### ISSUE TITLE
Implement react-starter-kit with nodemailer

### ISSUE THREAD

**Issue by paschalidi** [kriasoft/react-starter-kit#1006]
I am trying to make nodemail work with react-starter-kit 

I have googled around found some good posts like [this](http://javascript.tutorialhorizon.com/2015/07/02/send-email-node-js-express/)

But I am a bit inexperienced with Express so I cannot see the right way to implement this with the react-starter-kit. 

Would be nice if someone could give me a hint or two. 

Thanks in advance. 

PS. If there is more appropriate way I would love to listen .

**Comment by ulani** [comment]
@paschalidi   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
