### ISSUE TITLE
Consider getting started with Meteor instead of Flux

### ISSUE THREAD

**Issue by dandv** [kriasoft/react-starter-kit#101]
> Flux is complicated. Just choosing a Flux library is a project in itself. [All of these](https://github.com/kriasoft/react-starter-kit/issues/22) are Flux libraries.

> I love Back to the Future, but [Flux] is a mountain of complexity. The Flux philosophy might be great for a company with billions of users and billions of dollars. But if you try building for a billion people before you get to ten thousand, you'll just sink. So I don't think it's the right thing to start with.

> If you're trying to build something really good really quickly, and you don't know if your idea is any good, you don't want to get mired in details like Flux. If [...] you don't need a small army of people to maintain it and write it, you don't want Flux. This is where Meteor can help.

All of these are quotes from an excellent talk by @maxharris9 ([video](https://www.youtube.com/watch?v=-QtrkXKvQFc&t=329)), a developer who spend two weeks learning React and building several components with it. His conclusion, at the end of the video (16:38), was:

> If you're new to React, Meteor is the best way for you to get started with it. It's so much easier than messing around with Flux.

**Comment by frankleng** [comment]
Nothing against meteor. I use it, and it has come a long way. 
But you are never going to get the whole picture about Flux from a Meteor talk. 

There is nothing wrong with using the plain Facebook implementation of Flux. The whole point is to dispatch actions and have it flow through the stores. Async operations are contained within the action creators, and stores get their data from those results accordingly. 

I don't know how that's complicated... at least not more complicated than any of the existing patterns out there. 
Sure there are many Flux libs out there that can save you from boilerplating. But you should always start with the least amount of magic, it helps you understand the pattern at its core.

**Comment by goatslacker** [comment]
Meteor is pretty complicated as well, it has its share of magic. I'm lost trying to deal with the meteor package manager. Is there a help section/slack/gitter for meteor? @dandv

**Comment by dandv** [comment]
@goatslacker: there are many ways to [get help with Meteor](https://www.meteor.com/get-involved), and there's a Gitter too - https://gitter.im/meteor/meteor

**Comment by korczis** [comment]
:-1: 

This project is called react-starter-kit not meteor-starter-kit.

**Comment by AdamBrodzinski** [comment]
@dandv This is kind of a cross post from [issue 22](https://github.com/kriasoft/react-starter-kit/issues/22#id="issuecomment-128108252") but using ***flux with Meteor and React*** helps build scalable Meteor apps (scale as in large teams & lots of components). This is something that is hard to do without some kind of architecture that handles change in large codebases. Relying on global Session and even the bolted on reactive dicts for state don't handle state changes well.

I've written tens of thousands of lines of prod. Meteor code and after a while it gets really hairy when changing the app. Race conditions with reactive data sources start to become a problem. Talking with others who write large Meteor apps agree it becomes an issue at a certain point.

Flux helps solve this problem and using it has decreased bugs and has allowed us to finally speed up again (in dev time). It's also helped me enjoy using Meteor again! Getting started quickly is only half of the battle... maintaining it is another :+1: 

Here's the cross post from the other issue if it helps provide more context:

<br><br>


> What a wonderful example of the paradox of choice!
>No wonder that it's easier to get started with Meteor + React, than with Flux + React.

I think it's worth mentioning that ***flux doesn't replace Meteor***. In fact Meteor doesn't have *any* built in architecture to keep yourself from getting buried in a game of 'whack a mole' when changing large codebases. I did write [a spec](https://forums.meteor.com/t/flux-for-meteor-using-blaze-or-react-would-like-your-design-opinions/6651) for something based on flux to solve this (using Blaze) but that's off topic. 

However i've used Meteor + flux + React to have a pretty nice workflow with  @goatslacker 's Alt. This gives you Relay type benefits while still using flux. In this context, Alt's snapshots are handy because you can snap the state before a hot code reload and bootstrap on re-load. It also makes it easy to track mongo cursors and update the store on change. Alt seems to be one of the best choices so far with Meteor. I've used it in a large Meteor prod app and it's working great.

If interested I have a leaderboard repo with Meteor + Alt/Reflux + React:
https://github.com/AdamBrodzinski/meteor-flux-leaderboard

**Comment by constantx** [comment]
:-1: it'd be odd to clone this repo and find that you'll need Meteor. Nothing against Meteor, but it's better not having to have that opt-out.

As a starter it, this repo is create for getting started with flux architect. I've learned a lot about structuring the app and have been building on top of it for the past few weeks, and it's beeen great so far (minus the routing solution, which is a separate issue).

**Comment by AdamBrodzinski** [comment]
@constantx I agree, I think Meteor is out of scope for this repo. There's also other React/flux boilerplates for Meteor that people could use if they wanted to go that path.

**Comment by koistya** [comment]
I'm going to close this one as it sounds more like a question. But feel free to continue the conversation on this thread. You're also welcome to participate in discussions on [Gitter](https://gitter.im/kriasoft/react-starter-kit), [Appear.in](https://appear.in/react), or [StackOverflow](https://stackoverflow.com/tags/react-starter-kit).
