### ISSUE TITLE
how to invoke multiple api？

### ISSUE THREAD

**Issue by epubreader** [kriasoft/react-starter-kit#1010]
I want to display both hot news and latest news on the homepage,
I am new to react, how to do it? thanks.  

async action() {
    const resp = await fetch('/graphql', {
      method: 'post',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        query: '{news{title,link,contentSnippet}}',
      }),
      credentials: 'include',
    });
    const { data } = await resp.json();
    if (!data || !data.news) throw new Error('Failed to load the news feed.');
    return {
      title: 'React Starter Kit',
      component: <Layout><Home news={data.news} /></Layout>,
    };
  },

**Comment by forrest23** [comment]
just like this 

 body: JSON.stringify({
        query: '{movies{title,alt,original_title,year,images{large},rating{average},directors{name,alt}}comingsoonmovies{title,alt,original_title,year,images{large},rating{average},directors{name,alt}}}',
      })

**Comment by ulani** [comment]
@epubreader   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
