### ISSUE TITLE
Is usage of RUNNING_REGEXP in runServer.js a common/best practice?

### ISSUE THREAD

**Issue by buildbreakdo** [kriasoft/react-starter-kit#1015]
Spent a day trying to figure out why browser sync wasn't launching after making a move to HTTPS. Thought it was a configuration issue on the browser sync side. Come to find out that by removing the console.log statement in the `// Launch the server section` of `server.js` means browser sync will no longer be triggered because the console log is checked for a particular string match.

```
console.log(`The server is running at http://localhost:${port}/`);
```

Find removal of a console.log statement stopping a devtool from launching to be counter intuitive. Think at a minimum we should at least make this more clear as to what this console.log is doing and provide a warning, if not refactor away from this idea. Trying to better understand why this is setup this way before exploring other options. Cheers.

**Comment by ulani** [comment]
@buildbreakdo   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
