### ISSUE TITLE
Add and document possibility to run server in debug mode

### ISSUE THREAD

**Issue by apsavin** [kriasoft/react-starter-kit#1017]
It seems that people need a simple, documented way to run server with `--inspect` or `--debug` flag.

See #755 #396 

What if we'll add such possibility? If you agree, how to do it best? Via env variable?
I can implement it and send a PR, if you wish.

**Comment by ulani** [comment]
@apsavin   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
