### ISSUE TITLE
server error case the Process interruption

### ISSUE THREAD

**Issue by jiapengdeng** [kriasoft/react-starter-kit#1021]
```
if (pending) {
    throw new Error(`Server terminated unexpectedly with code: ${code} signal: ${signal}`);
}
``` 
those codes may case the process interruption,  this place should do not throw the Error

**Comment by buildbreakdo** [comment]
@koistya Think this might be related to #978 and your comment there.. quoting for context:

`A while ago there was a pull request tweaking tools/runServer.js or tools/start.js so that the server shuts down in case of an error. I think we need to rollback this commit.`

Think what is happening here is that webpack is retrying or rebundling and isn't given a chance to do so because of this thrown error. Commenting this code out, seemed to stop the app from crashing out during dev. Thoughts?

**Comment by buildbreakdo** [comment]
Adding @frenzzy too as I know this is build tool space he was in recently.

**Comment by buildbreakdo** [comment]
@koistya Okay, looks like the suspicion above was correct, finally figured out how to reproduce this crash. If a file is saved after `webpack building...` has been output to the terminal but not before the development server has relaunched -- thus kicking off a new rebuild -- the development server may crash (say may, because it is not altogether predictable but it is repeatable if you try enough times, race condition?).

This is a painful because if a save is made and rebundle kicks off and you notice an error in your code, fix it and _save again before the server has fully relaunched_ with the new bundle we end up hitting the line above in https://github.com/kriasoft/react-starter-kit/blob/master/tools/runServer.js and having to restart the development server manually. 

Possible solution is checking before throwing if rebundle is currently executing and don't throw or make this snippet not active in dev? 

I'm not even sure what value this code has. Was introduced in this commit: https://github.com/kriasoft/react-starter-kit/commit/5c3bc7f31e102027f594ff297964da9b864b6989. @haraldrudell any insight?

**Comment by ulani** [comment]
@jiapengdeng   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
