### ISSUE TITLE
How do we get query parameters in router? 

### ISSUE THREAD

**Issue by pvijeh** [kriasoft/react-starter-kit#1028]
for example in this route,  how would I get :placeSlug ?  

path: '/place/:placeSlug',

**Comment by frenzzy** [comment]
[https://github.com/kriasoft/universal-router/blob/master/docs/api.md#url-parameters](https://github.com/kriasoft/universal-router/blob/071e62470ee5a9d300d6879454a8f1cb9edd9576/docs/api.md#url-parameters)
```js
const route = {
  path: '/path/:param',
  action({ path, params, query }) {
    console.log(path, params, query);
  }
}
```

**Comment by ulani** [comment]
@pvijeh   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
