### ISSUE TITLE
Location missing? (universal-router)

### ISSUE THREAD

**Issue by Matol66** [kriasoft/react-starter-kit#1037]
Hi,

I'm looking for Location to push location state, but i can't find it in ../core/Location

Is it moved to other place?

cheers

**Comment by frenzzy** [comment]
Look at the [src/components/Link/Link.js](https://github.com/kriasoft/react-starter-kit/blob/2a293f506a1e4a8bc381b6a790a0b47b4d1bab57/src/components/Link/Link.js#L42)
```js
import history from '../../core/history';

// https://github.com/mjackson/history
history.push('/login');
```

**Comment by ulani** [comment]
@Matol66   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
