### ISSUE TITLE
Error Handling in Route and Component

### ISSUE THREAD

**Issue by archansel** [kriasoft/react-starter-kit#1049]
The way I understand on how RSK handling error is using this [server.js#L140](https://github.com/kriasoft/react-starter-kit/blob/master/src/server.js#L140) but this handler only use `ErrorPageWithoutStyle` component. As far as I understand, there is no way to reach `/error` route define in [here](https://github.com/kriasoft/react-starter-kit/blob/master/src/routes/error/index.js)

So far, in every route that might encounter an error (e.g. 403 forbidden, or 500 server error), I import `ErrorPage` and use it similar to not found route [here](https://github.com/kriasoft/react-starter-kit/blob/master/src/routes/notFound/index.js) so I can get styled error.

Is there any cleaner or proper way of doing error handling both in routes and components?

**Comment by ulani** [comment]
@archansel   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
