### ISSUE TITLE
Problem with URL when adding a slash at the end

### ISSUE THREAD

**Issue by sudharsan1988** [kriasoft/react-starter-kit#1052]
When I try to access url without ending with slash it works great but it's throwing "not found" error when we add a slash at end of the URL.

This one works fine:  https://demo.reactstarterkit.com/about

This is not working: https://demo.reactstarterkit.com/about/

Is this something to do with historyjs?

**Comment by ulani** [comment]
@sudharsan1988   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
