### ISSUE TITLE
Debugging server.js directly from a src folder

### ISSUE THREAD

**Issue by ndjordjevic** [kriasoft/react-starter-kit#1063]
Just wonder if there's a way to start/debug server.js from a src folder with babel-node or use generated source maps? I guess it's not since it imports css files and needs webpack to bundle it all together ...
In other words, how to tell Webstorm to connect generated server.js.map to a src/server.js, and put breakpoints there...
It's a pain to debug generated server.js from a build folder ...

**Comment by ndjordjevic** [comment]
OK, it automatically works in Webstorm 1017.1 EAP. Not sure if the mappings could be done in early versions.

**Comment by advance512** [comment]
Can you perhaps share how you got it to work in 2017.1 EAP?

When trying to run /src/server.js directly, I get:
`ERROR: only one instance of babel-polyfill is allowed`

**Comment by ulani** [comment]
@ndjordjevic   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
