### ISSUE TITLE
Table naming after connecting to psql

### ISSUE THREAD

**Issue by Mykybo** [kriasoft/react-starter-kit#1066]
I have connected to psql db.
Listing tables with \d looks ok:
```
                   List of relations
 Schema |       Name       |   Type   |     Owner      
--------+------------------+----------+----------------
 public | User             | table    | xxx
 public | UserClaim        | table    | xxx
 public | UserClaim_id_seq | sequence | xxx
 public | UserLogin        | table    | xxx
 public | UserProfile      | table    | xxx
```

but if I want to do any kind of select for example, I have to use "User" instead of just User, which suggests the " is included in the table name. Is this intended? If so, can I change it somehow?
(e.g. SELECT * FROM "User"; instead of SELECT * FROM User;)

**Comment by frenzzy** [comment]
Use lowercase for table names if you don't like to use quotes (need to rename table in your db).

**Comment by buildbreakdo** [comment]
@Mykybo If you have capital letters with postgres you have to put `"TableName"` around your table name. Lowercase the model names in your `src/data/model folder`, you'll also want to use underscores elsewhere too I assume instead of camelcase? 

Will also want to take a look at manually setting `createdAt: 'created_at'` and `updatedAt: 'updated_at'` in `src/data/sequelize.js`.
