### ISSUE TITLE
Have you considered writing CSS in JS? (helps to remove the folder for each component)

### ISSUE THREAD

**Issue by totty90** [kriasoft/react-starter-kit#110]
Hy!
Usually I write encapsulated components with CSS in JS. Take a look at this lib: https://github.com/hackhat/smart-css You are doing basically almost the same thing where you put the css file near the js file, therefore you could put the CSS into the JS. This could remove the need to have a folder for each component (exception if you need not-shared assets)

Also your long css names could be more beautiful `.ComponentName-elementName--modifier { }` (<- that's quite ugly IMO). Take a look at this [example](https://github.com/hackhat/tic-tac-toe-flux/blob/dev/src/js/components/Tile.jsx). I understand that with LESS, this is easier to do, but please consider looking into this approach too because I found it a delight to work with.

I really appreciate the help you are giving here with this lib!

**Comment by koistya** [comment]
You, you're right, long CSS class names are ugly. This has been fixed with the introduction of CSS Modules. What do you think about it? Inline CSS looks good, not sure how practical it is since plain CSS is better supported by text editors and IDEs.

I'm going to close this one as it's not a real issue or feature request. But feel free to continue the conversation on this thread. You're also welcome to participate in discussions on [Gitter](https://gitter.im/kriasoft/react-starter-kit), [Appear.in](https://appear.in/react), or [StackOverflow](https://stackoverflow.com/tags/react-starter-kit).
