### ISSUE TITLE
how about using react-dom-stream instead of ReactDom.renderToString

### ISSUE THREAD

**Issue by hienhuynhtm** [kriasoft/react-starter-kit#1124]
Hi guys,
How about this library: https://github.com/aickin/react-dom-stream

Regards,

**Comment by hienhuynhtm** [comment]
usage:
import ReactDOMStream from "react-dom-stream/server";

app.get('/', (req, res) => {
    // TODO: write out the html, head, and body tags
    var stream = ReactDOMStream.renderToString(<Foo prop={value}/>);
    stream.pipe(res, {end: false});
    stream.on("end", function() {
        // TODO: write out the rest of the page, including the closing body and html tags.
        res.end();
    });
});

**Comment by frenzzy** [comment]
ref: #402 (because it does not compatible with "critical path css" rendering approach)

Also even with stream rendering, code generation on the fly is still very slow. You may consider to start using server-side caching (nginx, varnish, etc.) in front of node.js application. It will speed up your app a lot and make streaming rendering useless.

**Comment by hienhuynhtm** [comment]
Yeah, I'm considering using nginx, the TTFB rather slow, usually take to 400 - 800ms.
