### ISSUE TITLE
HOWTO: setup login

### ISSUE THREAD

**Issue by AdamZaczek** [kriasoft/react-starter-kit#1170]
When trying to log in I get a message I'm in developer mode and I cant log in. What do I need to know to make the login work? I did search for a solution and without help I'm stuck for good :/

**Comment by langpavel** [comment]
Hi @AdamZaczek

At first, try ask correctly. ***Ultra login newbie question*** is really issue everyone wants answer, for free, as this is FOSS :smile:

At second, you should know something about OAuth, look at `passport` node module documentation, look at Facebook documentation and ask at correct places. I'm not sure how much people are on our gitter.im channel, but you can try luck there.

Then you can look at documentation and improve it :+1:

**Comment by Asalem1** [comment]
@AdamZaczek did you manage to get the issue sorted?

**Comment by AdamZaczek** [comment]
@Asalem1 Not with this started kit, I did what @langpavel wrote about, learnt how to implement login from scratch. Not sure if my solution is the best one tho, and I'm still working on it. I would love to see some best practices regarding doing a login with GraphQL apps.

**Comment by Asalem1** [comment]
@AdamZaczek I'm currently still working on having the information stored onto the DB (I'm knew to SQL), but from what I can tell by your initial error message, you would have to open up access to the app during development mode under facebook's settings (developers.facebook.com) and replace the secret, clientID, etc... in the config file. That should prevent the 'developer mode' error message you were getting for Facebook (if it was from Facebook). If you are still encountering issues, I would make sure to start your server's GET request like they do on the passportJS site and go from there (Do a search for routes under Facebook and copy paste their code - make sure to include the serializier and deserializer - http://passportjs.org/docs). The initial repo doesn't have a built in framework for the google or twitter login so that would have to be taken care of as well. Let me know if that works

**Comment by AdamZaczek** [comment]
This is some great help Asalem, I will definitely check it out, thank you a ton!

**Comment by AdamZaczek** [comment]
I made it work using your advice @Asalem1 , thank you so much! I'd like to add section about Facebook login to ReadMe.

**Comment by AdamZaczek** [comment]
@langpavel  Added info how to make FB login work. This might be useful to newcomers: https://github.com/kriasoft/react-starter-kit/pull/1258
Let me know it its k.

**Comment by Asalem1** [comment]
Awesome! Happy to hear, happy coding!

**Comment by ulani** [comment]
@AdamZaczek   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
