### ISSUE TITLE
Redundant Style in Header.css

### ISSUE THREAD

**Issue by joshuamanns** [kriasoft/react-starter-kit#1171]
There is a redundant style in  Header.css (`.root`) for the float and margin styles (vs the Navigation.css root style)

**Comment by ulani** [comment]
@joshuamanns   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
