### ISSUE TITLE
How to Nest Views?

### ISSUE THREAD

**Issue by ghost** [kriasoft/react-starter-kit#1172]
I'm trying to nest views - in vanilla implementations of React and using its router I can figure it out, but with this set up I'm not so sure. Haven't read anything on the docs yet. Any suggestions for how to nest or allow one route to have multiple views with different routes on the same page?

**Comment by frenzzy** [comment]
https://github.com/kriasoft/universal-router/blob/master/docs/api.md#nested-routes

**Comment by ulani** [comment]
@ghost  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
