### ISSUE TITLE
Demo URL isn't working (Err 403 - App is stopped)

### ISSUE THREAD

**Issue by joshuatalb** [kriasoft/react-starter-kit#1179]
The demo URL (https://demo.reactstarterkit.com/) is giving me a 403 error. Is it possible to start the web app again?

**Comment by crimedude22** [comment]
+1 demo app is still stopped

**Comment by langpavel** [comment]
Demo is running but TLS/SSL is not configured well

**Comment by Aadmaa** [comment]
@koistya  I get that error on the demo site as well, then (somewhat disconcertingly) am redirected here: https://datamgr DOT co/

**Comment by langpavel** [comment]
@koistya I believe it is an accident with redirection..

**Comment by ulani** [comment]
@joshuatalb   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
