### ISSUE TITLE
Update .travis.yml to push an updated image of RSK to Docker Hub

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-starter-kit#1181]
Update [`.travis.yml`](https://github.com/kriasoft/react-starter-kit/blob/master/.travis.yml) file so that when all the tests are passed, it would compile a new Docker image and push it to [`kriasoft/react-starter-kit`](https://hub.docker.com/r/kriasoft/react-starter-kit/) Docker Hub repository. Ref #1179.

**Comment by langpavel** [comment]
How you deal with forks running Travis too?

**Comment by langpavel** [comment]
Can this be set up in Travis itself?

**Comment by koistya** [comment]
@langpavel you can have conditional statements in `.travis.yml`. See [here](http://steven.casagrande.io/articles/travis-ci-and-if-statements/).

**Comment by ulani** [comment]
@koistya  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
