### ISSUE TITLE
Route /error is not used anywhere

### ISSUE THREAD

**Issue by comerc** [kriasoft/react-starter-kit#1182]
Is it true?

**Comment by langpavel** [comment]
This is related to [kriasoft/universal-router](https://github.com/kriasoft/universal-router#universal-router) *slightly* lacking documentation.

Answer I think is **yes**, since kriasoft/universal-router#48. Can you confirm, @koistya or @frenzzy?

**Comment by frenzzy** [comment]
Visitors should not be able to see permanent error on any page, but `/error` route can be useful for testing. Maybe we should start using this route for development mode only.

**Comment by ulani** [comment]
@comerc   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
