### ISSUE TITLE
facing slowness in user actions done through thunk middleware

### ISSUE THREAD

**Issue by shishirarora3** [kriasoft/react-starter-kit#1190]
Hi,

Anyone facing slowness in user actions. Sometimes a user action might dispatch many actions. Every action causes rerender of react. 

```javascript
const setAction()=>{
return async (dispatch, getState) =>{
     await dispatch(setAction1);
      dispatch(setNormalAction1);
      dispatch(setNormalAction2);
     await dispatch(setAction2);
     await dispatch(setAction2);
}
}
```

I am using above pattern of actions with redux-thunk. 

One option of redux-batched-subscribe in middleware helped in batching concurrent actions( setNormalAction*) and hence saved some renders. But still the performance is bad because of sequence required in thunk actions(setAction1*).

Any other approaches, you are following to scale this?

**Comment by comerc** [comment]
Promise.all() may be

**Comment by shishirarora3** [comment]
Promise.all() will not work for actions depending sequence. await fixes issue of bringing actions in sequence.

**Comment by comerc** [comment]
[We have a problem with promises](https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html) > Advanced mistake #3: promises vs promise factories

**Comment by phpeek** [comment]
@shishirarora3 

Please format Your code so it's easier to read and add syntax highlighting.

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

Can You give more info on Your use case ?

**Comment by shishirarora3** [comment]
> Do You use connect() to connect component to state ?
yes

> Which component is being rerendered ? Is it Your component or one of the components that come with RSK ?

No, but mine is a normal connected component with redux-thunk middleware.

**Comment by phpeek** [comment]
> No, but mine is a normal connected component with redux-thunk middleware.

Gotya.

In that case You'll see rerender of Your component every time You dispatch and action which changes part of state that component is connected to.

What I usually do is extract logic contained in actions to methods and execute them in necessary order. Then when all data is ready, dispatching single action with this data.

This might not be the case for You, as from what I see, Your actions depend on data in state set by other actions. In that case You might consider connecting Your component to part of state that is being changes by the last dispatched action. But again, this is very dependent on the way how Your state is designed.

I would need to have more specific examples, so that I can fully understand Your use case.

**Comment by shishirarora3** [comment]
I guess your solution is similar to redux-batched-subscribe and its giving good improvement.

**Comment by ulani** [comment]
@shishirarora3   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
