### ISSUE TITLE
Comments for package.json configs especially for style rules!

### ISSUE THREAD

**Issue by Stupidism** [kriasoft/react-starter-kit#1207]
1. Why `react/prefer-stateless-function` is closed? Is there a reason?
Recommended config:
```
      "react/prefer-stateless-function": ["error", { "ignorePureComponents": true }]
```
2. Why `import/extensions` is closed? Only for `universal-router`?
3. Why `import/no-extraneous-dependencies` is closed?
Recommend to add comments 
```json
  "//": "Rule `import/no-extraneous-dependencies` not supporting nested package.json yet",
  "//": "https://github.com/benmosher/eslint-plugin-import/issues/458",
  "eslintConfig": {
    "rules": {
      "import/no-extraneous-dependencies": "off",
    }
  }
```
4. Recommended config for `no-console`
```json
   "no-console": ["warn", { "allow": ["warn", "error", "info"] } ],
```

**Comment by frenzzy** [comment]
1. The reason: #961
2. For any libs which support tree shaking of the box, maybe we should use
```json
"import/extensions": ["error", "always", {"js": "never", "jsx": "never", "mjs": "never"}]
```
3. Yes, because of unsupported nested package.json
4. 👍 

PR is welcome! :)

**Comment by Stupidism** [comment]
I'm doing a PR.
And why is `react/jsx-filename-extension` closed, too?

**Comment by Stupidism** [comment]
https://github.com/kriasoft/react-starter-kit/pull/1210 @frenzzy please review

**Comment by ulani** [comment]
@Stupidism   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
