### ISSUE TITLE
feature/react-intl issue with Safari on OSX

### ISSUE THREAD

**Issue by zirho** [kriasoft/react-starter-kit#1211]
Error formatting relative time.
getting enormous number of errors in console

node 6.9.2
yarn 0.19.1

```
[React Intl] Error formatting relative time.
```

![image](https://cloud.githubusercontent.com/assets/1251296/24723626/1d91020e-19fd-11e7-9de2-e5aa1cdfabab.png)

**Comment by langpavel** [comment]
Huh, sorry, but you need a `intl` polyfill. It can be my bad, fact is that only Safari does not support `intl`...

**Comment by langpavel** [comment]
@zirho Can you add polyfill for this?

**Comment by langpavel** [comment]
Is this still an issue?

**Comment by langpavel** [comment]
May be we should convert number timestamps to date instance..

**Comment by ulani** [comment]
@zirho   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
