### ISSUE TITLE
static content in sub folder/url, not in root

### ISSUE THREAD

**Issue by atalebagha** [kriasoft/react-starter-kit#1217]
I have created multiple mini apps each using a separate RSK build, and I want to publish each one in it's own sub folder.

example:
www.mycustomdomain.com/app1
www.mycustomdomain.com/app2

The problem with the above is that routing doesn't work when the root of the app is not "/".  Is there a workaround for the above solution.

Any help would be appreciated.

Thanks!

**Comment by phpeek** [comment]
RSK doesn't support that out-of-the-box.

What You should do is to modify Your `./src/core/router.js` file in both apps.

## src/core/router.js (app1)
```js
export default new Router(routes, {
  baseUrl: '/app1',
});
```

## src/core/router.js (app2)
```js
export default new Router(routes, {
  baseUrl: '/app2',
});
```

**Comment by luffyZh** [comment]
I have encountered the same problem, may I ask whether it has been solved? Could you give me a Demo

**Comment by ulani** [comment]
@atalebagha   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
