### ISSUE TITLE
Why can not I get a user?

### ISSUE THREAD

**Issue by cubooks** [kriasoft/react-starter-kit#1226]
Why can not I get a user when rendering on a server? 

/src/data/queries/post.js - 
`resolve: async(parent, { id }) => {
    const user = parent.request.user; //undefined
  },`

On the client side everything is fine, but when rendering on the server there is no.

help me!

**Comment by cubooks** [comment]
I was looking for solutions on the Internet, but I could not find them.

Here is my temporary solution to the problem. As it turned out when you post requests to req, you could not get the user's data.

`//
// TODO
// Fixed req.user = undefined from server render
// -----------------------------------------------------------------------------
app.get('*', (req, res, next) => {
  const user = req.user;
  if (user) {
    app.set('user', req.user);
  }
  next();
});

app.post('*', (req, res, next) => {
  const user = app.get('user');
  if (user) {
    req.user = user;
  }
  next();
});`

**Comment by langpavel** [comment]
@cubooks You are doing totally wrong by setting user into **server global state** (by calling `app.set`).
By this way you are opening **massive security hole!** (every successive (or may be almost parallel) request will think that is made by last user GET)
You should look at express — how it works — learn a little about middleware, how to use request, cookies (and session if it is really necessary).
I will edit your post above, because I don't want anyone to even try this!

**Comment by langpavel** [comment]
Please, don't afraid to ask in this thread, if I have a time a can answer you :-)
