### ISSUE TITLE
Using MediaElement.js: ReferenceError: Element is not defined

### ISSUE THREAD

**Issue by kevin-chau** [kriasoft/react-starter-kit#1234]
I'm trying to set up the node package MediaElement.js (https://github.com/mediaelement/mediaelement) with react starter kit.

I'm following this usage guide on how to integrate the library with react:
https://github.com/mediaelement/mediaelement/blob/master/docs/usage.md#react

I'm running in to the following `ReferenceError` when starting up my application:
```
/Users/kevinchau/TReactr/node_modules/mediaelement/build/mediaelement-and-player.js:8790
})([Element.prototype, CharacterData.prototype, DocumentType.prototype]);
    ^
ReferenceError: Element is not defined
    at Object.__dirname.27.2 (/Users/kevinchau/TReactr/node_modules/mediaelement/build/mediaelement-and-player.js:8790:5)
    at s (/Users/kevinchau/TReactr/node_modules/mediaelement/build/mediaelement-and-player.js:11:257)
    at e (/Users/kevinchau/TReactr/node_modules/mediaelement/build/mediaelement-and-player.js:11:428)
    at Object.<anonymous> (/Users/kevinchau/TReactr/node_modules/mediaelement/build/mediaelement-and-player.js:11:446)
```

**Comment by ucay** [comment]
You should render the package in client side only.
see #186

**Comment by langpavel** [comment]
Yes, client side only..

**Comment by ulani** [comment]
@kevin-chau   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
