### ISSUE TITLE
when it's support typescript?

### ISSUE THREAD

**Issue by Ive4** [kriasoft/react-starter-kit#1252]
many people use typescript to write react
and i need too,but the react-starter-kit not
do you have a plan to support typescript?

**Comment by jonirrings** [comment]
bro, there are many people using flowtype too.
I think just to stay in js is the best.
that is what both ts and flow compatible.

if you prefer ts, just refactor this project to ts. it is not much work,

**Comment by langpavel** [comment]
Flow is my favorite

**Comment by jonirrings** [comment]
@langpavel work with ts in office but with flow personally.

**Comment by bingo-lumity** [comment]
I have a pre-pull request feature branch that needs some testing. I'm not sure if this kind of feature branch is appropriate to include in this repository. At least with Redux, React-Intl, and Apollo, those are additive on top of the main react-starter-kit. But Typescript is a replacement over Flow, and that is a very different change altogether.

My team will be using this [TypeScript feature branch](https://github.com/Lumity/react-starter-kit/tree/feature/typescript) to do some spikes based on our own architectural needs in any case, but I mention it here in case you find it useful.

**Comment by piglovesyou** [comment]
@langpavel @frenzzy At the end of 2019, I feel the **master branch should be in TypeScript** and possibly the JS version can be archived on feature/legacy branch. What would you say? It's obvious that [TypeScript covers the best](https://2018.stateofjs.com/javascript-flavors/overview/) and it'll go more in the upcoming survey, although I also dug into Flow types before. I can state more reasons but simply I would love to know what's in your mind today.

**Comment by frenzzy** [comment]
There are a trade off between keeping the entry threshold as low as possible (a kit with best practises for developers of different levels) and providing as much as possible for the fastest up and running (a kit for advanced developers and probably very opinionated).

When we previously discussed this concern with @koistya a few years ago we come up with an opinion that react-starter-kit should go with first path, otherwise we would integrate `relay` into the master brunch. But we need an advanced kit for ourselves anyway, so [react-firebase-starter](https://github.com/kriasoft/react-firebase-starter) was introduced. Since that time a lot of good [starer kits](https://ru.react.js.org/community/starter-kits.html) was introduced by different teams including [create-react-app](https://create-react-app.dev/).

Now in 2019 I believe we should support typescript out of the box but keeping compatibility with javascript too so both `.js` and `.ts` files will work. Also I am thinking that in order to make RSK better and more competitive with other starters, it might be worth introducing more opinionated things or even merge the best from RSK and FSK plus start keep focus on a one project only. Would be very cool to hear what @koistya's thoughts on this.

**Comment by ulani** [comment]
@Ive4   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
