### ISSUE TITLE
Using Sequelize

### ISSUE THREAD

**Issue by brian-kilpatrick** [kriasoft/react-starter-kit#1255]
Sorry if this is the wrong place to be asking this but is there a way we could get a recipe for how you are utilizing Sequelize? Seems like it is different than every tutorial I've come across and I'm just unclear as to whats happening, why you chose this way, migrations, and why it doesn't work using the way described in the Sequelize docs(using the CLI)

**Comment by buildbreakdo** [comment]
@brian-kilpatrick Would redo that section of the starter kit and run `sequelize init` in the data folder and rewire everything up, not too sure why the setup diverges from sequelize docs, could possibly be the case that GraphQL docs were followed for folder layout/filenames instead of Sequelize docs? Just a guess.

Figure out a better way please make a pull request. 

Issue might help just a little:
https://github.com/kriasoft/react-starter-kit/issues/1137

**Comment by ulani** [comment]
@brian-kilpatrick   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
