### ISSUE TITLE
How can I pass a param from Home component to queries/news.js

### ISSUE THREAD

**Issue by duydk** [kriasoft/react-starter-kit#1263]
I use branch "feature/react-intl", and I'd like to pass some param named '**myParams**' in the url on **data/queries/news.js** like this: 
const url = 'https://api.rss2json.com/v1/api.json' + '?param=myParams';

How can I pass '**myParams**' from **routes/home/Home.js** to **data/queries/news.js**?
Thanks alot!

**Comment by langpavel** [comment]
See universal-router docs or it's very short and readable source codes

**Comment by ulani** [comment]
@duydk   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
