### ISSUE TITLE
Webstorm IDE Integration dead link in quickstart

### ISSUE THREAD

**Issue by ckeeney** [kriasoft/react-starter-kit#1265]
The Webstorm IDE integration link in the [Quick Start](https://github.com/kriasoft/react-starter-kit/blob/master/docs/getting-started.md#quick-start) points at https://www.jetbrains.com/webstorm/help/create-new-project-react-starter-kit.html, which is a 404.

I have found JetBrains docs for creating a new project based on this boiler plate, but they are outdated.

https://www.jetbrains.com/help/webstorm/2017.1/generating-a-project-from-a-framework-template.html#d88767e51

Since these docs were written, they have added more templates, but have removed the template based on this project in favor of the official `create-react-app` setup.

![image](https://cloud.githubusercontent.com/assets/8799010/26040278/9b7c9e4a-38d8-11e7-8eb0-21fd840f5505.png)

**Comment by jonirrings** [comment]
yes, it is outdated.
for now you must install create-react-app globally.
2 years ago, when I start to learn react, webstorm provided this repo as template/boilerplate, and thanks to kriasoft, I've learned much from this repo.

**Comment by ckeeney** [comment]
I don't really have a question or problem, but the link in the docs should be removed.  That's why I created this issue.  I can open a pull request removing it now.

**Comment by ulani** [comment]
@ckeeney   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
