### ISSUE TITLE
Yeoman generator does not include a .gitignore

### ISSUE THREAD

**Issue by ckeeney** [kriasoft/react-starter-kit#1266]
The [Yeoman generator](https://www.npmjs.com/package/generator-react-fullstack) for react-starter-kit does not have a `.gitignore`.  At a minimum, both `node-modules` and `build` directories should be added to `.gitignore`.

**Comment by langpavel** [comment]
I'm not sure if yeoman generator is maintained. Latest commit c23e08c on Mar 13. 2016.

@koistya, Have you any metrics how many users use them?

**Comment by ckeeney** [comment]
If the Yeoman generator is no longer maintained, then I think it should be pulled from the [Getting Started](https://github.com/kriasoft/react-starter-kit/blob/master/docs/getting-started.md#1-get-the-latest-version) instructions.  I'm happy to add it to #1267 if that's the case.

However, that would mean the only documented way to use this boiler plate is with `git clone`.  This is pretty user-unfriendly if you happen to already have a git repo.

**Comment by langpavel** [comment]
@ckeeney I'm maintaining and using this starter via git only. I'm also maintaining feature branches. The only way how to get features is through git.

I have `rsk` remote added on my private repos and periodically merging from my favorite branch from `rsk` remote. This way I have repository up to date with latest features and additions. Yes, there are merge conflicts sometimes, but I have fresh codebase and I know what changed. The best way by my opinion.

**Comment by ulani** [comment]
@ckeeney   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
