### ISSUE TITLE
Flow errors: "Required module not found"

### ISSUE THREAD

**Issue by bityogi** [kriasoft/react-starter-kit#1278]
This starter kit has  the /src/createFetch.js file declared to be a /* @flow */ typed.

However, there are certain flow errors that show up:

- isomorphic-fetch Required module not found [Line 12]

- parameter 'url' Missing annotation [Line 38]

- parameter 'options' Missing annotation [Line 38]

I guess, I could fix the last 2 errors by modifying the code to:

`return (url : string, options : { headers : {} }) => ((url.startsWith('/graphql') || url.startsWith('/api')) ?`

But not sure what to do about the first error. I've tried [this](https://github.com/facebook/flow/issues/2092) fix, but it didn't remove the flow error.

_FYI, I'm using Atom 1.17.0 on a Mac. With nuclide 0.223.0_

**Comment by ulani** [comment]
@bityogi   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
