### ISSUE TITLE
postcss-import duplication

### ISSUE THREAD

**Issue by pavel06081991** [kriasoft/react-starter-kit#1280]
For example we have file variables.css and we have files menu.css, layout.css, footer.css in which we import variables.css. As a result the output file will contain content of variables.css 3 times. How can we fix it?

**Comment by frenzzy** [comment]
Remove from `variables.css` everything except variables definition.

**Comment by pavel06081991** [comment]
@frenzzy, then I will have duplications of variables.

**Comment by frenzzy** [comment]
Variables are not represented in the final css, they are useful for development mode only.

**Comment by pavel06081991** [comment]
@frenzzy, even in production mode I see the repeated variables in the output css files:

this part is repeated many times(as many times as I import variables.css into other css files)
```
:root {
  --primaryColor: red;
}
```

**Comment by frenzzy** [comment]
Looks like you had removed [`postcss-custom-properties`](https://github.com/kriasoft/react-starter-kit/blob/7415429172016c977bdd91f3915c909267b65f94/tools/postcss.config.js#L19-L21) plugin or configured it with option `preserve: true`, then you also need to disable [`postcss-import`](https://github.com/kriasoft/react-starter-kit/blob/7415429172016c977bdd91f3915c909267b65f94/tools/postcss.config.js#L16-L18) to transfer the control over the css `@import`s to css-loader to deduplicate them.

**Comment by pavel06081991** [comment]
@frenzzy, thank you very much, I'll check

**Comment by ulani** [comment]
@pavel06081991   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
