### ISSUE TITLE
How to merge the <style> tags into one?

### ISSUE THREAD

**Issue by xingyun1li** [kriasoft/react-starter-kit#1288]
I've found that in src/server.js:
``` js
data.styles = [
   { id: 'css', cssText: [...css].join('') },
];
```
but, in src/client.js:
```js
const elem = document.getElementById('css');
if (elem) elem.parentNode.removeChild(elem);
```
does it means that in the `<Html>` component, the prop *styles* has no means?
It seams that isomorphic-style-loader will inject `<style>` nodes to the `<head>` tag with an id...

**Comment by frenzzy** [comment]
In the browser `isomorphic-style-loader` mounts css for currently mounted (visible) components. Than more components with its own styles do you have then more `<style>` tags will be in the `<head>` of document. `Id`s are used to easily remove styles from DOM for components which is being unmounted.

On server-side they are combined together into single `<style>` tag because of implementation and this tag removed on client-side after initial render.

ref #1132 (Reuse styles between server and client)

**Comment by frenzzy** [comment]
Why you want to merge all styles into single `<style>` tag? It could slow down the app in case of frequent components updates (mount/unmount).

**Comment by xingyun1li** [comment]
Ohh, you're right! I just haven't got the point of isomorphic style~
Thanks a lot!
