### ISSUE TITLE
MongoDB and Mongoose

### ISSUE THREAD

**Issue by nschurmann** [kriasoft/react-starter-kit#1289]
Great kit!, my congratulations to the developers!

Is there a pull request or something that integrates mongodb and mongoose instead on sequelize?, i'm not very interiorized with graphQL but i would love to use it with mongodb.

**Comment by ibudisteanu** [comment]
You can do that, by simplying deleting the GraphQL usage and uninstalling the GraphQL modules. After you do that, you just need to install the Mongose node_module and you are ready to use it.

**Comment by nschurmann** [comment]
I think you didn't understand the question, is to use this but with mongoose instead of sequelize.

**Comment by ibudisteanu** [comment]
So, Mongose can be considered as an ORM for MongoDB for node.js. Sequelize (although I have never used it), it's exactly like a simple ORM, but this case for GraphQL.  So, I truly believe that there is absolutely no need to convert an object model to a relational model or otherwise. Besides, Mongo Data is in JSON. One of the great advantage of a NonSQL DB like MongoDB or others JSON based is to remove the overhead of using an ORM.

For instance, in my project, I am using Redis. Although, my backend sends JSON objects from DB, I wrap them in a similar way like sequelize especially to enable them methods.

**Comment by nschurmann** [comment]
Mongoose is an ODM, sequelize ia an ORM but for MySQL, PostgreSQL, and others. Basically is, get rid of sequelize, install mongoose, install mongodb and define a data model and the queries, but nvm, I figured that out myself, I'm closing this.

**Comment by ayxos** [comment]
hey @nschurmann do you have the version with mongoDB?? i am looking for that

**Comment by oshalygin** [comment]
why was this closed?

Agreed with @nschurmann , totally unrelated to sequelize(which is an ORM for relational DBs such as sqllite or mysql)

**Comment by langpavel** [comment]
This is closed without answer, but I thing this a question, not issue at all. So it's good that it's closed :slightly_smiling_face:

**Comment by oshalygin** [comment]
@langpavel I guess that makes sense.  SO is probably best for this sort of question/answer thing too.
