### ISSUE TITLE
connecting Redux to component is stopping the component to access the propTypes

### ISSUE THREAD

**Issue by ibudisteanu** [kriasoft/react-starter-kit#1304]
When I conenct a Children Component to Redux, the children is no longer receving the access my parent's getChildrenContext using the propTypes. 

I have a component:

```js
class MyChildren extends React.Component{

  static contextTypes = {
    refAuthenticationModal: PropTypes.any,
  };

buttonClicked(){
      this.refAuthenticationModal.showModal();
}

....
}
```

The component MyChildren receive the required context properties from the parent, but when I connect the component to Redux using the connect function, my children component is not longer receving its "inherited" properties from parent.
```js
function mapState (state){
  return {
    userAuthenticated : state.userAuthenticated,
  }
};

function mapDispatch (dispatch) {
  return {
    dispatch : dispatch,
  }
};

export default connect(mapState, mapDispatch)(MyChildrenComponent);
```

My parent

```js
class Parent extends React.Component{

  static childContextTypes = {
    refAuthenticationModal: PropTypes.any,
  };

  getChildContext() {
    return {
      refAuthenticationModal: this.refAuthenticationModal,
    }
  };
}
```

**Comment by langpavel** [comment]
You have
```js
buttonClicked(){
      this.refAuthenticationModal.showModal();
}
```
I believe you should have
```js
buttonClicked(){
      this.context.refAuthenticationModal.showModal();
}```

**Comment by ulani** [comment]
@ibudisteanu   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
