### ISSUE TITLE
Server Side Rendering with Apollo Client

### ISSUE THREAD

**Issue by manoj150283** [kriasoft/react-starter-kit#1311]
I am using react-intl branch and I understand that by default this branch comes with SSR. Home, About us pages are working perfectly with SSR but when I am trying to implement the same on another page, it is only showing the static html on SSR and not the dynamic data that comes from graphql. My code is like this:

![image](https://user-images.githubusercontent.com/7291281/27054134-87810e14-4fdd-11e7-9373-cc7094f88369.png)
![image](https://user-images.githubusercontent.com/7291281/27054159-9f51efb8-4fdd-11e7-86e8-e3a32c0cbf4f.png)
![image](https://user-images.githubusercontent.com/7291281/27054177-b0bf6fdc-4fdd-11e7-816c-7a797d24d1bf.png)

This is the right way to do this for SSR or am I missing something ?

**Comment by langpavel** [comment]
Hi.
- Where you call `this.props.getLeads()`?
- You can use Apollo on `react-intl` branch for data fetching, it is just a breeze
- If data are fetched, then Apollo does not make additional query if it is not needed

**Comment by ulani** [comment]
@manoj150283   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
