### ISSUE TITLE
It seems chunk feature not working well with babel-plugin-xxx

### ISSUE THREAD

**Issue by Stupidism** [kriasoft/react-starter-kit#1315]
https://github.com/umidbekkarimov/babel-plugin-material-ui/issues/2
Also `babel-plugin-lodash`

https://github.com/Stupidism/react-starter-kit/tree/feature/material-ui

1.Original chunk size
`admin.chunk.js     104 kB       0  [emitted]         admin`

2.With `babel-plugin-material-ui` and import with {}
```
// routes/Admin.js
import { TextField, SelectField, FlatButton } from "material-ui";
```

`admin.chunk.js    1.29 MB       0  [emitted]  [big]  admin`

3. Import seperately
```
// routes/Admin.js
import TextField from "material-ui/TextField";
import SelectField from "material-ui/SelectField";
import FlatButton from "material-ui/FlatButton";
```
`admin.chunk.js     451 kB       0  [emitted]  [big]  admin`

**Comment by ulani** [comment]
@Stupidism   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
