### ISSUE TITLE
Remove duplicates from server and client head rendering

### ISSUE THREAD

**Issue by apsavin** [kriasoft/react-starter-kit#1319]
There are two places now where we update title of the document:

https://github.com/kriasoft/react-starter-kit/blob/master/src/client.js#L50
https://github.com/kriasoft/react-starter-kit/blob/master/src/components/Html.js#L42

It would be nice to have only one.
By the way, if you need  to change meta-tags, for example, you need to duplicate such logic, too.
It may be important (I heard google search engine can execute js and parse SPAs even without SSR, not sure it's true though)

**Comment by ulani** [comment]
@apsavin   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
