### ISSUE TITLE
Build failed when running yarn run build -- --release

### ISSUE THREAD

**Issue by puttyman** [kriasoft/react-starter-kit#1324]
Getting a couple of the errors below when I try to create a build:

` ERROR in ./~/css-loader?{"sourceMap":false,"modules":false,"minimize":true,"discardComments":{"removeAll":true}}!./~/normalize.css/normalize.css
    Module build failed: Error: ENOENT: no such file or directory, open 'C:\Users\user\Documents\project\node_modules\svgo\.svgo.yml'
        at Object.fs.openSync (fs.js:584:18)
        at Object.fs.readFileSync (fs.js:491:33)
`

I found the issue seems to be related to yarn. After I tried deleting my **node_modules**, **yarn.lock** and **.yarclean**. Reinstalling the deps the build would work again.

Any ideas?

Many thanks.

**Comment by langpavel** [comment]
No, this is related to some postcss svg processing plugin, may be directly to `svgo`. Try search here: https://www.npmjs.com/browse/depended/svgo

**Comment by WiktorKa** [comment]
I think this is related to this yarn bug: https://github.com/yarnpkg/yarn/issues/2276

**Comment by ulani** [comment]
@puttyman   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
