### ISSUE TITLE
Ignore graphql document in test environment 

### ISSUE THREAD

**Issue by zhn1010** [kriasoft/react-starter-kit#1325]
Hi everyone!
How can we ignore imported graphql documents when webpack is not supported such as test environment.

There is a [solution](https://github.com/remind101/jest-transform-graphql) for Jest but how can we do the same with Mocha?

**Comment by ulani** [comment]
@zhn1010   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
