### ISSUE TITLE
Cannot read property 'pathname' of undefined

### ISSUE THREAD

**Issue by charyorde** [kriasoft/react-starter-kit#1341]
I have below code in a custom route at `routes/apps/index.js`
```js
const route = await router.resolve({
  path: history.location.pathname,
  query: queryString.parse(history.location.search),
});
```
When I navigate the route in the browser, I get the `Cannot read property 'pathname' of undefined`. What could be causing this?

**Comment by valeeum** [comment]
is this happening server side or client side?  the history object doesn't exist on the server.

**Comment by charyorde** [comment]
code at `src/routes` is server side I presume? Just don't know how to get current pathname on the server without `history` object.

**Comment by valeeum** [comment]
that gets run on both server and client.  I had the same issue yesterday and ended up solving it by adding 'path' and 'query' properties to the context on the server and client.

**Comment by charyorde** [comment]
`this.props.context` is `null` in a component for me. How did you access the `context` object?

**Comment by valeeum** [comment]
it's this.context but you need to specify contextTypes first - https://facebook.github.io/react/docs/context.html

**Comment by langpavel** [comment]
`history` object exists on server side too, but not as global object, it's can be derived (and it is) from `request` (or `req`) in express handler and then it's passed to router `context`. See `server.js` source

**Comment by ulani** [comment]
@charyorde   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
