### ISSUE TITLE
webpack-flush-chunks and async component?

### ISSUE THREAD

**Issue by charyorde** [kriasoft/react-starter-kit#1344]
[webpack-flush-chunks](https://github.com/faceyspacey/webpack-flush-chunks) ? Could this be the solution to async component.

[useful ref](https://medium.com/faceyspacey/code-cracked-for-code-splitting-ssr-in-reactlandia-react-loadable-webpack-flush-chunks-and-1a6b0112a8b8)

**Comment by frenzzy** [comment]
Looks interesting, would you like to create a PR?

**Comment by charyorde** [comment]
Still fiddling with it...

**Comment by ulani** [comment]
@charyorde   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
