### ISSUE TITLE
Just starting out, a few questions

### ISSUE THREAD

**Issue by keithcollins** [kriasoft/react-starter-kit#1350]
Hello, just a few basic things I don't quite understand about the RSK implementation and can't seem to find answers to in any of the RSK docs. If there's a doc somewhere that I've missed, please point me in the right direction. If it helps, I'm using RSK with data that's in a postgresql db, and was able to modify data/sequelize.js to connect to it.

Here's a route I've been working on, which is simply modified from routes/home/index.js in RSK:

```js
async function action({ fetch }) {
  const resp = await fetch('/graphql', {
    body: JSON.stringify({
      query: '{qbookmarks{bookmark_id,title,url,content,tags,type,last_updated}}',
    }),
  });
  const { data } = await resp.json();
  if (!data || !data.qbookmarks) throw new Error('Failed to load bookmarks.');
  // get all unique tags
  const allTags = [...new Set(data.qbookmarks.map(d => d.tags))];
  
  return {
    chunks: ['home'],
    title: 'Readux',
    component: <Layout><Home allTags={allTags} qbookmarks={data.qbookmarks} /></Layout>,
  };
}
```

And this is the simple query that calls, which I have in data/queries/qbookmarks.js

```js
import { GraphQLList as List } from 'graphql';
import bookmarks from '../models/bookmarks';
import bookmarks_type from '../types/bookmarks_type';

const qbookmarks = {
  type: new List(bookmarks_type),
  resolve() {
    return bookmarks.findAll({
      order: [
        ['last_updated', 'DESC'],
      ],
    });
  },
};

export default qbookmarks;
```

This is working fine. But, **question 1:** is the above the appropriate way to query graphql directly from a route? I'm talking specifically about this bit:

```js
  const resp = await fetch('/graphql', {
    body: JSON.stringify({
      query: '{qbookmarks{bookmark_id,title,url,content,tags,type,last_updated}}',
    }),
  });
```

All of the route samples in the RSK docs call some ambiguous API endpoints, suggesting there's some other way routes should fetch data that isn't in the implementation. For example, in docs/data-fetching.md:

```js
{
  path: '/posts/:id',
  async action({ params, fetch }) {
    const resp = await fetch(`/api/posts/${params.id}`, { method: 'GET' });
    const data = await resp.json();
    return { title: data.title, component: <Post {...data} /> };
  }
}
```

And in docs/recipes/how-to-implement-routing.md

```js
  {
    path: '/tasks/:id',
    action({ params }) {
      const resp = await fetch(`/api/tasks/${params.id}`);
      const data = await resp.json();
      return data && {
        title: data.title,
        component: <TodoItem {...data} />
      };
    }
  }
```

Since routes/home/index.js in the implementation is getting data from an RSS feed and not a more common data source, I have no idea which parts of it are specific to that use case. And since the sparse docs on the topic suggest fetching from some other endpoint, which suggests a different architecture altogether, it's even more confusing.

Anyway, **question 2** is more specific and straightforward. Suppose I wanted to fetch one bookmark by its ID, which the route gets from a param. Would the graphql query in the route look like this?

```
{
  bookmarks(bookmark_id:${params.bookmark_id}) {
    bookmark_id,
    title,
    url,
    content,
    tags,
    type,
    last_updated
  }
}
```

If not, how do you get the param into the query. And **question 3**, in the query itself, which would be somewhere in data/queries/, how do you pick up the `bookmark_id` parameter? There's only one example in RSK that seems to do something like this, which is data/queries/me.js, but I don't quite get it, and no other file in all of RSK refers to or uses the `me` query.

And **question 4**, can all of the queries for one model go into one file? If so, how should that file be setup? If not, does every single possible query need its own file? Clearly there are a few basic things here I don't understand but there's so much going on in this implementation, passing between graphql and sequelize and others, that it's tough to even figure out what to read.

If I'm able to get all of this figured out (and don't just give up and stick to my simple Express setup) I'd be happy to write some more robust documentation for beginners. Thanks!

**Comment by koistya** [comment]
The routing solution used in RSK is very customizable, it's better to adapt it to your application needs. For example, if you're using a GraphQL backend for all of your routes, it might be a good idea to remove all the fetching logic from routes, leaving just a path, GraphQL query, the list of components/chunks to load and what to render. For example, each route may look like this:

```jsx
import React from 'react';
import { graphql } from 'relay-runtime';

export default {
  path: '/bookmarks/:id',
  query: graphql`query BookmarkQuery($id: GraphQLID!) {
    me { ...Layout_me }
    bookmark: node(id:  $id) { ...Bookmark_bookmark }
  }`,
  components: () => [
    import(/* webpackChunkName: 'main' */ '../../components/Layout'),
    import(/* webpackChunkName: 'bookmark' */ './Bookmark'),
  ],
  render: (data, [Layout, Bookmark]) => (
    <Layout me={data.me}>
      <Bookmark bookmark={data.bookmark} />
    </Layout>;
  ),
}
```

And put data fetching and async chunk loading code into UniversalRouter's `resolveRoute` option. So that, whenever a user navigates to /bookmarks/123 your router will start fetching data and loading missing JavaScript chunks in parallel, and after it's done, it would call route.render(..) method.

BTW, if you're using an existing database, it might be better to use Knex instead of Sequelize, plus you can have API endpoint in a separate project in order to keep things clean in both front-end and api server parts. I'm quite successfully using this template [kriasoft/nodejs-api-starter](https://github.com/kriasoft/nodejs-api-starter) in all of my latest projects, it works great, allows to build an API backend in under two weeks, and I use RSK just for the front-end part including server-side rendering.

If you GraphQL types implement Relay's Node interface, then you will be able to fetch individual items by their IDs via `node(id)` field (see the GraphQL query above). The `me` field in GraphQL represents a currently authenticated user (or, it might also be a guest user in some type of apps).

Regarding Question 4, I would group queries and mutations by model, e.g. create Bookmark.js and put all the bookmark related queries and mutations into that file. Here is an example:

![image](https://user-images.githubusercontent.com/197134/27820829-ccafbafe-60a8-11e7-9e23-551d0ac9a0a7.png)

https://twitter.com/ReactStarter/status/875636837741608961

BTW, how do you think, should we put GraphQL-based routes and Relay integration onto the master branch in RSK?

**Comment by frenzzy** [comment]
Could be useful:
- Remove data API endpoint from the boilerplate - PR #1057
- Integrate Relay "Modern" - PR #1250

**Comment by keithcollins** [comment]
Thanks @koistya! That's all really helpful. I'm going to try all of this, but at the moment still having trouble understanding the relationship between the graphql query in the route and the sequelize query in `/src/data/queries/*`

If I do something like `bookmark: node(id:  $id)` in the graphql query in the router, how does the sequelize query in `/src/data/queries/*` pick up that ID? I thought it would be something like

```js
const bookmarkById = {
  type: bookmarks_type,
  resolve({request}) {
    return bookmarks.findAll({
      where: {
        bookmark_id: request.params.bookmark_id
      }
    });
  },
};
```

But `request.params.bookmark_id` is undefined, and graphql returns: `"Unknown argument \"node\" on field \"bookmarkById\" of type \"Query\"."`

I'm hoping that I'm just misunderstanding the RSK implementation here, because I don't see the value in having to define a corresponding sequelize query for every possible variation of a graphql query I might write. Thanks again!

**Comment by koistya** [comment]
For this to work, you would need to implement Node interface in your Bookmark GraphQL type, take a look here as an example:

* [/schema/StoryType.js#L21](https://github.com/kriasoft/nodejs-api-starter/blob/429adfa60d750f6b8be0333d8eaeef6209a50997/src/schema/StoryType.js#L21)
* [/schema/Node.js#L20](https://github.com/kriasoft/nodejs-api-starter/blob/429adfa60d750f6b8be0333d8eaeef6209a50997/src/schema/Node.js#L20)
* [/schema/index.js#L24](https://github.com/kriasoft/nodejs-api-starter/blob/429adfa60d750f6b8be0333d8eaeef6209a50997/src/schema/index.js#L24)

**Comment by keithcollins** [comment]
Got it, thanks for your time!
