### ISSUE TITLE
How can I remove hmr?

### ISSUE THREAD

**Issue by dnson** [kriasoft/react-starter-kit#1351]
Hi all,

The reason I want to do this. Because I am not sure why but the hmr doesn't work on mobile(ipad, tablet)
`Failed to load resource: The network connection was lost.` with the link ("/__webpack_hmr")

**Comment by frenzzy** [comment]
Just checked, HMR works fine in the latest Safari on Mac OS, iPad and iPhone.
If you use Node.js 8 take a look #1328

To disable hot module replacement you need to tweak [tools/start.js](https://github.com/kriasoft/react-starter-kit/blob/master/tools/start.js) file.

**Comment by ulani** [comment]
@dnson   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
