### ISSUE TITLE
Made an ESLint service using the React Starter Kit

### ISSUE THREAD

**Issue by lassegit** [kriasoft/react-starter-kit#1352]
And thought you might find it useful. It is basically running ESLint with your custom configuration and posting the result as a Github comment whenever you commit code to the repository. The project is here: https://github.com/lassegit/gitdude.com and live here: https://gitdude.com/

**Comment by ulani** [comment]
@lassegit   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
