### ISSUE TITLE
How to turn off browser-sync in --release?

### ISSUE THREAD

**Issue by tim-soft** [kriasoft/react-starter-kit#1356]
I would like to add a flag or modify `yarn start -- --release` to start RSK without browser-sync. It is a big dependency and I would like to turn it off in production.

Can anyone point me in the right direction?

I believe the only place that Browser-Sync is referenced directly is in `./tools/start.js`
```javascript
  // Launch the development server with Browsersync and HMR
  await new Promise((resolve, reject) => browserSync.create().init({
    // https://www.browsersync.io/docs/options
    server: 'src/server.js',
    middleware: [server],
    open: !process.argv.includes('--silent'),
    ...isDebug ? {} : { notify: false, ui: false },
  }, (error, bs) => (error ? reject(error) : resolve(bs))));
```

**Comment by frenzzy** [comment]
Browsersync is not used for production. To run the production build you need:
```bash
$ yarn run build -- --release    # compile app in release mode
$ node build/server.js           # run the production server
```
However if you want to remove Browsersync from development server (`yarn start`) then you need to replace lines mentioned above with something like this:
```js
server.listen(3000, () => {
  console.info('The development server is running at http://localhost:3000/');
});
```

**Comment by langpavel** [comment]
Pretty common beginner issue. May be we can add some sentinel that doing this makes no sense.

**Comment by squirmsound** [comment]
Does anyone have an example of this?

**Comment by tim-soft** [comment]
I think this was my point of confusion, I hope this clears things up

// Runs browser sync (and dev server)
yarn start -- -- release

// Doesn't run browser sync or dev server
yarn run build
node build/server.js

I'm going to go ahead and close this, thanks for the clarification!

**Comment by langpavel** [comment]
Actually:
 * `yarn start -- --release` does not make sense, because `yarn start` is for development – with Browsersync, hot reload etc..
 * `yarn run build` does not make much sense too, because build is designed for stage or production.

So you shout use:
 * `yarn start` for development
 * `yarn build -- --release` for production

**Comment by tim-soft** [comment]
Since yarn start -- --release  doesn't make sense, it probably shouldn't be listed in the getting started doc under browser sync, unless I'm misunderstanding the doc

**Comment by victorvu88** [comment]
Add more property ghostMode: false,

**Comment by ulani** [comment]
@tim-soft   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
