### ISSUE TITLE
Replace yahoo/react-intl with alibaba/react-intl-universal

### ISSUE THREAD

**Issue by cwtuan** [kriasoft/react-starter-kit#1359]
yahoo/react-intl can only be applied in view layer such as React.Component. For Vanilla JS file, there’s no way to internationalize it. For example, the following snippet is general form validator used by many React.Component in our apps.
```js
export default const rules = {
  noSpace(value) {
    if (value.includes(' ')) {
      return 'Space is not allowed.';
    }
  }
};
```
https://github.com/alibaba/react-intl-universal is simple but powerful. It doesn’t change behavior of components. And can used in JSX and normal JS file.

**Comment by langpavel** [comment]
Hmmm very interesting! Can you provide more resources, arguments whatever? If I adopt this, I should create new branch for it or can it be backward compatible?

**Comment by langpavel** [comment]
Hmmm, I'm not sure that all what `alibaba/react-intl-universal` says about `yahoo/react-intl` is true.
I have a way to get message from intl after I can decide language on server, probably I did not publish this in `react-intl` branch, but it's really possible... On the client it's really easier because client can use globals easier :-)

**Comment by cwtuan** [comment]
@langpavel 
`alibaba/react-intl-universal` has [compatible APIs](https://github.com/alibaba/react-intl-universal#compatibility-with-react-intl) with `yahoo/react-intl`. 

It resolve the problem mentioned in [How to use imperative API in a non-component script](https://github.com/yahoo/react-intl/issues/416).

**Comment by ulani** [comment]
@cwtuan   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
