### ISSUE TITLE
How dispatch action in component once?

### ISSUE THREAD

**Issue by Shadowman4205** [kriasoft/react-starter-kit#1369]
Hello, 
i want load data on component from redux store if available, if not dispatch action.
This component is common and i use it in every page. 
i tried something like this on constructor

```
 constructor(props) {
    super(props);
    if (isEmpty(props.data)){
      this.props.loadData();
    }
  }

// this.props.loadData(); -> loadData: bindActionCreators(loadData, dispatch),
```
But this props.loadData called twice once one server and once one client side when first time page, cause second time still props.data empty no time to update.

Some solution could be load this data on all routes , with this motive

> if (isEmpty(store.getState().data)) await store.dispatch(loadData());

or load it once on server.js but i already load some other data there.

Is there any suggestion how use this properly on component side?

**Comment by pfftdammitchris** [comment]
Since you want to load this data on every page you can pass the data through a higher component in the chain by using context, and use that in your target component to render only if that data is available. [Link to context explanation.](https://facebook.github.io/react/docs/context.html#how-to-use-context)

Another way is to fire an action right before your entire page gets to render. Somewhere in your higher component up the chain you imported createStore(). The first argument is the reducers to your app, and the second argument is the initial state of your whole app which you will put your pre-loaded data into. 
[Link to the createStore() api](http://redux.js.org/docs/api/createStore.html#createstorereducer-preloadedstate-enhancer). 

Correct me if I am wrong or my suggestions are crappy. I saw this in a video not too long ago by Dan Abramov but I am not sure if I explained it the right way

**Comment by langpavel** [comment]
Your component will be evaluated always twice on first render.
 - Server must create markup
 - Client will recreate React components when hydrate the DOM again
So:
 - constructor will be called on server and client 
 - `componendWillMount` will be called on server and client 
 - `componendDidMount` will be called only on client
 - `render` of course will be called on both, server and client too.

If you want reuse data, you must store it inside `store` on server, serialize them to client and then reuse them.

Apollo can do this for you, Redux can do this for you with yours extra care, you can check if store already have the data needed.
