### ISSUE TITLE
How to programmatically change route?

### ISSUE THREAD

**Issue by yeezysallonyoursofa** [kriasoft/react-starter-kit#1373]
I'm on react-router v.3 (can't update to 4 since it'll break my app). I'm trying to use react router to programmatically change the route, but I only receive:

**"app.js:5 TypeError: Cannot read property 'push' of undefined"** 

meaning that I have no access to router anywhere. With this boilerplate - is there a way to get access to router so I can programmatically change the route?

```js
class Admin extends React.Component {
  static contextTypes = {
      router: React.PropTypes.object
  };
  state = {
    loading: true,
    submitLoading: false
  }

  constructor(props,context) {
    super(props)
  }

  componentDidMount() {
    firebaseAuth().onAuthStateChanged(user => {
      if (user) {
        this.context.router.push('/')
        
      } else {
        this.setState({loading: false})
      }
    })
  }
```

**Comment by tgdn** [comment]
Try with this

```javascript
import { browserHistory } from 'react-router'

// in your code (can use pop() and other methods as well)
browserHistory.push('/')
```
Let me know

**Comment by piglovesyou** [comment]
@yeezysallonyoursofa This boilerplate mounts `universal-router` instead of `react-router`. Not sure why you ask about `react-router` here.

And one of tutorials in the proj refers to this: [Related Articles > You might not need React Router by Konstantin Tarkus](https://github.com/kriasoft/react-starter-kit/blob/master/docs/recipes/how-to-implement-routing.md#related-articles)
