### ISSUE TITLE
How do I remove bootstrap and add MDC?

### ISSUE THREAD

**Issue by redimongo** [kriasoft/react-starter-kit#1388]
I prefer material design over bootstrap, but in this example, you have not clearly documented were a beginner would add or change the overall sites CSS and core JS.

If someone can please explain where the stylesheets are or JS file that tells the site to load bootstrap. I would ideally like to use material design.

My background is PHP and coding everything from scratch but I have a project I need done by December and I thought I would try reactjs, it's proving to be more hassle then I really want.

I am feeling really lost with understanding how this demo react-starter-kit works. I worked out the menu and how to add a new page template (about, find us etc). So I guess I am on the right path when it comes to learning a whole new language.

I do have more questions however i'll post another question after I figure this one out.

**Comment by langpavel** [comment]
We are not so far. This kit is about how React can work in isomorphics way with some paths sketched. Not more, not less..

**Comment by GideonFlynn** [comment]
If you download MDL and if you let's say wanted to use the layout, you put that CSS in the layout component. Want to make a card? Put the MDL card CSS in a card component, and so on.
As Pavel says: you can write all styles yourself. If you want to incorporate a CSS framework,  you would have to piece it together in individual components.  :)

**Comment by ulani** [comment]
@redimongo   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
