### ISSUE TITLE
running `yarn run messages -- --watch` on branch feature/react-intl is not working

### ISSUE THREAD

**Issue by fortranlee** [kriasoft/react-starter-kit#1397]
https://github.com/kriasoft/react-starter-kit/blob/2d3c105b63423febc74b7a37fe9cf2b1f489fef7/tools/messages.js#L143

event name `changed`should be `change`

see https://github.com/paulmillr/chokidar#getting-started

**Comment by langpavel** [comment]
Uff I think old code works too, didn't it?

**Comment by ulani** [comment]
@fortranlee   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
