### ISSUE TITLE
Possible network speed enhancements

### ISSUE THREAD

**Issue by ethanneff** [kriasoft/react-starter-kit#1400]
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdemo.reactstarter.com%2F&tab=mobile

**Comment by langpavel** [comment]
This is starter kit, but sure, something can be done by kit, something by proxy.
@koistya Can you write a line there? :smiley: Thanks!

**Comment by ulani** [comment]
@ethanneff   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
