### ISSUE TITLE
WARNING: Accessing createClass via the main React package is deprecated

### ISSUE THREAD

**Issue by malishahi** [kriasoft/react-starter-kit#1402]
How to solve the following warning?

Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class

**Comment by tgdn** [comment]
Replace all the `createClass` with the ES2015 `class MyClass extends React.Component`

**Comment by langpavel** [comment]
It can be from outdated or not more maintained external library. In this case you should look for alternative.

**Comment by ulani** [comment]
@malishahi   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
