### ISSUE TITLE
Is it possible to implement graphQL subscriptions within this boilerplate?

### ISSUE THREAD

**Issue by k1tzu** [kriasoft/react-starter-kit#1408]
I spent enormous amount of my lifetime trying to figure out how to do that with no luck.
Can somebody tell me how to add subscriptions to this boilerplate, please?

**Comment by tgdn** [comment]
I was able to successfully implement it. I used [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws) with [graphql-subscriptions](https://github.com/apollographql/graphql-subscriptions) from Apollo to start with.

I replaced the Express GraphQL server with the one from [Apollo](https://github.com/apollographql/apollo-server), and put my schema in a schema.graphql file which is then imported on server-side.

_A little bit of effort has to be put in if you've already written quite a bit of ObjectTypes. However, there are some benefits: You have much less code to write as you are using the actual graphql syntax and not the one for nodejs. I removed a lot of JS code the day I did the change, and the resolvers are much less verbose._

For  scalability reasons I then replaced  [graphql-subscriptions](https://github.com/apollographql/graphql-subscriptions)  with [graphql-redis-subscriptions](https://github.com/davidyaha/graphql-redis-subscriptions), because I am using Redis for sessions and for caching, and it seemed logical to also use Redis as a message broker using Redis' [PubSub](https://redis.io/topics/pubsub) capabilities.

It works perfectly, client connects to websocket and subscribes to graphql changes, reconnects if connection is lost.

In order to do it I wrote a standalone socket.js which spawns an http server as shown in [subscriptions-transport-ws's README](https://github.com/apollographql/subscriptions-transport-ws). Added it to the webpack config file so that it would compile server.js, client.js and socket.js and put them in the /build folder.

The source code is shared between the three files so that I can use the same schema in server and socket. After compilation, my socket.js file can work on its own as a standalone websocket server. The server.js and client.js work the same as before.

This allows the websocket server to be on one machine whilst the server is on another. You could of course use a message broker such as RabbitMQ by using [graphql-rabbit-mq-subscriptions](https://github.com/cdmbase/graphql-rabbitmq-subscriptions) instead of Redis.

I don't have access to the source right now but I can if you want later on today.

I hope this helps.

**Comment by k1tzu** [comment]
Thank you, but the devil is in the detail as usual.

**Comment by tgdn** [comment]
I'll post it later on!

**Comment by tim-soft** [comment]
You could also do it this way 
https://github.com/kriasoft/react-starter-kit/issues/1362#issuecomment-328218418

Although HMR in dev isn't perfect, you have to handle the cases where the dev server stops, you must also stop the websocket server, don't add a listener if one already exists etc.

**Comment by k1tzu** [comment]
Yes I'm trying to implement it but it's working somehow server side via graphiql only and only if I'm using ```  subscribe: withFilter(```
with plain ``` subscribe: () => pubsub.asyncIterator...``` it's not working dunno why.
And ```resolve: ``` within subscription is not working also
and the solution you've pointed to lacks client side.
Still can't build a solid and understandable solution for the question.

**Comment by tim-soft** [comment]
GraphQL Subscriptions should only be run client-side

**Comment by k1tzu** [comment]
Yes, I said it wrong. I mean they work currently only within graphiql by some magic I don't understand ```app.use(
  '/graphiql',
  graphiqlExpress({
    endpointURL: '/graphql',
    subscriptionsEndpoint: `ws://localhost:${config.subPort}/subscriptions`,
  }),
);
```
But I can't implement it in my react component that easy.

**Comment by tim-soft** [comment]
An issue isn't the best place to post that much code, maybe I'll write something for the wiki since this has been asked about pretty frequently. 

Here's a good place for you to start
https://dev-blog.apollodata.com/tutorial-graphql-subscriptions-server-side-e51c32dc2951

You need to put your subscription query into a .graphql file, load it into your component, then do your `this.props.data.subscibeToMore()` stuff in `componentWillMount`

**Comment by k1tzu** [comment]
God, please somebody give me a working GraphQL subscriptions with this boilerplate as I created lots of components based on it and just can't move it that easy, learn different structure and logic. Why it even says "GraphQL" if it doesn't include graphQL subscriptions... 
Please tell me what to add to server.js within this boilerplate?
And what to add to components?
I'm extremely stuck for 2 weeks with this task and no tutorials are working when I get down to this boilerplate structure and modules.
Please.

**Comment by tgdn** [comment]
I'll send you a link to a repo!

**Comment by k1tzu** [comment]
Yes! Please! Thank you!

**Comment by tim-soft** [comment]
@tgdn can I also take a look? I'm interested to know how you configured webpack/HMR

**Comment by k1tzu** [comment]
![@tgdn and a link for me please](https://user-images.githubusercontent.com/8276458/31025452-63e49a2a-a54b-11e7-93fd-297ba13bdd58.gif)

**Comment by ricardomoura** [comment]
i've integrated with success the only problem is with browser-sync and HMR. everytime i make a change it gives me EADDRESS is already in use.

i've used the approach from @tim-soft in the other issue.
the only change i've done was to remove the second http.createServer cause the addGraphqlSubscriptions is already wrapping around the original server so having 2 server listening doesn't make sense for me here.

would be nice to see a complete solution for development
cheers

**Comment by k1tzu** [comment]
...still no link, no solution, nothing.
![eh](https://i.imgur.com/UcPefCB.gif)

**Comment by tgdn** [comment]
I'm extracting it from another project, hang on

**Comment by k1tzu** [comment]
Anything that will allow graphql subscriptions to work within this boilerplate will be an extremely huge relief for me and will be of a great help for lots of people that no doubt will run into the same question sooner or later.

**Comment by tgdn** [comment]
Have a look: https://github.com/tgdn/react-starter-kit-subscription

You should clone and test. You need redis running and sqlite

package.json contains a bunch of unnecessary packages. Didn't remove them sorry.

**Comment by tim-soft** [comment]
@tgdn I really like your implementation. How do you run this in prod? I suppose you'd run `build/socket.js` first, then spin up `build/server.js`?

**Comment by tgdn** [comment]
There is no order. Because both are standalone, if you start the server without the socket you won't be able to connect to the websocket and thus won't have real time updates. But if at some point you start the socket, then the client will at some point connect to it.
Similarly, if you start the socket without the server, it will start, and wait for websocket connections.

The way it works is that the socket.js file is on its own inside a Compute Engine node in Google Cloud Engine, and the the server with the client on App Engine for automatic scalability. And the Redis server is itself on a node of his

**Comment by tgdn** [comment]
A resource that has proved to be more useful than the documentation about subscriptions and websockets is the GitHunt api and client:

API: https://github.com/apollographql/GitHunt-API
React client: https://github.com/apollographql/GitHunt-React

The only issue with my config is that because it is using Redis for pubsub, if all the socket servers are down, none will be able to catch the publication from Redis as it is a fire and forget kind of mechanism unlike RabbitMQ for example. A solution would be to use a better message broker than redis which has some kind of queue

**Comment by WiktorKa** [comment]
Any ideas why standard PubSub (based on EventEmmiter) is not working while RedisPubSub is working fine? I was struggling with setting everything up and eventually decided to give it a try with Redis... and it worked! So now I'm confused - any idea what could be the reason?

@tgdn I'm using your solution and I'm wondering whether and how to run both scripts (server.js and socket.js) on production server (AWS Beanstalk)?

**Comment by tgdn** [comment]
I had the same issue. But because I was going to use Redis anyway I didn't really look deeper.

You could probably put both on EC2 on different ports.
I am not sure about Beanstalk. It seems you can, I would either make it into one server on top of express and thus you would have one server. I made two because it was simpler for me to do it that way.

https://stackoverflow.com/questions/30683648/how-to-run-socket-io-and-express-on-the-same-elastic-beanstalk-instance
https://stackoverflow.com/questions/15907302/websockets-with-socket-io-on-aws-elastic-beanstalk

**Comment by WiktorKa** [comment]
@tgdn Thank you - I made it into one server (according to this article: https://dev-blog.apollodata.com/tutorial-graphql-subscriptions-server-side-e51c32dc2951). Interesting thing is that now PubSub is working very well :) My guess is that when you have two processes (server and socket) than you have two separate instances of in-memory PubSub...
