### ISSUE TITLE
Sqlite3 dependency broken 

### ISSUE THREAD

**Issue by vikas-0** [kriasoft/react-starter-kit#1409]
`node_modules/sqlite3: Command failed.
Exit code: 126
Command: node-pre-gyp install --fallback-to-build
`

**Comment by langpavel** [comment]
`node-gyp` is prerequisite.
`npm install --global node-gyp` then try again.
Next advice, remove related code from RSK and make PR :smile:

**Comment by ulani** [comment]
@vikas-0   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
