### ISSUE TITLE
Locale request say 405 not allowed when deployed.

### ISSUE THREAD

**Issue by xywenke** [kriasoft/react-starter-kit#1428]
I am a fresher and use feature/react-intl, I configured nginx server domain 'web.test' to build directory and then run
````
yarn run deploy
````
but when I visited web.test in browser, I find the news became static data written in build/index.html and locale can not change. the error as blow.
![image](https://user-images.githubusercontent.com/9194669/31318708-fd7202d8-ac88-11e7-8202-786c8ba08ca0.png)
How to use deploy scripts? Would someone help me? thanks a lot.

**Comment by ulani** [comment]
@xywenke   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
