### ISSUE TITLE
Making React Starter Kit work with Electron

### ISSUE THREAD

**Issue by holgersindbaek** [kriasoft/react-starter-kit#1433]
I've build a React app using React Starter Kit and now I want to create a desktop version of that app as well.

I'm not sure what the right approach to that would be. Has anyone used Electron with their RSK app? Can you share your main.js file? Which file would you make Electron load?

**Update 1:**
I found out that I can render the site as a static html site using `npm run build -- --static --release` and I'm not playing with loading the index.html that is generated.

It doesn't seem like the optimal way to do this though. Have anyone done this before? Can you give an advice?

**Comment by ulani** [comment]
@holgersindbaek   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
