### ISSUE TITLE
Cannot read property 'allowMutablePropsOnTags' of undefined

### ISSUE THREAD

**Issue by clivedsouza1010** [kriasoft/react-starter-kit#1436]
Cannot read property 'allowMutablePropsOnTags' of undefined (While processing: "/Documents/projects/profile-ui-app/node_modules/babel-plugin-transform-react-constant-elements/lib/index.js")
    at transformReactConstantElement (/Documents/projects/profile-ui-app/node_modules/babel-plugin-transform-react-constant-elements/lib/index.js:10:40)

**Comment by tim-soft** [comment]
Delete your `node_modules` folder and make the changes in this commit: https://github.com/kriasoft/react-starter-kit/commit/055e66aeac7e40f25fffbff70ad6c2e76620cca4

Basically just remove the carrot's `^` from the babel packages in package.json, then do a `yarn install`

**Comment by ulani** [comment]
@clivedsouza1010   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
