### ISSUE TITLE
Document how to start on a custom port

### ISSUE THREAD

**Issue by hakunin** [kriasoft/react-starter-kit#1438]
Hi, I can't seem to be able to change the default ports.

I changed the ports here in `src/config.js`:

```
module.exports = {
  // Node.js app
  port: 4000,

  // API Gateway
  api: {
    // API URL to be used in the client-side code
    clientUrl: process.env.API_CLIENT_URL || '',
    // API URL to be used in the server-side code
    serverUrl:
      process.env.API_SERVER_URL ||
      `http://localhost:${4000}`,
  },
```

I also used `dotenv` to change the `process.env.PORT` to 4000 but the app uses`3000` and `3002` no matter what.

So please document how to do this and simply respect whats in the `process.env.PORT`.

**Comment by frenzzy** [comment]
Hey @hakunin,
`process.env.PORT` is used for a production server (`yarn run build && node build/server.js`):
https://github.com/kriasoft/react-starter-kit/blob/055e66aeac7e40f25fffbff70ad6c2e76620cca4/src/config.js#L20

In development mode (`yarn start`) Browsersync automatically chooses first free port since `3000`, but you can [set port manually](https://www.browsersync.io/docs/options#option-port) (ie `port: process.env.PORT`):
https://github.com/kriasoft/react-starter-kit/blob/055e66aeac7e40f25fffbff70ad6c2e76620cca4/tools/start.js#L225

**Comment by venkatch668** [comment]
yarn start --port 9988

**Comment by ulani** [comment]
@hakunin   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
