### ISSUE TITLE
No Docs: Adding Facebook SDK

### ISSUE THREAD

**Issue by goldylucks** [kriasoft/react-starter-kit#1440]
how do we add FB share button, page plugin, and like button?

Usually I add following snippet to the HTML right after the `<body>`, but `document` is not defined in `components/Html.js`

```js
  <div>
    <div id="fb-root" />
    {((d, s, id) => {
      const fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      const js = d.createElement(s);
      js.id = id;
      js.src = `//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.10&appId=${FB_APP_ID}`;
      fjs.parentNode.insertBefore(js, fjs);
    })(document, 'script', 'facebook-jssdk')}
  </div>
```

**Comment by fchienvuhoang** [comment]
same issue, FB is not defined

**Comment by fchienvuhoang** [comment]
@goldylucks in this case. May be you should copy FB script to a file in /public folder and link it in html file by script tag...

**Comment by goldylucks** [comment]
@fchienvuhoang yea then will have to do an additional http request just for that :(

**Comment by ulani** [comment]
@goldylucks   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
