### ISSUE TITLE
Any thoughts why not updating the  "app.lang".

### ISSUE THREAD

**Issue by Ranushka** [kriasoft/react-starter-kit#1442]
hi,
This Question is relate to [react-intl](https://github.com/kriasoft/react-starter-kit/tree/feature/react-intl.) branch.
When changing the  language by language switcher, any thoughts why not updating the
[`<html className="no-js" lang={app.lang}>`](https://github.com/kriasoft/react-starter-kit/blob/feature/react-intl/src/components/Html.js#L41)
This might relate to this [issue](https://github.com/kriasoft/react-starter-kit/issues/1163).

The reason i'm looking for. is to use as rtl eg: arabic. please let me know if the question is not clear.

Thanks in advance.

**Comment by Larinel** [comment]
Shortly: there is no listener for changes of app.lang
When youre rendering html, you can save ref of html object, and then change property in language switcher.

**Comment by ulani** [comment]
@Ranushka   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
