### ISSUE TITLE
Use `node -r babel-register` instead of `babel-node`?

### ISSUE THREAD

**Issue by cuyu** [kriasoft/react-starter-kit#1446]
Why not use `node -r babel-register` instead of `babel-node` in npm scripts (if so, the `.babelrc.js` needs to add `babel-polyfill`)?

At least, Webstorm does not support debugging using `babel-node` now (see [How to make Webstorm 2016.2 debug work with ES6 and babel](https://intellij-support.jetbrains.com/hc/en-us/community/posts/203373470-How-to-make-Webstorm-2016-2-debug-work-with-ES6-and-babel)).

**Comment by frenzzy** [comment]
I think maybe npm scripts must use native node.js features only, but it will require node v8 with async/await support in at least for development. What do you think is better?

**Comment by cuyu** [comment]
@frenzzy Is that what `babel-register`'s job? And `node -r babel-register` seems also works on node v6. So I didn't get the point which part is requiring async/await here?

**Comment by xamgore** [comment]
`node -r babel-register` doesn't work if `@babel/preset-typescript` is used.

**Comment by ulani** [comment]
@cuyu   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
