### ISSUE TITLE
Is it safe to bundle an project while it's running?

### ISSUE THREAD

**Issue by moshest** [kriasoft/react-starter-kit#1447]
Is it safe to bundle and deploy the project via `npm run deploy` while `npm start` is running?

**Comment by frenzzy** [comment]
No, I do not recommend to do so.
If you really want this feature you can change destination folder in start script.

**Comment by ulani** [comment]
@moshest   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
