### ISSUE TITLE
Toggle to disable isomorphic rendering

### ISSUE THREAD

**Issue by coryhouse** [kriasoft/react-starter-kit#145]
Would be handy if there was a simple toggle to disable isomorphic rendering. Perhaps one exists and I just haven't found it?

**Comment by josherich** [comment]
a quick way would be remove the server-side body rendering `data.body = ReactDOM.renderToString(component);` in server.js

**Comment by langpavel** [comment]
OMG Why? Select another crap, like PHP :-D For debugging server side you can use `curl` or `wget` or just disable JavaScript in your user agent :-)

**Comment by bjackson** [comment]
@josherich How would I go about doing that?

**Comment by bingo-lumity** [comment]
For what it's worth, I was looking into this because my team needs to know if we need to spin up a bunch of Node servers from the start, or can we get away with client-side rendering for now and add Node servers later. Luckily it seems `yarn run deploy` (which is documented in `tools/README.md`) seems to do much of the work we need.
