### ISSUE TITLE
Not working from safari 8.3

### ISSUE THREAD

**Issue by FMakareev** [kriasoft/react-starter-kit#1453]
Hello. There is a problem in Safari 8.3 on ipad, components are not rendered. Instead of a website, a white page. The browser logs is empty. The node.js log is empty.

**Comment by ulani** [comment]
@FMakareev   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
