### ISSUE TITLE
Facebook Login Strategy

### ISSUE THREAD

**Issue by cbravo** [kriasoft/react-starter-kit#1454]
After examining the code for the facebook authentication strategy I believe I have noticed an error. 

In /passport.js line 55 there is a call to User.create which passes in an existing user ID from the request object. Correct me If i am wrong but wont this create a duplicate key error?

If my understanding is correct this should be an upsert or something along those lines correct?

**Comment by ulani** [comment]
@cbravo   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
