### ISSUE TITLE
Importing styles within a lerna project doesn't work properly.

### ISSUE THREAD

**Issue by bluematter** [kriasoft/react-starter-kit#1457]
I have a separate project where I am importing react components. All dependencies are interlinked with lerna. Everything is setup properly with webpack. I did some inspecting and it seems to be an issue with `insertCss` in the `context` and `data.styles` from server.js.

Seems like it's not working with isomorphic-style-loader.

I can log the style sheet from the other package. It just doesn't have the generated styles with the ids.

    // Global (context) variables that can be easily accessed from any React component
    // https://facebook.github.io/react/docs/context.html
    const context = {
      // Enables critical path CSS rendering
      // https://github.com/kriasoft/isomorphic-style-loader
      insertCss: (...styles) => {
        // eslint-disable-next-line no-underscore-dangle
        styles.forEach(style => css.add(style._getCss()));
      },
      // Universal HTTP client
      fetch: createFetch(fetch, {
        baseUrl: config.api.serverUrl,
        cookie: req.headers.cookie,
      }),
    };

The second log shows the style sheet from the imported package.

<img width="744" alt="screen shot 2017-11-07 at 12 29 58 am" src="https://user-images.githubusercontent.com/1669104/32483934-e759df3a-c352-11e7-8375-97f2b6e610ef.png">

#

**Comment by ulani** [comment]
@bluematter   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
