### ISSUE TITLE
"react-error-overlay": "^1.0.9" in feature/redux

### ISSUE THREAD

**Issue by pdunc** [kriasoft/react-starter-kit#1463]
Hi folks,

I was working on a checkout of master and tried to merge in the feature/redux branch.  `yarn start` then errored.

## Steps Taken:

- Clean `node_modules` directory
- `npm -i`
- `yarn start`
- Did not fix the error

The error is missing function definitions for `reportBuildError`, `dismissBuildError`, `startReportingRuntimeErrors` and `stopReportingRuntimeErrors`.

All of these came from `tools\lib\webpackHotDevClient.js` which has the following import:

``` javascript
import { 
  reportBuildError,
  dismissBuildError,
  startReportingRuntimeErrors,
  stopReportingRuntimeErrors,
} from 'react-error-overlay';
```
## Fix:

Change the `react-error-overlay` version from `^1.0.0` to `^2.0.0` in `package.json`

Cheers,
Peter

**Comment by pdunc** [comment]
Just checked master and it is sitting at `"react-error-overlay": "^3.0.0"` now

**Comment by ulani** [comment]
@pdunc   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
