### ISSUE TITLE
How to use react redux router

### ISSUE THREAD

**Issue by sanjitbauliibm** [kriasoft/react-starter-kit#1468]
I am having difficulties while using react-router-redux in reducer

`const mapStateToProps = (state, ownProps) =>{
    return {
        query:state.router.location.search
    }
}`
TypeError: Cannot read property 'search' of null

i have <ConnectedRouter history={history}> in client.js
but SSR failing because of state.router.location undefined.

**Comment by ulani** [comment]
@sanjitbauliibm   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
