### ISSUE TITLE
Vendor.js and Client.js should be one file in production

### ISSUE THREAD

**Issue by buildbreakdo** [kriasoft/react-starter-kit#1470]
Client.js is worthless without Vendor.js and Vendor.js is worthless without Client.js. Client.js requires Vendor.js to be loaded to work.

So why make two HTTP requests? Think these files would also be smaller combined than separate (given how gzip compresses duplicates). Believe we should combine these files into one. Any rationale for not doing so in production?

**Comment by frenzzy** [comment]
Agreed! PR is welcome :)

**Comment by tim-soft** [comment]
That's a really great idea!

**Comment by mikehdt** [comment]
Vendor may be less likely to change often than, say, client. YMMV, but you could probably put a longer cache life on your vendor bundle. This wouldn't help first hits, but could help second visits. Depends what your priorities are.

That's often the rationale behind such a decision, as far as I've experienced :)

**Comment by ulani** [comment]
@buildbreakdo   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
