### ISSUE TITLE
No source code besides tools and node_modules revealed in debug mode

### ISSUE THREAD

**Issue by eric7578** [kriasoft/react-starter-kit#1472]
Dear team,

After I start with the debugging command `babel-node tools/run start --inspect`
And I open the link that direct to `chrome-devtools://devtools/remote/serve_file...`
It did show some source code in the folder of `node_modules` and `tools`, however, like the provided image, there are no other code that in folder of `src`.

![image](https://user-images.githubusercontent.com/4832545/33708824-7d2418ba-db76-11e7-8609-730397338d2d.png)

**Comment by ulani** [comment]
@eric7578   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
