### ISSUE TITLE
Another nodejs external server to use

### ISSUE THREAD

**Issue by malishahi** [kriasoft/react-starter-kit#1474]
I have implemented an api server with a separate nodejs server apart from dashboard.
How can I use this nodejs external server in react components?
thanks

**Comment by ImanMh** [comment]
@malishahi How do you want to use that external node server? if it's your API you can call it via ajax and get your data. Could you make your question a little bit more clear?

**Comment by ulani** [comment]
@malishahi   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
