### ISSUE TITLE
how to define env variables when deploy using kubernates container in bluemix?

### ISSUE THREAD

**Issue by sanjitbauli** [kriasoft/react-starter-kit#1477]
it is not taking any defined variables in deployment job

**Comment by ulani** [comment]
@sanjitbauli   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
