### ISSUE TITLE
Mongo Feature request

### ISSUE THREAD

**Issue by TeodorKolev** [kriasoft/react-starter-kit#1483]
Can you please make branch with mongodb implementation

**Comment by ulani** [comment]
@TeodorKolev   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
