### ISSUE TITLE
call history.goback ,dont trigger the re-render function

### ISSUE THREAD

**Issue by vince-fly** [kriasoft/react-starter-kit#1484]
i dont want to trigger the page re-render function, after calling history.goback.

some as ,the route support "cache",when cached,no re-render.

who has the better practice?

poor in english

**Comment by frenzzy** [comment]
Cache your routes data and goBack will work immediately. For example solutions like Relay do it automatically under the hood or you can use simple check like this:
```js
async function action({ store }) {
  if (!store.data) {
    store.data = await fetch();
  }
  return { component: <Page data={data} /> }
}
```

**Comment by ulani** [comment]
@vince-fly   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
