### ISSUE TITLE
Set status on not-found page

### ISSUE THREAD

**Issue by mmarkelov** [kriasoft/react-starter-kit#1489]
Good evening! I just try to set 404 status on page when catch error with fetch on server. So I tried:
```javascript
        try {
		const Res = await fetch(Url);
		Data = await Res.json();
	} catch (e) {
		return {
			status: 404,
			title: 'Page not found',
			component: <h1>Not found!!</h1>
		}
	}
```
But I got <h1>Not found!!</h1> on page, but status is 200. What is wrong with it? I console it in routes/index.js and I don't have status in it

**Comment by frenzzy** [comment]
It should work, here is the place where status is applied:
https://github.com/kriasoft/react-starter-kit/blob/d63dcf8efb06da3fca65346a80aeeccf30443087/src/server.js#L159
and default not found page route:
https://github.com/kriasoft/react-starter-kit/blob/d63dcf8efb06da3fca65346a80aeeccf30443087/src/routes/not-found/index.js#L16-L27

**Comment by mmarkelov** [comment]
@frenzzy yeah. That is all right, thanks! And for 301 redirect can I do something like this?
```javascript
{
  status: 301,
  redirect: '/',
}
```

**Comment by frenzzy** [comment]
Yes, exactly! Or you can skip status if you need 302 because it is default for redirects:
https://github.com/kriasoft/react-starter-kit/blob/d63dcf8efb06da3fca65346a80aeeccf30443087/src/server.js#L140
Example:
https://github.com/kriasoft/react-starter-kit/blob/d63dcf8efb06da3fca65346a80aeeccf30443087/src/routes/admin/index.js#L18-L20
