### ISSUE TITLE
How to get entire app in one .js file to include in a non-node server deployment

### ISSUE THREAD

**Issue by justjacksonn** [kriasoft/react-starter-kit#149]
Trying to figure out how I can get the entire app in a single .js file that I can then load in my non-node deployment. I am deploying in a Jetty Java container with a WAR file. I want to have my index.jsp (or index.html) in that WAR file load the entire app. I recall doing this before in my first attempt at ReactJS, and in my web app I have an API that I need my react app to make calls to for data to display. Is there an option to build the bundle.js that I can then just include in a separate page? If so, what else would my external page need to include (js, css, etc) in order to display the react app?

**Comment by koistya** [comment]
If you bundle your assets with webpack, the output bundle.js can contain js, css and images.. reffer to [webpack documentation](http://webpack.github.io/docs/), you wan want to look at [url-loader](https://github.com/webpack/url-loader), [file-loader](https://github.com/webpack/file-loader) and similar plugins for webpack.

**Comment by jhabdas** [comment]
@justjacksonn This seed is isomorphic (see also [hijax](http://domscripting.com/blog/display/41/)) using Node.js and Express. As it stands it allows users to disable JavaScript and continue using the app, while still benefiting from the use of Ajax and Virtual DOM while JS is enabled.

What you might want to look at running the app inside a Docker container using `forever` or [`PM2`](http://devo.ps/blog/goodbye-node-forever-hello-pm2/), and then configuring Jetty to direct traffic to the server running within the container and use something like ANT to manage the Docker containers if you're in an existing environment built around Java (otherwise look at [Ansible](http://www.ansible.com/home)). That's probably what I'd do anyways.

**Comment by justjacksonn** [comment]
Actually.. to my surprise, the bundle.js does contain everything and my app works when deployed as a .war file. I just run the npm run build process, then the build process that pulls in index.html and bundle.js, war it up, and deploy it and it all works nicely. Thanks. Will close.

**Comment by jhabdas** [comment]
Very cool!

**Comment by crj92** [comment]
@justjacksonn in your reply "Actually.. to my surprise, the bundle.js does contain everything and my app works when deployed as a .war file. I just run the npm run build process, then the build process that pulls in index.html and bundle.js, war it up, and deploy it and it all works nicely. Thanks. Will close.", how did you achieve " index.html and bundle.js, war it up". Thank You

**Comment by xgqfrms-gildata** [comment]
how to deploy a react app on apache web server ?
