### ISSUE TITLE
How to deploy the app in a sub directory served by nginx proxy?

### ISSUE THREAD

**Issue by sanjitbauliibm** [kriasoft/react-starter-kit#1493]

**Comment by frenzzy** [comment]
You need to copy the content of the `build` into your sub directory, you can do it manually or use any copy files scripts aka [`fs.copy`](https://github.com/jprichardson/node-fs-extra/blob/master/docs/copy.md).

If your destination folder under the git, you can use [deploy](https://github.com/kriasoft/react-starter-kit/blob/master/tools/deploy.js) script with small modifications.

**Comment by ulani** [comment]
@sanjitbauliibm   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
