### ISSUE TITLE
Upgrade react-starter-kit

### ISSUE THREAD

**Issue by randichilyon** [kriasoft/react-starter-kit#1504]
How can I upgrade the react-starter-kit to the newest version?

**Comment by frenzzy** [comment]
It described in [getting started guide](https://github.com/kriasoft/react-starter-kit/blob/master/docs/getting-started.md#how-to-update):
```sh
cd path/to/your/fork
git remote add react-starter-kit https://github.com/kriasoft/react-starter-kit.git
git checkout master
git fetch react-starter-kit
git merge react-starter-kit/master
yarn install
```

**Comment by ensemblebd** [comment]
--allow-unrelated-histories

**Comment by ulani** [comment]
@randichilyon   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
