### ISSUE TITLE
support output to independence CSS file under production build

### ISSUE THREAD

**Issue by lookis** [kriasoft/react-starter-kit#1505]
I am moving static file into another domain in order to use CDN service, when CSS in included in Html dom, the image in CSS and css file are not serve under CDN.

I think this feature is a common scene and better to support in react-starter-kit.

**Comment by frenzzy** [comment]
Small images inlined into `css`, styles included into `js` bundle, js bundle are served.
Only critical path css is inlined into html page, it's totally fine to be there.

**Comment by lookis** [comment]
What is critical path and how to avoid use it too much? 
Is isomorphic-style-loader/lib/withStyles means critical path? I think isomorphic-style-loader is doing more than "critical path", such as create independence css namespace.

**Comment by tim-soft** [comment]
You can use extract text plugin to output certain styles to an external spreadsheet, you'd configure that in the webpack config

**Comment by ulani** [comment]
@lookis   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
