### ISSUE TITLE
About building echarts.

### ISSUE THREAD

**Issue by thb2338** [kriasoft/react-starter-kit#1506]
Now this version of the react-starter-kit, does anyone know how to set up baidu's echarts?I met a problem when I build, is in the interface for the first time will not make a mistake, however, interface refresh, will be submitted to an action. The default is not a function, I also use this framework before, I in previous project structures, won't appear this problem, the caused by this version of the webpack version?

**Comment by kaiwen1811** [comment]
the same with u, have u fix this problem?

**Comment by thb2338** [comment]
@kaiwen1811 I tried a lot of methods, and I can't do it. I can use the previous version, no problem, and then I have a problem after updating this version. I don't know whether the version of webpack is a problem.

**Comment by kaiwen1811** [comment]
@thb2338 Thank you for your reply!

**Comment by ulani** [comment]
@thb2338   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
