### ISSUE TITLE
Home route has obsolete code?

### ISSUE THREAD

**Issue by reactor81** [kriasoft/react-starter-kit#1509]
In the Apollo branch:

1 - In routes/home/index.js we have '<Home news={data.reactjsGetAllNews} />'

Here, the news prop is not used at all in the <Home> component, and indeed data.reactjsGetAllNews does not even exist (should be data.data I believe). So, is this prop invalid?

2 - And then, why do we have the graphql query in the route index.js file AND in the <Home> component anyway? Is that pattern desirable / is it required? Or is this just a code cleanup issue where having it in the index.js is an older style that was not deleted? Should I be okay just putting the graphql queries in the actual component, and not in these index.js route files (as it seems like dead code in <Home> atm) 

Thanks!

**Comment by tim-soft** [comment]
1. It's a named query, take a look at the graphql file, which is why the data comes inside that appropriately named object.

2. I believe the point is to force fetch the data server side when you first visit the route. This particular query is getting a lot of html content as a string that needs to be rendered at some point, so why not do it SSR style? So initial render with html content is done via SSR, then Apollo hoc in component for client side updates.

It's for the SSR perf

**Comment by reactor81** [comment]
@tim-soft  Thanks for your reply. I think I still see two issues with that code though:

1) I think we need data.data.reactjsGetAllNews (see the console output in screenshot below)

2) the <Home> components expects a prop reactjsGetAllNews, but the index.js is passing it in as news which is not referenced at all in <Home> so maybe the index.js needs to be:

`<Home reactjsGetAllNews={data.data.reactjsGetAllNews} />`

instead of:

`<Home news={data.reactjsGetAllNews} />`

What are your thoughts? I only started looking at RSK a few hours ago so I could be wrong. But it seems maybe these changes are needed?

![screen shot 2018-01-18 at 4 56 57 pm](https://user-images.githubusercontent.com/14055426/35086651-a0429874-fc70-11e7-8480-9096b4df37d0.png)

**Comment by ulani** [comment]
@reactor81   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
