### ISSUE TITLE
Client.js inefficient because of currentLocation.key?

### ISSUE THREAD

**Issue by reactor81** [kriasoft/react-starter-kit#1510]
In the code below, we check that currentLocation,key !== location.key , but can this not happen before the router.resolve ? Does router.resolve somehow change currentLocation to make that check worthwhile? 

Indeed, currentLocation = location , and then checking currentLocation.key !== location.key . ... Is this not dead code? (ie does currentLocation or location get changed before the check? otherwise, we know they are equivalent?)

 ```
  currentLocation = location;

  const isInitialRender = !action;
  try {
    // Traverses the list of routes in the order they are defined until
    // it finds the first route that matches provided URL path string
    // and whose action method returns anything other than `undefined`.
    const route = await router.resolve({
      ...context,
      pathname: location.pathname,
      query: queryString.parse(location.search),
    });

    // Prevent multiple page renders during the routing process
    if (currentLocation.key !== location.key) {
      return;
    }
```

**Comment by frenzzy** [comment]
add a delay (api request) to route A, then click on A then B, you expect that B will be shown, but B will be replaced by A after a delay - you don't expect such behavior because you are viewing B.

**Comment by ulani** [comment]
@reactor81   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
