### ISSUE TITLE
SSL / HTTPS in recent config

### ISSUE THREAD

**Issue by reactor81** [kriasoft/react-starter-kit#1521]
Hi, 

I have seen the two or three posts regarding setting up ReactStarterKit (RSK) with https/ssl.. But these are 2 or 3 years old now and the configs seem to have changed a lot. I also saw someone reply about doing SSL and the ELB level, however my application uses websockets and so this is non-trivial. I prefer to handle ssl in the application itself. 

Has anyone successfully managed to get SSL/HTTPS working in RSK? How have you managed to do this? I'm not sure on the required steps really..

**Comment by langpavel** [comment]
Even I'm issue killer, this is something that needs more talk and we should care about.

**Comment by ulani** [comment]
@reactor81   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
