### ISSUE TITLE
tools/start.js Question

### ISSUE THREAD

**Issue by Kacoze** [kriasoft/react-starter-kit#1533]
Hello,
I'm trying to understand some things in this project. Here: [tools/start.js#L153](https://github.com/kriasoft/react-starter-kit/blob/c3f0c85e387a2df8579701ab871842386325ab97/tools/start.js#L153)

Could somebody explain to me how does it work? In line 150 there is app variable created, but magically in line 153 there should be something in it with the .handle method. How does this happen? And ofc. what does this do? :)
I will really appreciate explaining it :)

**Comment by langpavel** [comment]
See [tools/start.js#L217](https://github.com/kriasoft/react-starter-kit/blob/c3f0c85e387a2df8579701ab871842386325ab97/tools/start.js#L217).
Because you look inside event callback, `app` will be populated when it can happen. The `app` is then used from outside — this is called *closure*. Basic event programing :-)
I'm going to close this, but please don't give it up and learn javascript, it will make you better programmer :-)
