### ISSUE TITLE
where are unit tests?

### ISSUE THREAD

**Issue by hyzhak** [kriasoft/react-starter-kit#154]
I'm trying to find any example of tests that follows [react-style-guide](https://github.com/kriasoft/react-starter-kit/blob/master/docs/react-style-guide.md#file-structure-per-component-example) in this project, but I don't see any of them here. Where did they go?
##

**Comment by AndrewRevinsky** [comment]
:+1:

**Comment by AndrewRevinsky** [comment]
@koistya, really, the work on the Kit seems to have slowed down and some time ago all the tests were removed. The whole impression, there is not a suitable testing framework to work well with React, esp. with modern syntax and under Node. Do we need to worry about it?

**Comment by ulani** [comment]
@hyzhak   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
