### ISSUE TITLE
Is it possible to implement React Loadable in RSK?

### ISSUE THREAD

**Issue by firzx77** [kriasoft/react-starter-kit#1545]
Hello,

I'm new in RSK, I've already search [React Loadable](https://github.com/jamiebuilds/react-loadable) in RSK repository, but no one start discussing in using React Loadable. I'm just trying to implement Component-based splitting in RSK. Is it possible to implement React Loadable in RSK? Thank You :)

**Comment by langpavel** [comment]
You should split by pages, like we do in router.
I don't think its shit (as React Loadable say) :-)
You can also split large components

Most effective React app can do this:
* render on server side:
* add relevant scripts and other resources to `<head>` as `<link rel="preload" ... />`,
  do not add scripts itself, they are needed after DOM is rendered.
* write rendered app
* serialize app state
* load scripts, mount the App, they should be already prefetched…
* register service worker, preload all frequently used scripts, now your app can run even offline :slightly_smiling_face:

**Comment by langpavel** [comment]
And, of course, I think you don't need React Loadable, just use state for rerender when component is loaded.

BTW there is React suspense technique which I believe can be used even for loading components, I don't know how will this work with SSR but it will be solved one nice day :slightly_smiling_face:

**Comment by ulani** [comment]
@firzx77   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
