### ISSUE TITLE
[feature/react-intl] The "path" argument must be of type string

### ISSUE THREAD

**Issue by WiktorKa** [kriasoft/react-starter-kit#1546]
Running `yarn messages` on Intl branch gives following error: 

`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string`

@kayluhb created an issue here: https://github.com/yahoo/babel-plugin-react-intl/issues/135

**Comment by WiktorKa** [comment]
OK, I think I have a solution (added `filename: fileName,` line):
file: `tools/messages.js`: 
```javascript
const processFile = async fileName => {
    try {
      const code = await readFile(fileName);
      const posixName = posixPath(fileName);
      const result = transform(code, {
        filename: fileName,
        presets: babelrc.presets,
        plugins: ['react-intl'],
      }).metadata['react-intl'];
      if (result.messages && result.messages.length) {
        fileToMessages[posixName] = result.messages.sort(compareMessages);
      } else {
        delete fileToMessages[posixName];
      }
    } catch (err) {
      console.error(`extractMessages: In ${fileName}:\n`, err.codeFrame || err);
    }
  };
```

**Comment by langpavel** [comment]
What should I do for this to be fixed? Code above?

**Comment by WiktorKa** [comment]
@langpavel Adding the line `filename: fileName` as option for `transform()` method made it work in my case.

**Comment by ulani** [comment]
@WiktorKa   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
