### ISSUE TITLE
[Opinion] Is SSR still necessary?

### ISSUE THREAD

**Issue by WiktorKa** [kriasoft/react-starter-kit#1558]
Google announced that it is using Chrome 41 engine to render sites -
 https://developers.google.com/search/docs/guides/rendering . I wonder if this means that there is no longer need for server side rendering (or soon wont be)? What do you think?

**Comment by frenzzy** [comment]
Take a look this video: [Server-side Rendering with JavaScript Frameworks](https://www.youtube.com/watch?v=GH3kJwQ7mxM)

**Comment by koistya** [comment]
If you're building a public site, at a very least you need to do partial SSR - make sure that you pre-render `<head>` section on the server with all the meta tags (title, description, Open Graph etc.). Also, in order to improve the initial page load time, you would want to embed the list of application chunks used on the page, serialized data that can be dehydrated on the client (avoiding fetching data via Ajax on the initial page load), and ideally pre-render at least the layout of the page (background, header/toolbar), this way users will see something while application chunks are being loaded instead of a blank screen or a loader icon. Here is an example: https://firebase.reactstarter.com

Without full SSR you will also need to be extra careful not to introduce some fancy E2017 syntax or language feature that Googlebot cannot understand. Otherwise, it will nullify all or some of your indexed pages degrading SEO. Surprisingly, Googlebot doesn't use the latest version of Chrome for rendering.

On the other hand, if you're building an admin panel, CRM dashboard or something like that, you don't need SSR.

**Comment by WiktorKa** [comment]
I'm building a public site with full SSR based on this project, but recently I got into conversation with my friend who is also working on a public site with ReactJS and he claims that SSR is not really necessary anymore - so that's why I was interested in your opinion on that matter.  Thanks for all the resources - they are helpful!

**Comment by langpavel** [comment]
SSR is still good for some use cases:
- Google is not the only search engine
- Prerendered HTML can be displayed immediately, it's usually much smaller and content can be displayed much faster to the client
