### ISSUE TITLE
This kit used to not be node-dependent

### ISSUE THREAD

**Issue by beeb** [kriasoft/react-starter-kit#156]
Hey, just passing by after a long time, and I noticed the project has changed quite a bit! I used to use this when it was still generating a site structure that was not server-dependent (i.e. no node.js server was necessary) and that's what I loved about this project. Most of the clients whom I work for don't want a node hosting and still force me to use standard apache servers.

I would love to be able to bundle my app into plain html/js like the ol'days. Is there a way using this starter kit? Or is there another React/Flux implementation out there that would still do this?

Node.js is fancy and exciting but unfortunately, not compatible with my day-to-day needs.
Thanks !
##

**Comment by pewh** [comment]
+1 I have same scenario with you

**Comment by koistya** [comment]
I know some folks develop back-end (mostly RESTful API) with a totally different stack, and use this starter kit only for the front-end and server-side rendering which is very easy to do with Node.js/Express. Maybe that's what you really need? Or, you want to do server-side rendering using another back-end technology as well?

**Comment by beeb** [comment]
Thanks for the reply! Indeed, I would like to use a restful API as back-end and use React just for the front-end, static boilerplate looks promising. Of course though, this would not be isomorphic anymore.

**Comment by ulani** [comment]
@beeb   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
