### ISSUE TITLE
[feature/redux] Redux DevTools not working (only @@INIT action)

### ISSUE THREAD

**Issue by WiktorKa** [kriasoft/react-starter-kit#1566]
It seems that Redux DevTools stopped working somewhere in the process. I tried to follow troubleshooting advise and added [redux-immutable-state-invariant](https://github.com/leoasis/redux-immutable-state-invariant) but with no success (meaning no error occurs). Any ideas?

**Comment by ulani** [comment]
@WiktorKa   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
