### ISSUE TITLE
How to implement bootstrap?

### ISSUE THREAD

**Issue by mychaelgo** [kriasoft/react-starter-kit#157]
##

**Comment by korczis** [comment]
I am afraid that @koistya is not big fan of bootstrap, see https://github.com/kriasoft/react-starter-kit/issues/93

**Comment by mychaelgo** [comment]
@korczis Ok

**Comment by ulani** [comment]
@mychaelgo   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
