### ISSUE TITLE
[feature/react-intl] problem on IE10 (polyfill)

### ISSUE THREAD

**Issue by dreisel** [kriasoft/react-starter-kit#1580]
when running the app on IE10 (or any browser that need the intl polyfill)
the client loader will eventually load the polyfill but the main client file that uses the intl is loaded first.
this causes an error and the entire app won't load.

I fixed this issue at my fork by importing the client file dynamically when the polifilled is done (if needed).

I'll open a PR soon

**Comment by langpavel** [comment]
I have this in clientLoader.js but it's possible that it was lost

**Comment by ulani** [comment]
@dreisel   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
