### ISSUE TITLE
How do you use fetch in your sagas?

### ISSUE THREAD

**Issue by ImanMh** [kriasoft/react-starter-kit#1584]
This is related to idea of putting fetch in context. With this decision made in react-starter-kit, I should get fetch from context of a component and pass it to my action creator, then take it there and dispatch it so my saga can get it. I wish I could pass data to my action creators rather than functions. This doesn't feel good. I wish I could simply import fetch in my sagas instead of passing it around. Here is an example:

```
// server.js
import { configFetch } from 'starter-kit-fetch';

configFetch.setHeaders('some-header', 'some-value');
```

```
// client.js
import { configFetch } from 'starter-kit-fetch';

configFetch.setHeaders('some-header', 'some-value');
```

```
// some saga

import { fetch } from 'starter-kit-fetch';

// use configured fetch here
```

What do you think about this implementation?

**Comment by ulani** [comment]
@ImanMh  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
