### ISSUE TITLE
Storing images outside project folder

### ISSUE THREAD

**Issue by lvian** [kriasoft/react-starter-kit#1586]
Hello guys,

We are using RSK for our project and so far it has been working well.

Recently we decided to make a change about how we stored user uploaded images, changing from a folder inside the project to a folder outside it.

ex:
/home/company/our-project/public/user-images/
to
/home/company/user-images

I used the same sintax already present inside server.js and registered the new folder as : 

```app.use(express.static(path.resolve(NEW_IMAGES_PATH , ''), {immutable: true, maxAge: '1y'}));```

It worked well when the first image for each field was uploaded, but when they were replaced by new ones, the frontend kept displaying the old ones, even with them not being available since they were overwritten on the server.

I kinda managed to solve it by removing the maxAge and immutable parameters, but even so, the image only updates after a page refresh, while before, the component re-render was enough to get the new image.

So, what am I missing? Why were the images stored in the project folder updated without the need to change the express code or refresh the page?

**Comment by tim-soft** [comment]
Why don't you setup a special folder with your webserver so that you can access those assets via `fqdn/special-folder/image.jpg`

**Comment by ulani** [comment]
@lvian  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
