### ISSUE TITLE
Packaged static pages flashed to 404 pages per second

### ISSUE THREAD

**Issue by top319VIP** [kriasoft/react-starter-kit#1598]
This problem occurs when I type a static file using the "yran run build-static-release" command

**Comment by kolf** [comment]
me too

**Comment by ulani** [comment]
@top319VIP   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
