### ISSUE TITLE
any suggestion for config "baseUrl"

### ISSUE THREAD

**Issue by lookis** [kriasoft/react-starter-kit#1603]
My application running under some baseUrl like "/[project]", I think config.js is the best place for it, and I need to add this baseUrl into router.js at the same time, but config.js reject to run under browser environment, any suggestion?

**Comment by tim-soft** [comment]
you can either make another config, like `clientConfig.js` that has public/non-sensitive information, or pass in a baseUrl as an env variable to the front-end via context/redux/whatever.

**Comment by rodeyseijkens** [comment]
I pass in the baseUrl through that from the server side through the context & the data.app variables so that also in my html.js I can set a [<base>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) tag etc then I can safely put it in my config.js without exposing it to the client code.

_server.js_
```js
const context = {
  baseUrl: config.baseUrl,
  ...
}

data.app = {
  baseUrl: context.baseUrl,
  ...
}
```

_Html.js_ (Something like this for example for serving files from that route).
```html
<base href={app && app.baseUrl ? `${app.baseUrl}/` : '/'} />
```

**Comment by lookis** [comment]
Thank you all

**Comment by ACPK** [comment]
@lookis - Can this issue be closed now?

**Comment by lookis** [comment]
OK，thx very much
