### ISSUE TITLE
How can I checkout the feature branch?

### ISSUE THREAD

**Issue by pfxstar** [kriasoft/react-starter-kit#1604]
I followed the Getting Started Guide to clone single-branch only:
git clone -o react-starter-kit -b master --single-branch https://github.com/kriasoft/react-starter-kit.git MyApp

After cloned the master branch, I tried to checkout the feature branch "feature/react-intl".
I run these commands:
1. git fetch react-starter-kit feature/react-intl
From https://github.com/kriasoft/react-starter-kit
 * branch            feature/react-intl -> FETCH_HEAD
2. git checkout feature/react-intl
error: pathspec 'feature/react-intl' did not match any file(s) known to git

I can't checkout the feature branch. Please help me to solve this problem.
Thank you so much!

**Comment by damiangreen** [comment]
You need to merge the branch to your master after checking it out.
[see](https://github.com/kriasoft/react-starter-kit/blob/master/docs/recipes/how-to-integrate-react-intl.md)
I am however getting merge conflicts when i do this right now.

**Comment by ulani** [comment]
@pfxstar   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
