### ISSUE TITLE
Test suite failed to run (Feature/Apollo)

### ISSUE THREAD

**Issue by jeric17** [kriasoft/react-starter-kit#1620]
Test suite failed to run using feature/apollo branch

Webpack 4.10.0
React 16.4.0

Jest encountered an unexpected token
      This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
      By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
      Here's what you can do:
       • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
       • If you need a custom transformation specify a "transform" option in your config.
       • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
      You'll find more details and examples of these config options in the docs:

**Comment by zhangfaliang** [comment]
npm i -D jest babel-jest babel-preset-es2015 babel-preset-react react-test-renderer

**Comment by ulani** [comment]
@jeric17   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
