### ISSUE TITLE
Change to the 16.3 React Context API

### ISSUE THREAD

**Issue by rodeyseijkens** [kriasoft/react-starter-kit#1625]
So currently the project still uses the Legacy Context.
React 16.3 introduced the new [Context API](https://reactjs.org/docs/context.html).

So because the Legacy will be deprecated in React 17+, we should start thinking about moving to the new Context API.

_Just throwing it out there.
Maybe I'll pick it up or if someone else is happy to do it you know what to do ;)_

**Comment by ulani** [comment]
@rodeyseijkens   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
