### ISSUE TITLE
Accessing Context Variables

### ISSUE THREAD

**Issue by reeda6** [kriasoft/react-starter-kit#1628]
Hello,

Disclaimer: I am new to React. I was wondering how I can access context variables? I read a little online how to do it but I was wondering if there is a different set up for this kit. I tried following the instructions online and was receiving errors. 

server.js:
```js
const context = {
  // Enables critical path CSS rendering
  // https://github.com/kriasoft/isomorphic-style-loader
  insertCss: (...styles) => {
    // eslint-disable-next-line no-underscore-dangle
    const removeCss = styles.map(x => x._insertCss());
    return () => {
      removeCss.forEach(f => f());
    };
  },
  // Universal HTTP client
  fetch: createFetch(fetch, {
    baseUrl: window.App.apiUrl,
  }),
  hello: "trying to get this to appear"
};
```
I can see the hello variable in App.js but can not see it in the children components.

Thanks!

**Comment by langpavel** [comment]
This is for old context API  which is still used.
You must define `ContextType` property to see it. 
I'm also recommending you to look at new `React.createContext` API

**Comment by ulani** [comment]
@reeda6   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
