### ISSUE TITLE
demo.reactstarter.com 502 Bad Gateway.

### ISSUE THREAD

**Issue by jshuadvd** [kriasoft/react-starter-kit#1632]
Demo Site does not work. SSL isn't there nor does the site load.

**Comment by ulani** [comment]
@jshuadvd   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
