### ISSUE TITLE
You should not use <Link> outside a <Router>

### ISSUE THREAD

**Issue by markolofsen** [kriasoft/react-starter-kit#1633]
Got an error `You should not use <Link> outside a <Router>`
How to fix it? I can't to find <Router> nowhere

**Comment by ulani** [comment]
@markolofsen   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
