### ISSUE TITLE
Critical dependencies, the request of a dependency is an expression

### ISSUE THREAD

**Issue by JosethC** [kriasoft/react-starter-kit#1641]
I have this warning when I ran my project.

![image](https://user-images.githubusercontent.com/22751723/42478788-47587b20-8393-11e8-88f3-06e3d8c8d02b.png)

This is the declaration of the routes
`const routes = [`
  `require('./routes/margarita'),`
  `require('./routes/consultoriaux'),`
`]`

I want to know how I can fix this.

**Comment by ulani** [comment]
@JosethC   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
