### ISSUE TITLE
How to replace GraphQL to REST API?

### ISSUE THREAD

**Issue by daryn-k** [kriasoft/react-starter-kit#1642]
This boilerplate is very very complicated. Who can tell me how to replace GraphQL to REST API? Thanks.

**Comment by klaaz0r** [comment]
GraphQL is not tightly coupled in the boilerplate, you can simple remove the middlewares from the server and replace the `data/` folder GraphQL's features with restful endpoints. And another thing that comes to mind is changing the `createFetch` function

**Comment by ulani** [comment]
@daryn-k   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
