### ISSUE TITLE
is Saga feature supported?

### ISSUE THREAD

**Issue by Lokesh235** [kriasoft/react-starter-kit#1644]
How do we integrate saga in this boiler plate? is there any doc for that.
Please help. Thanks

**Comment by Arrow891** [comment]
Here is a [very good article](https://hackernoon.com/replacing-redux-thunks-with-redux-sagas-4aa306854925) that guides you to hit the bulb  💡  :D

**Comment by ulani** [comment]
@Lokesh235   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
