### ISSUE TITLE
Test suite failed to run (feature/react-intl)

### ISSUE THREAD

**Issue by aureustaurus** [kriasoft/react-starter-kit#1645]
Test suite failed to run using feature/react-intl branch

I cleare node-modules and pulled from origin feature/react-intl
- `git pull origin feature/intl`

then install all packeges
- `npm install`

and then run test
- `npm run test`

and get this image:
![image](https://user-images.githubusercontent.com/10784396/42885991-217aad1e-8aab-11e8-9d06-bc65cde4e07a.png)

How can i fix the same issue in my project?

- `npm i -D jest babel-jest babel-preset-es2015 babel-preset-react react-test-renderer`
from: https://github.com/kriasoft/react-starter-kit/issues/1620
didn't help :)

**Comment by ulani** [comment]
@aureustaurus   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
