### ISSUE TITLE
How to convert to SPA mode ?

### ISSUE THREAD

**Issue by be-next-hotdog** [kriasoft/react-starter-kit#1650]
Hi guys, 
Wish to have a fantastic switch feature to turn into SPA mode instead of remoulding manually ?
thx for any tips :)

**Comment by rodeyseijkens** [comment]
Can you be more specific? Even with SSR on it technically is a SPA cause only the SSR is done on initial call then it is client side only from that point on.

Technically you can use the ```npm run render``` command, to have it run on client side only and create an index.html, I guess if that is what you mean?

**Comment by be-next-hotdog** [comment]
Yepp, exactly, but I got an babel (bete-55) error on master branch, I'm gonna fix it to see the final render result.

**Comment by be-next-hotdog** [comment]
PS: Cause by  https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets

**Comment by ulani** [comment]
@be-next-hotdog   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
