### ISSUE TITLE
an Apollo client which polls under invokes componentWillReceiveProps once

### ISSUE THREAD

**Issue by damiangreen** [kriasoft/react-starter-kit#1653]
and then never re-renders when the ajax call returns.

I've checked the ajax call is being sent.
I tried disabling the cache. I've tried with both `<Query> `and  graphql()

I've tried using the recompose library withState()

Run out of ideas

**Comment by ulani** [comment]
@damiangreen   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
