### ISSUE TITLE
window.EventSource(options.path) このオブジェクトではサポートされていない操作です。

### ISSUE THREAD

**Issue by yasuyuki1203** [kriasoft/react-starter-kit#1655]
react-redux-material-starter-kit-master.zip
↑をnpm run build しました。

After that, after starting with npm run start,
When browsing with the IE browser (IE 11), the engine below will be emitted to the convolver.
"This is an unsupported operation on this object."

In the debugger of the IE browser, an error occurs at the point
function init() {
    source = new window.EventSource(options.path);　←　this
    source.onopen = handleOnline;
    source.onerror = handleDisconnect;
    source.onmessage = handleMessage;
}

Action Please tell me if you understand.

**Comment by rodeyseijkens** [comment]
Can you translate this to English plz? We can't help you like this.

**Comment by yasuyuki1203** [comment]
Do you understand？

**Comment by rodeyseijkens** [comment]
If you want IE11 support change the package: `query-string` to version `5.1.1`
Since 6.0.0 that package doesn't work anymore in IE11.

**Comment by yasuyuki1203** [comment]
Thank you very much.
However, in the case of query-string to version 6.0.0,
I get an error ↓. What should I do?

function encoderForArrayFormat (options) {
switch (options.arrayFormat) {
case 'index':
return (key, value, index) => {← ※

**Comment by rodeyseijkens** [comment]
Not use that version on IE11 cause it doesn't work.

**Comment by ulani** [comment]
@yasuyuki1203   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
