### ISSUE TITLE
Logging in react-starter-kit

### ISSUE THREAD

**Issue by fedor-chemashkin** [kriasoft/react-starter-kit#1658]
I started working on my app which based on react-starter-kit. With the increasing complexity of my app, I thought that I need to add more detailed logging. Is there any "react-starter-kit way" for logging?

**Comment by piglovesyou** [comment]
Originally it's implemented with basic stdout and stderr style so you can use stdout as like "info log" and stderr as "runtime error log". If you'd like to go further, it all depends on what you want. My colleague uses [Log4js](https://github.com/log4js-node/log4js-node). If you collect logs by fluentd or something so more parsable type logging is expected, personally I recomment [Pino](https://getpino.io/).

**Comment by ulani** [comment]
@fedor-chemashkin   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
