### ISSUE TITLE
passport implmentation - profile.id or accessToken for 'value' property in claims? 

### ISSUE THREAD

**Issue by valeeum** [kriasoft/react-starter-kit#1662]
Line number 60 from passport.js file has profile.id in the claims field. 

https://github.com/kriasoft/react-starter-kit/blob/0dbae5354bcb52f66fa4dfad2de5f87a42656d49/src/passport.js#L60

Shouldn't we use  accessToken instead of profile.id like it is on line 112? 
https://github.com/kriasoft/react-starter-kit/blob/0dbae5354bcb52f66fa4dfad2de5f87a42656d49/src/passport.js#L112

**Comment by ulani** [comment]
@valeeum   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
