### ISSUE TITLE
Restrict "/graphql" route from external requests?

### ISSUE THREAD

**Issue by gijonc** [kriasoft/react-starter-kit#1671]
Under production mode, I can still see response message from `www.example.com/graphql`, I want to restrict all requests to `/graphql` so that can only be accessed through the same server/host url. Has anyone tried to do the same thing?

**Comment by ulani** [comment]
@gijonc   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
