### ISSUE TITLE
Update State of Parent without sending Props Or refs From App

### ISSUE THREAD

**Issue by ask2mahtab** [kriasoft/react-starter-kit#1672]
I want to Update The State of Parent on click of button which is child but parent and  child both is separate component which is being called in app.

class App extends React.Component {
    render() {
        return (<React.Fragment>
            <Parent>
                <Child />
            </Parent>
        </React.Fragment>)
    }
}
class Parent extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            msglength: 0
        }
    }
    changeTheMsgValue = () => {
        let msglength = this.state.msglength + 1;
        this.setState({
            msglength: msglength
        })
    }
    render() {
        return (<React.Fragment>
            <form
                msglength={this.state.msglength}
                parentStatecall={this.changeTheMsgValue.bind(this)}
            >
                {this.state.msglength}
                {this.props.children}
            </form>
        </React.Fragment>)
    }
}
class Child extends React.Component {
    constructor(props) {
        super(props)

    }
    render() {
        return (<React.Fragment>
            <input type="button" value="click" onClick={this.props.parentStatecall} />
            <div>{JSON.stringify(this.props)}</div>
        </React.Fragment>)
    }
}
ReactDOM.render(<App />, document.getElementById('root'));

**Comment by ulani** [comment]
@ask2mahtab   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
