### ISSUE TITLE
How to remove yarn and use the normal 'npm'

### ISSUE THREAD

**Issue by shyaaam** [kriasoft/react-starter-kit#1682]
Linking dependencies in yarn is taking 30-45min which is simply unacceptable. And there is little or no support in their github issue tracker. Im fed up. Please tell me how to remove yarn from this, i am happy with npm ? Please advise. I tried to install some package via npm, but then when i run the project it says incorrect dependencies..

**Comment by langpavel** [comment]
Both, npm and yarn should work just fine. Where are your build process from, it tooks under half minute for me and under 10 seconds from cache.

**Comment by ulani** [comment]
@shyaaam   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
