### ISSUE TITLE
How to generate new dynamic routes for static builds with content created in a headless cms

### ISSUE THREAD

**Issue by raphaellarrinaga** [kriasoft/react-starter-kit#1683]
Hi, I wonder what could be a solution to generate dynamic routes (understand deploy a new static build) as new content is created under prismic.
My content is managed under Prismic and my app is hosted on github pages.

So, I am talking about dynamic routes defined in `render.js` file.
See https://github.com/kriasoft/react-starter-kit/blob/master/tools/render.js#L37

I can't see something else than a routine that querries prismic api to check if it returns an updated Object with new content then deploy a new build.
But that should be done from a server, which is not the idea.

Did somebody faced that problem ?
What could be another solution ?

**Comment by ulani** [comment]
@raphaellarrinaga   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
