### ISSUE TITLE
Why use experimental babel ?

### ISSUE THREAD

**Issue by panos-kouf** [kriasoft/react-starter-kit#1687]
This is a very nice boilerplate which could be used on production, why not make it as stable as possible ?

**Comment by piglovesyou** [comment]
Good point. But there are always ES proposals that we cannot wait, aren't there 😏

**Comment by ulani** [comment]
@panos-kouf   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
