### ISSUE TITLE
how to import antd?

### ISSUE THREAD

**Issue by TristanDongMaster** [kriasoft/react-starter-kit#1690]
I encouter the issues: the project DO NOT import the antd css file when i follow the steps:
 rules: [
          {
            test: /\.css$/,
            include: [/node_modules\/.*antd/],
            loader: 'style-loader',
          },

          // Convert CSS into JS module
          {
            issuer: { not: [reStyle] },
            exclude: [/node_modules\/.*antd/],
            use: 'isomorphic-style-loader',
          },

// Only use babel-plugin-import in client side
clientConfig.module.rules[0].options.plugins = [
  ...clientConfig.module.rules[0].options.plugins,
  ['import', { libraryName: 'antd', style: 'css' }],
];

**Comment by ulani** [comment]
@TristanDongMaster  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
