### ISSUE TITLE
How to get router in redux store  - set from server

### ISSUE THREAD

**Issue by sanjitbauli** [kriasoft/react-starter-kit#1695]
In my application everywhere in my component, i am using location.pathname and location.search.
Now from server side configure store, it is setting history as null, then how can i access pathname inside any component?
```
//Not working...

const mapStateToProps = (state) =>{
  console.log("router__", state.router);
    return {
        pathname: state.router.location.pathname,
        query:state.router.location.search
    }
}
//Not working...
const mapStateToProps = (state) =>{
  console.log("router__", state.router);
    return {
        pathname: history.location.pathname,
        history.location.search
    }
}
```

**Comment by mmarkelov** [comment]
@sanjitbauli you can do something like this:
For example pass query and path from home component:

        react-starter-kit/src/routes/home/index.js
      
```javascript
import React from 'react';
import Home from './Home';
import Layout from '../../components/Layout';

// You can get query and path like this
async function action({ query, path }) {
// And than you can pass it as props to your component
  return {
    title: 'React Starter Kit',
    chunks: ['home'],
    component: (
      <Layout>
        <Home query={query} path={path} />
      </Layout>
    ),
  };
}

export default action;
```

**Comment by ulani** [comment]
@sanjitbauli   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
