### ISSUE TITLE
Out-of-the-box etag support from express is broken in redux branch 

### ISSUE THREAD

**Issue by apsavin** [kriasoft/react-starter-kit#1705]
The reason is https://github.com/kriasoft/react-starter-kit/blob/feature/redux/src/reducers/runtime.js

It adds new runtimeVariable every time so the content of pages is different.

**Comment by ulani** [comment]
@apsavin   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
