### ISSUE TITLE
Add home route to client.js to reduce size of all route chunks

### ISSUE THREAD

**Issue by samkelleher** [kriasoft/react-starter-kit#1707]
Reopens #1514 as the changes made in #1515  was reverted in #1571 

The regression brings back large bundle sizes.

When opening the root page, the following chunks are added:
Without fix:
```
<script src="/assets/vendors.chunk.js"></script>
<script src="/assets/client.js"></script>
<script src="/assets/vendors~about~admin~contact~home~login~not-found~privacy~register.chunk.js"></script>
<script src="/assets/about~admin~contact~home~login~not-found~privacy~register.chunk.js"></script>
<script src="/assets/home.chunk.js"></script>
```

With fix:
```
<script src="/assets/vendors.chunk.js"></script>
<script src="/assets/client.js"></script>
```

**Comment by ulani** [comment]
@samkelleher   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
