### ISSUE TITLE
can i use mdbreact on this proyect?

### ISSUE THREAD

**Issue by squirtle34** [kriasoft/react-starter-kit#1711]
hi i triying to use MDBreact with react starter-kit but i i dont know how can i do for appply the css styles... im newbie plz can u help me?

**Comment by ulani** [comment]
@squirtle34   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
