### ISSUE TITLE
does not pickup gulpfile.babel.js file

### ISSUE THREAD

**Issue by windyboy** [kriasoft/react-starter-kit#172]
npm -v
2.11.3
node -v
v0.12.7
gulp -v
[16:42:59] CLI version 3.8.11
[16:42:59] Local version 3.9.0

I try to run gulp at project directory.
It seems like gulp does not pickup config file.
##

**Comment by koistya** [comment]
@windyboy you can either update your global gulp version to 3.9.0 (`npm update -g gulp`).. or, you can use npm scripts which startup local version of gulp (`npm run build` or `npm run sync`)

**Comment by windyboy** [comment]
@koistya  
I execute npm update -g gulp, but the local version  does not change to 3.9.0

npm run build
npm run sync 
these scripts works!

**Comment by windyboy** [comment]
@koistya 
sudo npm install -g gulp-cli
gulp -v
[11:18:52] Requiring external module babel-core/register
[11:18:52] CLI version 3.9.0
[11:18:52] Local version 3.9.0

update gulp-cli to version 3.9.0, gulp pick up the config file.
but gulp build get error message.
src/components/App/App.js
      72:8  error  Infix operators must be spaced  space-infix-ops

It seems like there is space problems in " ) : <NotFoundPage />; "

**Comment by timdoes** [comment]
These errors can be changed to warnings by adding `"space-infix-ops": 1,` to the `.eslintrc` file under `"rules"`.

**Comment by windyboy** [comment]
@timdoes 

``` "space-infix-ops": 1, ``` works

The error message change to warn.

**Comment by pebie** [comment]
If I may,

Updating gulp twice done nothing. I was ```CLI Version 3.8.1``` and ```Local version 3.9.0```.
But try to reload Terminal (or wathever) then retry ```gulp --v```
It works for me :)

Stupid thing.

**Comment by windyboy** [comment]
@pebie 
try npm install gulp-cli -g

**Comment by pebie** [comment]
@windyboy It's ok for me thanks. My issue was that I forgot to reload Terminal just after update.

**Comment by oliverbenns** [comment]
Is there a reason why the README doesn't state to use the npm scripts as opposed to gulp tasks? Npm scripts always default to the local binaries. Resulting in issues like this not cropping up.

**Comment by koistya** [comment]
@oliverbenns good point, it would be better to replace `gulp` commands with `npm` commands in the docs. And also would be great to replace `gulpfile.babel.js` with custom `.js`-based build scripts, since most of the work is done by webpack, and there is very little room for streams and stuff. Here is an example: https://github.com/koistya/react-static-boilerplate (see `tools` folder)

**Comment by ulani** [comment]
@windyboy   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
