### ISSUE TITLE
Upgrading to react-redux 6

### ISSUE THREAD

**Issue by makeitraina** [kriasoft/react-starter-kit#1722]
Is there any plan to upgrade the feature/redux branch to use react-redux 6? Currently the store is integrated into the context. This approach will no longer work with v6.

If anyone has an example or advice on how to upgrade that would be really appreciated. In a very basic attempt I tried to pass the store as a prop to main App component and register the Provider.

```
<Provider store={this.props.store}>
        {React.Children.only(this.props.children)}
</Provider>
```

However, this leads to other issues with the isomorphic-style-loader:
`Cannot read property 'insertCss' of undefined`

**Comment by GriffinSauce** [comment]
Hey @makeitraina did you figure out how to set this up?

**Comment by GriffinSauce** [comment]
Okay so I don't have to to create a whole PR because our repo has diverged from the starter kit but I'll try to describe what I did to get this working:

In `server.js` and `client.js`:
```
      <ReduxProvider store={store}>
        <StyleContext.Provider value={{ insertCss }}>
          <App>{route.component}</App>
        </StyleContext.Provider>
      </ReduxProvider>,
```
You can remove all the context stuff from `App.js` then. If you're using context you can just set it up as the new context docs explain. (Create one, add a provider in that stack, connect it to your component)

The latest version of isomorphic-style-loader has support for the new context, that's where `StyleContext` comes from. When you upgrade you'll have to replace all:
```import withStyles from 'isomorphic-style-loader/lib/withStyles';```
with:
```import withStyles from 'isomorphic-style-loader/withStyles';```

I bumped package versions to:
```
"react": "^16.8.6",
"react-dom": "^16.8.6",
"redux": "^4.0.4",
"react-redux": "^7.1.0",
"isomorphic-style-loader": "^5.1.0",
```

**Comment by makeitraina** [comment]
@GriffinSauce At the time I ended up sticking with v5. Your solution seems like the right approach here.

**Comment by ulani** [comment]
@makeitraina   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
