### ISSUE TITLE
Question: Any interest in putting together a premium version for sale on SugarKubes?

### ISSUE THREAD

**Issue by wrannaman** [kriasoft/react-starter-kit#1728]
Hi @kriasoft, congrats on the traction. Would you be interested in putting together a premium version of this repo to sell on [SugarKubes](https://sugarkubes.io)? It's a code and container marketplace I'm putting together.

**Comment by ulani** [comment]
@wrannaman   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
