### ISSUE TITLE
How to disable SSR completely 

### ISSUE THREAD

**Issue by jsvishal** [kriasoft/react-starter-kit#1737]
Hi , I have developed one of my application using this starter kit,

Now we want our application to not perform SSR 
I know SSR has many benefits but we need it to render on the client side

Can anyone please help.
I tried  many things but no luck

**Comment by mmarkelov** [comment]
@jsvishal maybe you shouldn't use RSK for your approach? https://github.com/kriasoft/react-starter-kit/issues/984#issuecomment-261797529
But also you can check https://github.com/kriasoft/react-starter-kit/pull/833

**Comment by jsvishal** [comment]
I have removed this line. Its seem to work.

let me know if this is fine
```
data.children = ReactDOM.renderToString(
            <App context={context}>{route.component}</App>,
);
```

```
data.children = ""   //working
```

**Comment by mmarkelov** [comment]
@jsvishal youp! You can just comment **data.children = ...** and it won't do any server rendering

**Comment by jsvishal** [comment]
But it calls APIs on serverside

**Comment by ulani** [comment]
@jsvishal   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
