### ISSUE TITLE
SyntaxError: Unexpected token .     at Module._compile - When rendering react component on server side with import css 

### ISSUE THREAD

**Issue by renji** [kriasoft/react-starter-kit#1738]
I use **express-react-views** npm package to render the react components on Server side(nodejs). I have a react component that import style from a css file. I use  **import 'react-activity-feed/dist/index.css';** for that. I am stuck with the error 
**/home/renjisujin/Public/community-zenler/node_modules/react-activity-feed/dist/index.css:1**
**body [class^='raf-'],**
           **^^**

**SyntaxError: Unexpected token ^=**
when running npm start. Please help to resolve this issue.

**Comment by ulani** [comment]
@renji   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
