### ISSUE TITLE
SSL certificate expired for reactstarter.com (again)

### ISSUE THREAD

**Issue by alopatin** [kriasoft/react-starter-kit#1739]
```
reactstarter.com
Issued by: Let's Encrypt Authority X3
Expired: Monday, June 10, 2019 at 4:35:29 PM Pacific Daylight Time
```

Previous issue from October 2018: https://github.com/kriasoft/react-starter-kit/issues/1681
Previous issue from December 2017: https://github.com/kriasoft/react-starter-kit/issues/1485

Let's Encrypt SSL certificates expire every 90 days; you should really be automating the renewal process.

**Comment by piglovesyou** [comment]
> Expires: Saturday, August 10, 2019 8:31:35 Japan 
Now it's valid. See what happens on the expiring date

**Comment by shrthnd** [comment]
> Expired: Wednesday, February 5, 2020 at 6:20:42 PM Eastern Standard Time

I think you still need to automate this... Is this project still alive?

**Comment by ulani** [comment]
@alopatin   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
