### ISSUE TITLE
Cannot read property 'title' of null

### ISSUE THREAD

**Issue by Panamer** [kriasoft/react-starter-kit#1740]
npm start
appear  Cannot read property 'title' of null   three times
How to solve

**Comment by mmarkelov** [comment]
@Panamer could you provide some more info, please?

**Comment by ulani** [comment]
@Panamer   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
