### ISSUE TITLE
ReactJS code compiled successfully but the output is not displayed on browser 

### ISSUE THREAD

**Issue by RohitSavant24** [kriasoft/react-starter-kit#1741]
I am new to ReactJS ( still learning ).
I installed ReactJS properly , and when i run the project after executing the command npm start , i am redirected to the browser, but the output is not displayed...

this is the code and files that i have created...
https://pastebin.com/LBw7h2Rm

Someone Please resolve this issue ASAP.
Thank You.

**Comment by ulani** [comment]
@RohitSavant24   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.

**Comment by blackboardcoder** [comment]
Due to syntax error.
