### ISSUE TITLE
Any advice for build/bundle speed?

### ISSUE THREAD

**Issue by GriffinSauce** [kriasoft/react-starter-kit#1744]
We've built our app based on this starter kit with redux added. We've done some tweaks over time but it's not too far away from the original setup.

That said, as our app grows (24 routes, lotsa components) it's getting very slow to build and bundle. Adding cache-loader provides some relief but it still feels like I'm swimming through pudding most of the time.

Do you have any advice on where to look? Is it just the size of the project or could it be that I need to investigate our dependencies?

**Comment by piglovesyou** [comment]
You might have already looked, but the webpack team builds [a neat guide for it](https://webpack.js.org/guides/build-performance/).

**Comment by ulani** [comment]
@GriffinSauce   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
