### ISSUE TITLE
Infix operator error in App.js

### ISSUE THREAD

**Issue by amit242** [kriasoft/react-starter-kit#177]
Getting the below error on "gulp build"
...\src\components\App\App.js
 72:8  error  Infix operators must be spaced  space-infix-ops
##

**Comment by soluwalana** [comment]
I'm also getting this error on a fresh pull of the code base.

**Comment by timdoes** [comment]
A temporary fix for this is here #172

**Comment by soluwalana** [comment]
ありがとう！

**Comment by timdoes** [comment]
@soluwalana 
どういたしまして！

**Comment by ulani** [comment]
@amit242   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
