### ISSUE TITLE
Jade implementation

### ISSUE THREAD

**Issue by sebgos** [kriasoft/react-starter-kit#180]
Did you think about implementation of http://jade-lang.com/ into this starter-kit? I was using it in some angularJS projects and it's really powerfull.
##

**Comment by koistya** [comment]
@gos-sebastian it currently uses Jade for static content (about us, privacy policy etc. pages) https://github.com/kriasoft/react-starter-kit/tree/master/src/content

**Comment by gos-sebastian** [comment]
@koistya I saw this, but it would be great to have it with bootstrap and dynamic pages

**Comment by koistya** [comment]
@gos-sebastian so that some portion of the site could work with regular static pages (not as SPA)?

**Comment by vladikoff** [comment]
I was kinda wondering why Jade is needed at all, why not pipe everything through React / JSX or some other JS templating, especially with server rendering

**Comment by Jahans3** [comment]
@vladikoff Also wondering this. Whenever I have a templating engine like Jade or Hogan in a React project it always gets wasted

**Comment by arvigeus** [comment]
This issue can be closed: Jade was removed in favor of Markdown.

**Comment by ulani** [comment]
@sebgos   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
