### ISSUE TITLE
Authentication router

### ISSUE THREAD

**Issue by kingend00** [kriasoft/react-starter-kit#1868]
How can i check login and permission in all router , using Cookie

**Comment by HapoGFL** [comment]
who are u?

**Comment by samankhademi** [comment]
in server.js get your token & permission from req.cookies and set in Redux,
then you can access Authentication result in Header Component for display menus Or each Route Index File for check user access(for example you want show some route only for logged in users or user access) or Route/Index in action method

**Comment by ulani** [comment]
@kingend00  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
