### ISSUE TITLE
Wildcard instead of GraphQL?

### ISSUE THREAD

**Issue by brillout** [kriasoft/react-starter-kit#1873]
Hi!

I'm curious, what do you think of using [Wildcard API](https://github.com/reframejs/wildcard-api#readme) instead of GraphQL?

As far as I can tell, Wildcard would be a better fit. What do you think?

**Comment by ulani** [comment]
@brillout   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
