### ISSUE TITLE
How to upload file ?

### ISSUE THREAD

**Issue by akhileshacc** [kriasoft/react-starter-kit#1875]
What is best way to upload file.  I have tried fetch, but form doesn't send correct 'Content-Type' and it fails. Please help.

**Comment by adithyaakrishna** [comment]
Hi @akhileshacc , Could you give me a better description of the problem?
& Hi @piglovesyou  Can I work on this issue? :)

**Comment by piglovesyou** [comment]
Hi @adithyaakrishna, of course. Only, I can't promise to merge the PR if you're willing to create one, since file uploading logic would be hard to be generalized I guess, eg. where to store, how to handle it in GraphQL API, etc. But I'm curious what your sample looks like anyway🙂

**Comment by adithyaakrishna** [comment]
Okay @piglovesyou , Thank You! 🚀

**Comment by ulani** [comment]
@akhileshacc   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
