### ISSUE TITLE
modify className and new class dosen't update in browser

### ISSUE THREAD

**Issue by kayleeWei** [kriasoft/react-starter-kit#1876]
1. clone the latest respository
2. yarn & yarn start
3. modify any className in component,(such as changing "className={s.brandText}" in Header.js into "className={s.brandText1}")
4. change the corresponding class name in css file, (such as changing ".brandText" into ".brandText1" )
5. save the above changes, the browser doesn't reload, and the class "brandText1" wasn't add to the dom

**Comment by kayleeWei** [comment]
node v10.16.1
yarn 1.17.3
chrome  80.0.3987.87

**Comment by ulani** [comment]
@kayleeWei   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
