### ISSUE TITLE
Adopt TODO.md for task list

### ISSUE THREAD

**Issue by ngduc** [kriasoft/react-starter-kit#1882]
Hi,
Thanks for creating this great boilerplate!

I have some thoughts about the project task list:
- It's hard to find out what are the current plans, ideas or tasks being worked on.
- Having a source of truth like TODO.md will help users quickly know about them which leads to more engagement.

Please adopt a TODO.md file for task list like the example here - https://github.com/coddx-hq/coddx-alpha

![image](https://user-images.githubusercontent.com/639189/77603370-25380200-6ecd-11ea-92d5-436e2fc3ca55.png)

Thanks.

**Comment by ulani** [comment]
@ngduc   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
