### ISSUE TITLE
reactstarter.com ssl certificate is expired

### ISSUE THREAD

**Issue by pahaz** [kriasoft/react-starter-kit#1883]

**Comment by ulani** [comment]
@pahaz   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
