### ISSUE TITLE
i have duplicate chunk build time

### ISSUE THREAD

**Issue by benamm** [kriasoft/react-starter-kit#1886]
<img width="712" alt="Screen Shot 1399-02-17 at 21 57 12" src="https://user-images.githubusercontent.com/40948849/81208592-90084d00-8fe4-11ea-8210-21bd608a6b95.png">

**Comment by benamm** [comment]
someone can help

**Comment by ulani** [comment]
@benamm   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
