### ISSUE TITLE
Login with user/password not working: Cannot POST /login

### ISSUE THREAD

**Issue by ptsmonteiro** [kriasoft/react-starter-kit#1887]
Hello,

When trying to login using username and password, I get:

`Cannot POST /login`

The same is happening in the demo site.

**Comment by ulani** [comment]
@ptsmonteiro   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
