### ISSUE TITLE
http2/spdy support?

### ISSUE THREAD

**Issue by nuclearspike** [kriasoft/react-starter-kit#1900]
I'd love to see this project get http2 support with some built-in routing support for good patterns for push of the css and js needed for the various packages. Or do it as a feature branch.

**Comment by frenzzy** [comment]
Need to just use a reverse proxy in front of node.js like Nginx with configured certs for http2/https. It makes no sense to use http2 on node.js side since it complicates the development process and affects performance. Also if your web application has some production load you will use cache proxy in anyway.

**Comment by ulani** [comment]
@nuclearspike   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
