### ISSUE TITLE
Import lib in browser

### ISSUE THREAD

**Issue by josecao** [kriasoft/react-starter-kit#1903]
Hi author,

I am using react-start-kit and use react-viewer, but now the version isn't support for ssr. Is there any way I can use it?

Thanks, looking forward to reply from you soon !!

**Comment by samankhademi** [comment]
it's very simple example 

```
// define package
let Lib = false;
//check if run CSR
if(process.env.BROWSER){
   //import
   Lib = require('lib');
}


class foo extends React.Component{
     render(){
       return (<div>
           {*/ check it */}
           {Lib && <Lib/>
       </div>)
    }
}


export default foo;
```

**Comment by ulani** [comment]
@josecao   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
