### ISSUE TITLE
Embedding a component in an existing web application

### ISSUE THREAD

**Issue by theunreal** [kriasoft/react-starter-kit#1914]
Hi,
I have created a React app using this starter, and I would like to show a react component in an existing web application, which was not created in React (old code)

I have read on how to use react components on an existing application, but it's not clear with this starter - since the need to decouple the server from the client (unless I'm wrong)

My goal is to use different React components and embed them independently in an existing web page.

Any instructions on how I can show react component from this starter components directory on another HTML web page with is not part of this project?

Thanks,

**Comment by ulani** [comment]
@theunreal   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
