### ISSUE TITLE
Unable to resolve path to module 'buefy'

### ISSUE THREAD

**Issue by Noxiess** [kriasoft/react-starter-kit#1916]
Unable to resolve path to module 'buefy'

_Originally posted by @Noxiess in https://github.com/kriasoft/react-starter-kit/issues/1180#issuecomment-702207924_

**Comment by ulani** [comment]
@Noxiess   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
