### ISSUE TITLE
Question on routing 

### ISSUE THREAD

**Issue by AbrahamMunguia** [kriasoft/react-starter-kit#1919]
Hi! The team I'm working with, uses `react-starter-kit` as boiler plate but, we're curious if, we can use `react-router-dom` or, if we're married to `universal-routing` 

Just curious 👍  If we can use either, is there a tutorial/guide on how to implement both? Thanks!

**Comment by ulani** [comment]
@AbrahamMunguia   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
