### ISSUE TITLE
Unable to Load Images in React

### ISSUE THREAD

**Issue by rjptechsolutions** [kriasoft/react-starter-kit#1920]
Actually I not getting any error at the terminal but static images are not loading and react unable to find the path of the image too. Something goes wrong with the path when I inspect and open images on a different  tab then I get the following URL 
http://localhost:3000/[object%20Module]
I did get this " [object%20Module] " 
See my code: 
I created one data.js file where I getting data

`export const dataObj = {
    img: require('../../Assets/Images/img-1.png'),
    alt: 'img'    
  };`

mySection.js
`
function InfoSection({  
  img,
  alt
}) {
  return (
<>
 <Img src={img} alt={alt} />
</>
`
and create page called home.js
`
import {dataObj} from './Data'

export default function Home() {
    return (
        <>
            <InfoSection {...dataObj}/>
        </>
    )
}
`
please help me I didn't get any reference regrading this..

**Comment by ulani** [comment]
@rjptechsolutions   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
