### ISSUE TITLE
You are missing the split code

### ISSUE THREAD

**Issue by tomtom94** [kriasoft/react-starter-kit#1924]
Hello, you forgot that your app is a monopage very long to download.

Please just enjoy this starter kit I made myself https://github.com/tomtom94/react-easy-ssr

`loadable-components` is installed in my repo

**Comment by mauryakrishna** [comment]
I was looking for the way to use `univarsal-router` with `loadable-components` but could not find any example.

@tomtom94 did you tried integrating `loadable-component` into existing `react-starter-kit`? Can tell me how to split code at router level. All my routes are combined into one chunk. Same goes for vender chunk for these component.

**Comment by tomtom94** [comment]
@mauryakrishna just do like this https://github.com/tomtom94/react-easy-ssr/blob/master/src/views/routes.js#L8

and give me a star for this react starter kit thanks

**Comment by ulani** [comment]
@tomtom94   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
