### ISSUE TITLE
Elaborate on feature/react-intl instructions

### ISSUE THREAD

**Issue by mscheper** [kriasoft/react-starter-kit#1939]
I'm a pretty old hand at git, but I still got stuck at step one in [How to Integrate React Intl](https://github.com/kriasoft/react-starter-kit/blob/master/docs/recipes/how-to-integrate-react-intl.md#how-to-integrate-react-intl). A [StackOverflow answer](https://stackoverflow.com/a/46557598/1450294) offered some help, but (presumably) because of #1871, the furthest I've gotten is a tonneo' merge conflicts.

I think an example `git` command would elaborate well.

Cheers.

**Comment by ulani** [comment]
@mscheper   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
