### ISSUE TITLE
Support for csr mode.

### ISSUE THREAD

**Issue by brizer** [kriasoft/react-starter-kit#1948]
This project currently only has the ssr mode now. It is best to provide a way to switch mode to CSR.

For example, we can launch project as CSR mode, or it takes effect when parameters are attached to the url such as `?csr=true`.

The changes are also very simple, First we set mark:

``` js
    const { csr, 
      ...paramsNeedtoMemo } = req.query || {}
    
    const needCrs = csr === 'true' || process.env.MODE === 'csr'
```

Then use it:

``` js

    const route = needCrs ? {} : await UniversalRouter.resolve(routes, {
      ...context,
      pathName: req.path,
      path: req.path,
      query: req.query,
      cookie: cookieStr,
      useragent: (req.headers['user-agent'] && req.headers['user-agent'].toLowerCase()) || '',
      curUrl, 
    });

    if (route.redirect) {
      res.redirect(route.status || 302, route.redirect);
      return;
    }

    const data = { ...route };
    data.children = needCrs ? null : ReactDOM.renderToString(<App context={context}>{route.component}</App>);
    data.chunk = needCrs ? null : assets[route.chunk] && assets[route.chunk].js;
```

So CSR is ready.

We have used this in the production environment, can you see if there is any problem?

You can visit `https://ke.study.163.com/wap/course/detail/100082827?Pdt=ydkWeb&inLoc=web_sy_msgkk&csr=true` in mobile mode and compare with `https://ke.study.163.com/wap/course/detail/100082827?Pdt=ydkWeb&inLoc=web_sy_msgkk`.

**Comment by ulani** [comment]
@brizer   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
