### ISSUE TITLE
Is there jsx support in VS2015?

### ISSUE THREAD

**Issue by alexro** [kriasoft/react-starter-kit#195]
I set up VS2015 and then added the react-starter-kit template.
But when I open a jsx file the editor complains about its syntax.
##

**Comment by cmnstmntmn** [comment]
same here

**Comment by vladikoff** [comment]
This issue seems unrelated to the starter kit, maybe better on stackoverflow?

**Comment by cmnstmntmn** [comment]
is supported now. see new [features](https://code.visualstudio.com/updates)

**Comment by AmitMY** [comment]
@alexro Please revisit this issue, and close it if necessary. It seems to be fixed

**Comment by KraigWalker** [comment]
VS2015 !== VSCode

**Comment by ulani** [comment]
@alexro   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
