### ISSUE TITLE
Hot Reload not working properly 

### ISSUE THREAD

**Issue by Sadam-MCA** [kriasoft/react-starter-kit#1989]

**Comment by koistya** [comment]
@Sadam-MCA I can only reproduce it if I try using anonymous functions when declaring React components:

```tsx
// GOOD
export function Example(): JSX.Element {
  return <Box>...</Box>;
}

-- vs --

// BAD
export const Example = (): JSX.Element => {
  return <Box>...</Box>;
};
```

If you're using anonymous function, consider giving them names, otherwise you may bump into issues like this one. This particular issue is not related to the starter kit but React Refresh limitations I believe. Feel free to re-open this issue if Hot Reload (React Refresh) is not working under some other condition.
