### ISSUE TITLE
Use react-router

### ISSUE THREAD

**Issue by jakecraige** [kriasoft/react-starter-kit#20]
How do you feel about using [react-router](https://github.com/rackt/react-router) instead of a custom basic routing approach? It seems to be getting super popular and the fact that it's build for react makes me like it a lot more anyways

**Comment by sdiaz** [comment]
Both are isomorphic, but I guess attaching to a formal react based router is a good choice

+1 to react-router

**Comment by radum** [comment]
I on the same page with @koistya we shouldn't JSXify everything now, just because we can.

**Comment by goatslacker** [comment]
Another +1 for react router. It seems like this is becoming the de-facto router to use with react and building isomorphic applications with it is quite trivial.

I actually have an [example here](https://github.com/goatslacker/iso/tree/master/examples/react-router-flux) that shows how you're able to build isomorphic applications using react-router and flux.

**Comment by majodev** [comment]
+1

**Comment by markopavlovic** [comment]
+1

**Comment by patrickng** [comment]
Has anyone successfully gotten this to work on their own project/fork? Would love to see the implementation details. I've only encountered errors trying to integrate it in.

**Comment by the4dpatrick** [comment]
+ 1 for seeing a fork with react-router implemented

**Comment by timdoes** [comment]
+1

**Comment by latifs** [comment]
+1

**Comment by aleksichen** [comment]
+1 to react-router

**Comment by soulmachine** [comment]
+1 for react-router

**Comment by luqin** [comment]
+1 for react-router

**Comment by abachuk** [comment]
+1

**Comment by 9mm** [comment]
Yeah I'd really like to see an example

**Comment by palmdeezy** [comment]
+1

**Comment by KirillSuhodolov** [comment]
+1 for react-router

**Comment by andrei-sheina** [comment]
+1 to react router please

**Comment by MathieuCh** [comment]
+1

**Comment by arkeros** [comment]
+1 to react-router, it's the de facto standard router for react.

**Comment by koistya** [comment]
After ff5016fd2f52ae9d852d7ebf640ce108f05342b7, it might be easier to integrate React Router. The `src/routes/index.js` file contains the list of all appliaction routes, where each route has these properties:

* `path` - a string or regular expression, e.g. `/posts/:id` (see [path-to-regexp](https://github.com/pillarjs/path-to-regexp), [route tester](http://forbeslindesay.github.io/express-route-tester/))
* `action` - a route handler that accepts `context` as its first argument, it can return a Promise
* `children` - optional parameter with an array of child routes

For example:

```js
{
  path: '/admin',               // www.example.com/admin
  action() { ... },
  children: [
    {
      path: '/users',           // www.example.com/admin/users
      children: [
        {
           path: '/',           // www.example.com/admin/users
           action() { ... },
        },
        {
           path: '/:id',        // www.example.com/admin/users/123
           action() { ... },
        },
      ]
    }
  ]
}
```

An action method may look something like this:

```
{
  path: '/users/:username',
  async action({ render, params }) {
    const resp = await fetch(`/api/users/${params.username}`);
    const data = await resp.json();
    if (!data) return undefined;
    return render(<UserProfile {...data} />);
  }
}
```

If action method returns `undefined`, the router will keep traversing the route tree until it finds the first route that matches the provided URL path string and returns anything other than `undefined`.

---

In order to make it work with React Router, (1) the `action` property must be replaced with either `component` or `getComponent`, (2) the `children` property must be renamed to `childRoutes`, (3) the `path` values shouldn't start with `/` and follow React Router convention, (4) the `match` method inside `src/client.js` and `src/server.js` should be replaced with React Router's `match` method.

**Comment by stupidisum** [comment]
How to handle with the context thing here?
react-router's match doesn't process context for us

**Comment by koistya** [comment]
@stupidisum you can set context in the top-level React component, for example, with React Router it would be: `const routes = { path: '/', component: App, childRoutes: [/* all the other routes */] }`, where the `App` component sets the required context vars (e.g. Flux/Redux/Relay store etc.).

BTW, the routing boilerplate is going to be removed from server.js and client.js. See PR #613.

**Comment by dhyegofernando** [comment]
👍

**Comment by rkait** [comment]
+1 for a forked example with `react-router`!

**Comment by langpavel** [comment]
@rkait can you point us to fork with react-router in new issue or better PR?

**Comment by rkait** [comment]
@langpavel I am trying to implementing something similar to their previous PR in my own project that uses RSK. There are still a few issues, so if anyone else has implemented something more formal that would be very helpful as an example.

**Comment by koistya** [comment]
FYI, you can find *some* of the issues with React Router v2-3 in the official docs:

![image](https://cloud.githubusercontent.com/assets/197134/18633293/443452b8-7e84-11e6-8e8e-11ba821a6870.png)

https://github.com/ReactTraining/react-router/tree/v4

The next version of RR has a completely different API, check it out. Yet, there is no guarantee that RR v4 will not be rewritten into something different in a few months from now.

**Comment by langpavel** [comment]
@koistya it looks like they are teaches a lot.. RR4 is awesome I think but I didn't tested it. If asynchronous routes, code splitting and other things will work seamlessly after they become stable, RR will be best choice :-)

**Comment by koistya** [comment]
@langpavel it seems like RR4 doesn't work well with Relay, and there is not a word about async data loading and code-splitting in their docs yet.

**Comment by ryanbelke** [comment]
what is the status of implementing react-router?
