### ISSUE TITLE
src/templates/index.html is not being watched/reloaded

### ISSUE THREAD

**Issue by andrewkolesnikov** [kriasoft/react-starter-kit#209]
Apparently src/templates/index.html is not being watched/reloaded. Maybe a way to auto-reload this too needs to be added?
##

**Comment by HarryHong** [comment]
you can modify it
under tools/copy.js


const watcher = await watch('src/templates/**/*.*');
    watcher.on('changed', async (file) => {
      const relPath = file.substr(path.join(__dirname, '../src/templates/').length);
      await copy(`src/templates/${relPath}`, `build/public/${relPath}`);
    });

something like this

**Comment by ulani** [comment]
@andrewkolesnikov   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
