### ISSUE TITLE
Where is server boilerplate?

### ISSUE THREAD

**Issue by vko-online** [kriasoft/react-starter-kit#210]
I'm new to here, and i have some questions. 
Where's server-side controllers/db/models etc or this is only front-end stuff?
Is this plays nice with Sails.JS?

**Comment by koistya** [comment]
There is an example of REST API endpoint located in `src/api` folder + there is server-side code in `server.js` which is responsible for launching Express server and server-side rendering. You can either add more stuff to `src/api` to implement RESTful API for your needs using Node.js/Express, or you can build API part using another other stack and make your React app use an existing RESTful API instead (e.g. `api.example.com` rather than `example.com/api/`).

**Comment by vko-online** [comment]
Why this stack doesn't use React Material Design (http://material-ui.com)?
They fit together thought
Indeed i couldn't combine them, issued there https://github.com/callemall/material-ui/issues/1428

**Comment by koistya** [comment]
I'm not sure if `material-ui` does work with React 0.14 yet.. but yeah, we can create at least a separate branch with `material-ui` integration.

**Comment by rodolfo2488** [comment]
there is a [material-ui-io](https://github.com/juhaelee/material-ui-io) that is a PoC for .14 that works with this starter kit just fine. You only need to make some changes for the Server rendering styles because it finds a difference between the client and server DOM and renders it again, so basically you lose the goodness of the server rendering.

**Comment by vko-online** [comment]
@rodolfo2488 can you elaborate more on that "make some changes" please

**Comment by rodolfo2488** [comment]
Sorry for that. What I mean by that is Material-UI does not use React Styles or the inline styles that is the new approach react programmers are using. You can, delete the inline styles from this project or ( what I am trying to do ) incorporate Material-UI with inline-styles. Other changes are easy and are explained in the example of the project of material-ui.

**Comment by vko-online** [comment]
Please help with this question http://stackoverflow.com/questions/32331303/react-starter-kit-api-demo
