### ISSUE TITLE
What was the reason to remove gulp impl.? 

### ISSUE THREAD

**Issue by eriknyk** [kriasoft/react-starter-kit#211]
Hi,
Can you tell me what was the reason to remove gulp impl.?

Regards
##

**Comment by constantx** [comment]
curious to hear this as well (though I'm a `grunt` fan)

**Comment by nodegin** [comment]
since webpack did the optimize stuff, so it's removed to reduce extra
dependencies

**Comment by ulani** [comment]
@eriknyk   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
