### ISSUE TITLE
Include Vagrantfile to the project

### ISSUE THREAD

**Issue by sreym** [kriasoft/react-starter-kit#212]
I think it would be nice for starter kit to have already configured Vagrantfile. I did maybe beginner version for this. I'm not sure of this task for all users of react-starter-kit so I've created this issue for discussion.

Here is Vagrantfile

``` ruby
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty32"
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 3001, host: 3001
  config.vm.network "forwarded_port", guest: 5000, host: 5000

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo locale-gen UTF-8
    curl -sL https://deb.nodesource.com/setup_0.12 | sudo -E bash -
    sudo apt-get install -y nodejs
    sudo apt-get -y install g++
    sudo npm install -g gulp
    echo "cd /vagrant" >> .bashrc
  SHELL
end
```
##

**Comment by ulani** [comment]
@sreym   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
