### ISSUE TITLE
Configure jade to be able to use 'include'

### ISSUE THREAD

**Issue by boosh** [kriasoft/react-starter-kit#218]
When I try to use `include` in a template (see `http://jade-lang.com/reference/includes/`), I get an error saying jade needs configuring with the `filename` option to support this. I've tried adding it in `src/server.js` but I couldn't get it working. It would be great if you could add it so that we can put template fragments in subdirectories of the `content` directory.
##

**Comment by ulani** [comment]
@boosh   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
