### ISSUE TITLE
webpack config..missing?

### ISSUE THREAD

**Issue by raptoria** [kriasoft/react-starter-kit#221]
Hi..I can't seem to find the webpack config.js. Was it removed on purpose?
thanks!!
##

**Comment by koistya** [comment]
@raptoria the `webpack.config.js` has been moved to `tools/config.js` in order to keep the root directory clean, and to have this file closer to the build scripts which actual use it.

**Comment by ulani** [comment]
@raptoria   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
