### ISSUE TITLE
Multi domain routing

### ISSUE THREAD

**Issue by vitaminwater** [kriasoft/react-starter-kit#227]
Does the router implement multi-domain routing ?

for example: `foo.com*` in the route definition.
##

**Comment by koistya** [comment]
@vitaminwater you want to be able redirect users from one domain to another (or a sub-domain) by using client-side redirect, without full page refresh? HTML History API doesn't support it (it's by design). See:

https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Manipulating_the_browser_history#The_pushState()_method

**Comment by vitaminwater** [comment]
I have multiple version of a same site, so instead of doing subdirectories for each versions, I'd like to have `version1.site.com` `version2.site.com` etc..

and then it would only the right homepage, as if I was doing '/version1', '/version2' etc..

**Comment by valeeum** [comment]
@vitaminwater did you ever get this working?

**Comment by ulani** [comment]
@vitaminwater    thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
