### ISSUE TITLE
ie8 throw error 

### ISSUE THREAD

**Issue by shawon1220** [kriasoft/react-starter-kit#229]
hi,when i use it ie8,thorw error:

Unhandled promise rejection TypeError: Object does not support the "next" property or method.

it's looked from react-routing error
##

**Comment by nodegin** [comment]
you should open issue at Microsoft instead of here

**Comment by koistya** [comment]
I will check in IE8, maybe there is a quick fix for that issue..

**Comment by f0def** [comment]
Same error `Unhandled promise rejectionTypeError`

**Comment by ulani** [comment]
@shawon1220   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
