### ISSUE TITLE
Lack of server error stack traces in terminal

### ISSUE THREAD

**Issue by ademuk** [kriasoft/react-starter-kit#246]
I'm not getting any server errors in the terminal where I launch `npm start`. Despite `DEBUG=true` and `NODE_ENV=development`.

I believe this is because the `server.js` is started in a forked process. I've added the following to `serve.js` for now.

``` javascript
server.on('message', message => {
  console.log(message);
});
```
##

**Comment by kurtmarcink** [comment]
`process.stdout.write()`?

**Comment by ulani** [comment]
@ademuk   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
