### ISSUE TITLE
Resolving non-relative require paths in server build

### ISSUE THREAD

**Issue by mbixby** [kriasoft/react-starter-kit#249]
When I tried to use non-relative require paths, e.g. `import withStyles from 'decorators/withStyles'` instead of `'../../decorators/withStyles'`, they didn't work in the server build. The Webpack config (`serverConfig.externals` property) specifies that all files matching `/^[a-z][a-z\/\.\-0-9]*$/i` (excl. `react-routing`) should be resolved by Node instead of Webpack.

I replaced the definition with the following to get it working:

``` javascript
serverConfig = { ... externals: fs.readdirSync("node_modules"), ... }
```

[Source](https://github.com/webpack/webpack/issues/603#issuecomment-65316834) ("commonjs" prefix is apparently not needed in latest Webpack)
##

**Comment by ericclemmons** [comment]
Thank you for posting this!  You just saved my day.

**Comment by ulani** [comment]
@mbixby   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
