### ISSUE TITLE
Several questions for this kit

### ISSUE THREAD

**Issue by vko-online** [kriasoft/react-starter-kit#250]
I really like this kit but 
I have several questions based on this repo. 
- Any component/action/store/api example?
- Why `npm start` is not watching js change (why it only watches `src/content` dir), and why it's also takes too long time to compile (i mean really long, 10-30sec)?
- Should i `extend React.Component` class when creating custom component? (This is described in [docs/style-guide](https://github.com/kriasoft/react-starter-kit/blob/master/docs/react-style-guide.md#react-component-example), but actual [TextBox](https://github.com/kriasoft/react-starter-kit/blob/master/src/components/TextBox/TextBox.js) component is not extending react)
- [CSS styling](https://github.com/kriasoft/react-starter-kit/blob/master/docs/react-style-guide.md#css-styling-example) is not correct, it's CSS not SCSS/SASS/LESS, or <s>any_unknown_thing</s> webpack will preprocessor it anyway, if so, why not use `.scss` file extentions?
- Where is actual docs, is it just ES6_docs + React_docs?
- Are you considering to make component generator?
- <s>This kit for making react-components or react-website?</s> Surprisingly it's react-website

Any demo with this kit would be awesome.
I'm just not catching things up, there is too much going on imo, react + ES6 + webpack + secret_stuff, it has 46 dependencies (not bower deps), just for front-end stuff, and they must be compiled into app.js - isn't that too much?

Any blogpost about this kit would be also awesome
Regards

<sup>P.S. This issue was githubed, gittered, twittered, i'm just really struggling with this kit, although i like the way it's built</sup>
##

**Comment by koistya** [comment]
Regarding the `app.js` bundle.. As of now, only the following `npm` modules are getting bundled into the client-side `.js` file: `classnames`, `eventemitter3`, `fastclick`, `fbjs`, `flux`, `history`, `normalize.css`, `react`, `react-dom`, `react-routing`, `superagent`.

P.S.: Will try to answer other questions later.

**Comment by chentaixu** [comment]
I was a complete noob on front end stuff like ... a month ago? Then I met this kit. It took me *a while* to digest. I learned Webpack, Reactjs ES6+, Babel, Postcss, isomorphic webapp etc, etc... I examined the source code line by line and tried reasoning about the logic behind each lines of code. All I got to say is that it's beautiful. I came across multiple medium posts about a wide range of topics pertaining to the philosophy used in this kit and I'm amazed by koistya on picking up the coolest concepts.

I really, really like the @withStyles decorator came up by koistya. I am currently trying to merge semantic-ui into this kit through @withStyles so that the css is completely separated from the react component. I think I would find some time to post a blog about this kit soon™.

**Comment by MattReimer** [comment]
I'm with @vko-online on this. I'm currently going through it and I would love to see some more docs and especially examples of really simple use-cases for custom components etc. It's like in language how words don't make sense until you hear them in a sentence.

All of this seems really well thought-out and I'm really trying hard to understand by going slowly through it. Now and then things like the `extend React.Component ` question completely stop me in my tracks.

**Comment by vko-online** [comment]
@koistya Still open :-)
```bash
                            __                     __                    __                          __          __      
                           /\ \__                 /\ \__                /\ \__                      /\ \      __/\ \__   
 _ __    __     __      ___\ \ ,_\            ____\ \ ,_\    __     _ __\ \ ,_\    __   _ __        \ \ \/'\ /\_\ \ ,_\  
/\`'__\/'__`\ /'__`\   /'___\ \ \/  _______  /',__\\ \ \/  /'__`\  /\`'__\ \ \/  /'__`\/\`'__\_______\ \ , < \/\ \ \ \/  
\ \ \//\  __//\ \L\.\_/\ \__/\ \ \_/\______\/\__, `\\ \ \_/\ \L\.\_\ \ \/ \ \ \_/\  __/\ \ \//\______\\ \ \\`\\ \ \ \ \_ 
 \ \_\\ \____\ \__/.\_\ \____\\ \__\/______/\/\____/ \ \__\ \__/.\_\\ \_\  \ \__\ \____\\ \_\\/______/ \ \_\ \_\ \_\ \__\
  \/_/ \/____/\/__/\/_/\/____/ \/__/         \/___/   \/__/\/__/\/_/ \/_/   \/__/\/____/ \/_/           \/_/\/_/\/_/\/__/
```

**Comment by pertrai1** [comment]
@koistya I am a noob as well and trying to understand how webpack is involved with this starter? Most projects I have looked into the last several weeks have a webpack config but I don't see one with this. Thank you for any help you can share.

**Comment by koistya** [comment]
@pertrai1 the Webpack config is located in `tools/config.js` (closer to the place where it's actually used).

**Comment by koistya** [comment]
@vko-online when you run `npm start` it should fire up a development server (`build/server.js` + [BrowserSync](http://browsersync.io/) proxy with React Hot Reload on top of it) and start watching for modifications in source files. If this doesn't happen, please file an issue. The initial compile time might be ~30s which is considered to be normal, but right after that, while you edit the source files, incremental updates should take less than a second.

Starting from React 0.14.0-rc1 your components must extend React.Component base class.

Regarding the `.scss` file extension, that might be a good idea! I'm already using this approach in [react-static-boilerplate](https://github.com/koistya/react-static-boilerplate).

I need to add Yeoman component generator into the **generator-react-fullstack**, need help with that.

Here is an example of REST API endpoint if you need one: https://gist.github.com/koistya/78a950371d2a10b550be

**Comment by vko-online** [comment]
@koistya Thanks, that now makes sense.
Also i would like to hear something about Flux
RSK doesn't have any samples
I could write my own flux implementation, but still want to stick with RSK conventions.

**Comment by popyachts** [comment]
@koistya I'm new to the React Starter Kit.  Loving what I see and definitely looking forward to dissecting each line to understand more about the RSK, Node and its components.

I am having some difficulty adding a custom CSS file.  I have added a public/css folder and placed a file (main.css) in it.  I have added the following simple line to the Html.js file:

<link rel="stylesheet" href="/css/main.css"/>

I modified the copy.js file to the best of my ability, but that basically involved adding new folder instructions under await Promise.all([]).

I know I've missed something important because the new css folder is not being created in /build/public/ and it is obviously not receiving the main.css file.

Is the problem in copy.js?

**Comment by koistya** [comment]
@popyachts the `tools/copy.js` script is configured to copy all the files from the `src/public` folder, to `build/public`, take a look here: https://github.com/kriasoft/react-starter-kit/blob/master/tools/copy.js#L23

**Comment by koistya** [comment]
@vko-online you can try to create a PRO with `docs/recipes/flux.md` with some Flux examples, and I will fix that if there are any issues. You can find some Flux examples [here](https://github.com/facebook/flux/tree/master/examples).

**Comment by Harris-Liu** [comment]
@koistya I'm new to the React Starter Kit, loving it design, it's cool, but I notice that after do the 'npm run build' without add any new feature, the file size of  'main.js'  is more than 3.5 MB, looks little big, any way can compress it?

**Comment by frenzzy** [comment]
@Harris-Liu just [compile app](https://github.com/kriasoft/react-starter-kit/tree/master/tools#build-automation-tools) in release mode:
```shell
$ npm run build -- --release   # Build the app in production mode
$ node build/server.js         # Lunch application
```

**Comment by ulani** [comment]
@vko-online   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
