### ISSUE TITLE
Deploy to firebase

### ISSUE THREAD

**Issue by ronlobo** [kriasoft/react-starter-kit#251]
Hey there,

just want to ask if there are any plans on making the react starter kit deployable to firebase?

https://www.firebase.com/docs/web/libraries/react/ works pretty well
##

**Comment by jhabdas** [comment]
I think I saw the maintainers of this kit make note of removing flux stuff due to "overhead" (I'm assuming cognitive overhead). The problem I saw with ReactFire is that it's a Mixin and there's no method to make it play with ES6 classes [at the moment](https://github.com/firebase/reactfire/issues/38). That doesn't mean you can't use Firebase with something like Flux, though I'd personally prefer to see the folks at Firebase and the surrounding community create an adapter for Relay once it's more mature.

As for magic deployment buttons, why?

**Comment by itwasmattgregg** [comment]
There is a newer reactfire-exque repo called [re-base](https://github.com/tylermcginnis/re-base) that works pretty well. You should be able to deploy to firebase with the firebase CLI.

**Comment by jhabdas** [comment]
WTF is up with that BountySource link in the OP. Looks like spam.

**Comment by zomars** [comment]
I think what @ronlobo means is that if there's a way to deploy to the firebase "Hosting" right? I've used re-base before but that only server for consuming the real-time database. Correct me if I'm wrong. I also would like to know if I can use Firebase Hosting with this repo.

**Comment by jhabdas** [comment]
Just spoke with a React dev with over a year of Firebase experience and he said React apps yes, isomorphic apps "totally not".

**Comment by langpavel** [comment]
Ugh, guys, sorry, what is this about? Firebase will not provide node hosting, so this can be close as **no**, no at all with all benefits. There are another kriasoft projects which can be hosted on firebase but this RSK is isomorphics which needs server by definition :rofl:
