### ISSUE TITLE
history entries not rendering

### ISSUE THREAD

**Issue by aayler** [kriasoft/react-starter-kit#258]
Hello, I'm noticing that entries pushed to the history stack using Location.pushState({}, URL) are not being rendered on popstate events.

In my instance, I'm including the Location.pushState() in a click handler that is part of a content slider with back and forward navigation buttons. On hitting back or forward, the URL is updating but the 'page' is not rendering to its previous state.

Any help would be very much appreciated!
##

**Comment by ulani** [comment]
@aayler   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
