### ISSUE TITLE
Export client-only version

### ISSUE THREAD

**Issue by DVLP** [kriasoft/react-starter-kit#260]
This is the most complete react template and I love it but it can only be deployed to a node server. How to build a client-only version which would run with any basic http server or even on github in gh-pages branch?
##

**Comment by koistya** [comment]
You may want to use a similar template but optimized for hosting in CDN: [React Static Boilerplate](https://github.com/koistya/react-static-boilerplate)

**Comment by tomasen** [comment]
@koistya :

Is it unpractical for proposing add build flags like `npm build -- static` to current stack, by adding static-site-generator-webpack-plugin to current automation scripts in /tools/, so that we can have both options of hosting react by node server and static?

If it shouldn't be done, can you explain why?

**Comment by codeorelse** [comment]
I would also love this!

**Comment by fusepilot** [comment]
@koistya I'm also curious why this warrants another repo since this seems to get 95% of the job done.

**Comment by okendoken** [comment]
:+1: It would be great to be able to use RSK as SPA with other backends like Rails, Java, not just node.

Initial description of this project is probably a bit misleading - you'd rather name it react-node-starter-kit

Thanks

**Comment by Jeger** [comment]
There are several cases where you would want both isomorphic and client side builds available.

Is this trivial to add?

**Comment by koistya** [comment]
@okendoken I know many folks who are using Ruby, .NET, PHP, Go etc. on the backend, still have Node.js in their setup just for server-side rendering of the React app. This project fits well in this scenario since there is very little server-side code.

**Comment by koistya** [comment]
@Jeger It shouldn't be that hard I think, I was going to add `--static` option for build scripts, which would build only the client-side portion of the app, ready to be deployed to a static site host provider (GitHub Pages, Amazon S3 etc.).

**Comment by josetesan** [comment]
I'd love that feature, as we are trying not to use node as a backend server, but java.
:+1:

**Comment by codeorelse** [comment]
That'd be awesome, @koistya!

**Comment by Jeger** [comment]
@koistya that solution would be perfect as far as I'm concerned. And as an added bonus it would widen the group of target users a lot for this project.

While doing some research for starter kits and boilerplates, this is by far the most starred, forked and active repo. The static alternatives are a lot less mature and active.

**Comment by brunogarcia** [comment]
:+1:

**Comment by Bogdaan** [comment]
:-1: Сompletely agree with @koistya - there is no place for "client only".

**Comment by Kobzol** [comment]
The --static flag generates the .html files correctly, but when I try to launch the built application (with web root set to build/public), it can't find `/graphql` (it returns 404). Is there anything else that has to be done apart from `npm run build -- --static`? When I run the application with node build/server.js, it works correctly.

**Comment by fchienvuhoang** [comment]
Are you using nginx like a server?
you need set Web root to build folder, and update js path:
module.exports = {"main":{"js":"/assets/main.js?8fe4a260b4b2033ace9d"}}; 
-> 
module.exports = {"main":{"js":"/public/assets/main.js?8fe4a260b4b2033ace9d"}};

**Comment by Kobzol** [comment]
I'm currently using lite-server (from npm), but it would be nice if the app could be exported to a single directory that would be usable as a root and could be ran with any web-server. 

I changed the webpack config to point to `/public/assets` instead of `/assets.` When I set the root to `/build,` there's no index.html there and I have to access the files through the `/public` URL prefix, but even then the error with missing `/graphql` stays the same.

**Comment by ulani** [comment]
@DVLP   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
