### ISSUE TITLE
After Building Application

### ISSUE THREAD

**Issue by 0zguner** [kriasoft/react-starter-kit#266]
After building applications 31892 lines of code for client side, 3253 lines of code for server side generated. Is this normal ?
##

**Comment by ulani** [comment]
@0zguner   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
