### ISSUE TITLE
Identifier name '_' is too short lint error on clean checkout

### ISSUE THREAD

**Issue by stevenyxu** [kriasoft/react-starter-kit#270]
I cloned master tonight and ran npm install; npm test. Getting the following error:

```
$ npm test

> @ test $PWD
> eslint src && jest


$PWD/src/app.js
  31:27  error  Identifier name '_' is too short. (< 2)  id-length

✖ 1 problem (1 error, 0 warnings)

npm ERR! Test failed.  See above for more details.
```

Just wanted to flag it since I'm not familiar with the linter settings. If I have a fix I can share more widely, I'll submit a PR but I wanted to bring this up here.
##

**Comment by IgorMing** [comment]
Hi @cairo140,
Please, just add in your eslintrc.js file the following code

`"id-length": ["error", { "exceptions": ["_"] }]`

This lint rule accepts it, and now, you are able to import lodash/underscore without problems.

**Comment by ulani** [comment]
@stevenyxu   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
