### ISSUE TITLE
CSS Modules and BrowserSync

### ISSUE THREAD

**Issue by fingermark** [kriasoft/react-starter-kit#274]
@koistya I'm trying to get CSS Modules working with BrowserSync in a fork of your starter kit:  https://github.com/fingermark/react-starter-kit/commit/79458ee4ef108d5440bb8019117939d15a594c03

The problem I'm having is with BrowserSync picking up the changes, so I had to make use of `module.hot` detection.  First, I'm not sure if that's correct.  Second, after you make the change and the browser picks it up, it won't "stick" after you navigate away and come back.  I don't understand your use of `style-loader`'s `use` and `unuse` to proceed.

Any ideas how I can fix this.  Also, keeping this around in case anyone else is interested in CSS Modules.

Note that I only applied this to the ContactPage.
##

**Comment by fingermark** [comment]
It looks like the issue is not specific to the CSS Modules addition I made, but is like that with the current react-starter-kit version.

If I make a CSS update.  BrowserSync will apply the change.  Once I navigate away and come back (through link clicking), I get the old CSS.

Should probably open this up in a separate ticket.  Let me know if that's necessary

**Comment by koistya** [comment]
Yep, I guess we need to add `module.hot.accept` into the `@withStyle` decorator to handle this issue.

**Comment by ulani** [comment]
@fingermark  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
