### ISSUE TITLE
not working examples

### ISSUE THREAD

**Issue by jakubwolny** [kriasoft/react-starter-kit#283]
I tried:
- demo page http://demo.reactstarterkit.com/contact
- master branch
- 4.0 version

on Chrome and Firefox but the only working page is /about in all the other I can see only 3 dots. No error in the console but I think something is definitely wrong.
##

**Comment by maysale01** [comment]
The starter kit doesn't include any content for those pages, check the directory `src/content`. Starter Kit is working as intended.

**Comment by Kepro** [comment]
@hamczu  you can see that dots here ;) 
https://github.com/kriasoft/react-starter-kit/blob/6ab134bd013e16a99233eaa6ec2b6f4f026b9799/src/components/ContactPage/ContactPage.js

**Comment by ulani** [comment]
@jakubwolny   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
