### ISSUE TITLE
Please include 'hello, world' page

### ISSUE THREAD

**Issue by remoteportal** [kriasoft/react-starter-kit#288]
I have NO idea how to get to get to bat, let alone first base.

Perhaps tailor an index.html file for this setup based off this page?
https://facebook.github.io/react/docs/getting-started.html
##

**Comment by maysale01** [comment]
The directory structure outlines a general overview of how the starter kit is organized. Generally the first thing to do when looking at a project is to look at `package.json` and see where the entry points are. Under `"scripts"` you'll notice that start corresponds to `tools/start.js`. This is the main entry point for running a dev server. It will kick build and bundle the application into `build` directory, run a child process to start `src/server.js` and run a Browser Sync server proxy.

**Comment by ulani** [comment]
@remoteportal   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
