### ISSUE TITLE
How to use externals to include external CDN based lib?

### ISSUE THREAD

**Issue by jma7889** [kriasoft/react-starter-kit#290]
It is not an issue, just don't know how to do it. No index.html or any html to edit, all js files. My question is if I want to load a vendor js lib from cloud, how to do I do that?

It would be easy to do that in a html file. <script src="https://forio.com/tools/js-libs/1.5.0/epicenter.min.js"></script>

However, in js file, it only uses npm installed packages. How can I import the above lib with no html file? I tried import and require, they only work for local files.
##

**Comment by codeorelse** [comment]
You should be able to add these external refs in src/components/Html/Html.js.

**Comment by jma7889** [comment]
Yes, it works now using Html.js

**Comment by ProtoJazz** [comment]
I know this is old, but what is the best way to do this? 
Ive got a cdn based version of jquery I need to bring in

Everything Ive tried to so far gives " ReferenceError: document is not defined"

**Comment by ulani** [comment]
@jma7889   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
