### ISSUE TITLE
Not supported on windows due to Node-gyp dependency 

### ISSUE THREAD

**Issue by YarivGilad** [kriasoft/react-starter-kit#293]
Node-gyp nightmare continues.
Not supported on Windows.
This starter kit includes webpack-dev-server which has a node-gyp dependency which blows up the whole installation process.
node-gyp is an unnecessary evil and embarrassing approach all together.
It is meant to build c++ code with a native compiler on the native OS the project runs in.
Just build the damn binaries and spare us web developers the need to compile c++ and debug it when it doesn't work or download almost 2 gigs of tools and compilers we shouldn't deal with.
Someone somewhere needs to understand that it is arrogant to expect every developer to use an apple or Linux machine.  
##

**Comment by bauerj** [comment]
I agree that it is a bit odd to make users install Python and Visual Studio (or Xcode for that matter) in order to use your starter-kit to develop a JS app. Is this really necessary?

**Comment by koistya** [comment]
As far as I understand, only `jest-cli`, `webkack-dev-middleware` and `browsers-sync` depend on `node-gyp`... you can strip them off from the project. But, isn't it simpler just to install `Python` and a free minimum version of `Visual Studio` to make `node-gyp` happy? If you're developing a Node.js app on Windows, that what you will probably need to do anyway regardless of what boilerplate you're using.

https://github.com/nodejs/node-gyp#installation

**Comment by bauerj** [comment]
Okay, just wanted to make sure, that this is the way to go.

Thanks for the response :+1:

**Comment by Ajar-Ajar** [comment]
Hey @koistya 
I guess you're a mac user ha? 
while it is nice to reference the installation instructions of node-gyp, in the real world the majority of js developers working on windows will not be able to make this crappy workflow to work.
it is not your fault or any of the libraries you use.
It is due to Joynet thinking it is A OKAY to let web developers deal with compiling c++ code instead of having those libraries that need compiled binaries provide those themselves. 
Instead - to have any web-developer install via npm and when node-gyp blows up (which it does!) be stuck in this nightmare again - that is a very bad design and a very bad experience.
I am to say I spent who knows how many days to download and install Visual Studio, windows sdk, service packes, make sure everything is in the bloody PATH yadda yadda yadda... still - guess what - it does not work no matter what the node-gyp installation instructions have to say.
So thank you for being so kind to reference this link, but don't kid yourself that it solves anything.
Simpler? you know nothing John Snow!!!
:)

**Comment by koistya** [comment]
@Ajar-Ajar I'm a Windows user as well. Maybe, if you can share your screen, I'll be able to see what's wrong with your `node-gyp` setup..

**Comment by Ajar-Ajar** [comment]
I'm not getting into this vortex again thank you. I'll wait it out until they fix it.
https://github.com/nodejs/node-gyp/issues/784#issuecomment-150546667

**Comment by garfieldnate** [comment]
I don't see webpack-dev-server in the dependencies, but this is still not working on Windows (#759).

**Comment by frenzzy** [comment]
@garfieldnate RSK uses patched version of [webpack-dev-server](https://github.com/webpack/webpack-dev-server) to make server hot reloadable.
See [webpack-middleware](https://github.com/kriasoft/webpack-middleware)

**Comment by ulani** [comment]
@YarivGilad   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
