### ISSUE TITLE
Can we run this in a non-node js based web server?

### ISSUE THREAD

**Issue by ghost** [kriasoft/react-starter-kit#294]
Can we run this app in a non-node js based web server?
Is there a node server dependency for the UI and routes to work?
##

**Comment by koistya** [comment]
I haven't tried, but I think it should work fine with another JavaScript engine.

**Comment by codeorelse** [comment]
I think @vineesv means using the rsk as a static package.

**Comment by ulani** [comment]
@ghost  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
