### ISSUE TITLE
best way to communicate with server

### ISSUE THREAD

**Issue by bingomanatee** [kriasoft/react-starter-kit#295]
What is the best way to communicate between the server and react? should you just have an api that the client layer reads or is there some direct way of communicating to the server in the components?
##

**Comment by MohhamedRafi** [comment]
I wondering about that too. React seems to be only V in MVC model as facebook stated.

**Comment by andrewmclagan** [comment]
There is a node/express server in this package already. You could also use an external Restful API server written in PHP, Ruby, Python... anything you want. Following the micro-service architecture.

**Comment by ulani** [comment]
@bingomanatee   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
