### ISSUE TITLE
Disable server side rendering for certain routes?

### ISSUE THREAD

**Issue by dfinzer** [kriasoft/react-starter-kit#316]
Relatively new to React, so apologies if this is a basic question. Is there any way to disable server side rendering for particular routes and have them rendered client side instead?
##

**Comment by chen844033231** [comment]
you can change the src/server.js file, the express route write use '*', you can add route before the * route. just like that:
```javascript
server.get('/hello',async (req, res) => {
	res.send('helo world');
        // or res.sendFile(....);
})

server.get('*', async (req, res, next) => {
//...
})
```

**Comment by ulani** [comment]
@dfinzer  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
