### ISSUE TITLE
Implement babel-plugin-module-alias

### ISSUE THREAD

**Issue by athomann** [kriasoft/react-starter-kit#321]
@koistya What do you think about adding babel-plugin-module-alias to this kit?  I'll create a pull request if you think its useful.  I've found it useful when I'm organizing the components folder.
https://github.com/tleunen/babel-plugin-module-alias
##

**Comment by ulani** [comment]
@athomann  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
