### ISSUE TITLE
Failed to use generator with yeoman

### ISSUE THREAD

**Issue by olemp** [kriasoft/react-starter-kit#323]
See log file

What's the issue?

[npm-debug.txt](https://github.com/kriasoft/react-starter-kit/files/36385/npm-debug.txt)
##

**Comment by ulani** [comment]
@olemp  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
