### ISSUE TITLE
Render react components server side

### ISSUE THREAD

**Issue by webchaz** [kriasoft/react-starter-kit#325]
This has been a very helpful project, however I'm not sure I understand how to render various react components.  Right now it's rendering static content from jade, any examples or tips on how to render more complicated ui that uses a number of components?

Thank you
##

**Comment by Kepro** [comment]
why you create issue? use stackoverflow...

**Comment by ulani** [comment]
@webchaz  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
