### ISSUE TITLE
How to store data?

### ISSUE THREAD

**Issue by AliceRossa** [kriasoft/react-starter-kit#334]
Hello,

I'm trying to learn React tool and I would like to develop a simple website.

I will wish to create a very simple CRUD: create, read, update and delete an article (text only). I managed to do so with Express and Mongoose but I don't know how with react starter kit.

I installed mongoose:

```
npm install --save mongoose
```

And I added in server.js

```
mongoose.connect('mongodb://localhost/react-starter-kit');
var db = mongoose.connection;
db.on('error', function () {
  throw new Error('unable to connect to database');
});
```

I created a "models" folder and I created "articleModel.js"

```
var mongoose = require('mongoose');

var schema = new mongoose.Schema({
  title : String,
  content : String
});

module.exports = articleModel = mongoose.model('articleModel', schema);
```

How to add a new article then display all articles in the database?

I recently discovered React, thank you for your help.
##

**Comment by koistya** [comment]
So far, I have an example with native MongoDb driver:

https://medium.com/@tarkus/how-to-open-database-connections-in-a-node-js-express-app-e14b2de5d1f8

**Comment by AliceRossa** [comment]
Thank you for your reply !

I tried to do something very simple, I created the user.js file in the API folder

```
import { Router } from 'express';
import { ObjectID } from 'mongodb';

const router = new Router();

router.get('/', async (req, res, next) => {
  try {
    const db = req.app.locals.db;
    const user = await db.collection('user').find();

    if (user) {
      res.send(user);
    } else {
      res.sendStatus(404);
    }
  } catch (err) {
    next(err);
  }
});

export default router;
```
In server.js file I added :
```
server.use('/api/users', require('./api/users'));
```

In route.js file I added :
```
import UsersPage from './components/UsersPage';

on('/users', async () => {
    const content = await http.get('/api/users');
    return content && <UsersPage {...content} />;
  });
```
I created the component, UsersPage.js
```
import React, { Component, PropTypes } from 'react';
import s from './UsersPage.scss';
import withStyles from '../../decorators/withStyles';

const title = 'Users';

@withStyles(s)
class UsersPage extends Component {

  static contextTypes = {
    onSetTitle: PropTypes.func.isRequired,
  };

  componentWillMount() {
    this.context.onSetTitle(title);
  }

  render() {
    return (
      <div className={s.root}>
        <div className={s.container}>
          <h1>{title}</h1>
          <div dangerouslySetInnerHTML={{ __html: this.props.content || '' }} />
        </div>
      </div>
    );
  }

}

export default UsersPage;
```
I will wish to see a list of all users by going to /users, is this the right way?

Thanks a lot for your help !

**Comment by ArdentKid** [comment]
Bump...

@koistya your example helps but is missing some things? Namely, how can we implement a mongo schema with your example?

**Comment by koistya** [comment]
@ArdentKid if you really need a schema, then `mongoose` is a way to go, I believe it should work similarly to the native MongoDb driver in terms of opening a connection, connection pooling..

**Comment by rdewolff** [comment]
Why not use Mongo in GraphQL?

Here is the nice tutorial from Kadira on GraphQL - they have a section "Using real data source" at https://learngraphql.com/basics/using-a-real-data-source. It's really showing a nice example on how to hook up MongoDB in GraphQL, using promised-mongo (https://www.npmjs.com/package/promised-mongo).

Maybe this help!

**Comment by koistya** [comment]
Currently only the authentication logic contains db access code - `src/core/passport`. PostgreSQL seems to be very popular choice of databases, especially since it does also have document storage similar to MongoDB. All user accoutns have exactly the same schema - email, password hash, registration date, the list of roles. That kind of data might be better stored in SQL tables I believe, where transactions are properly handled and data integrity is inforced out of the box.

But in additional to Postgres, I would really like to add Azure SQL Database, MongoDB, and SQLite versions of `src/core/passport`, so that RSK users may pick the appropritate implementation for their solution stack.

**Comment by phoenix377** [comment]
Hi @AliceRossa, I also have same situation and I'm new with React and Redux. Could you please let me know how you integrated MongoDB with this react starter kit?

**Comment by ulani** [comment]
@AliceRossa  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
