### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by SeanSanker** [kriasoft/react-starter-kit#336]
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/run serve

output of that command:
ReferenceError: [BABEL] /Users/mead/tog/StarterAct/tools/run.js: Unknown option: base.stage

I'm using node v5.11
##

**Comment by CocaCola183** [comment]
I got same error, and I'm on node v5.1.1 too.

I solve the problem by install babel-node -g, and then run the start script `babel-node tools/run start` manually.

**Comment by ulani** [comment]
@SeanSanker  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
