### ISSUE TITLE
Add Flow type annotations

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-starter-kit#34]
[![Flow](http://flowtype.org/static/flow-hero-logo.png)](http://flowtype.org/)
##

**Comment by langpavel** [comment]
Good point! Keeping this open

**Comment by james075** [comment]
Is this feature still in progress ? I'll be pleased to help out

**Comment by langpavel** [comment]
This is only issue.
PR is welcomed!

**Comment by ulani** [comment]
@koistya  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
