### ISSUE TITLE
How to add Zurb foundation for sites SASS framework to this starter kit?

### ISSUE THREAD

**Issue by kpnigalye** [kriasoft/react-starter-kit#351]
Based on [this article](http://blog.teamtreehouse.com/use-bootstrap-or-foundation) and some more research I decided to add Zurb Foundation to my project but I need help with the configuration. 

Please help me out!!
##

**Comment by Bogdaan** [comment]
@kpnigalye hi, have two options:
1. use global css for class names (without style-loader)
2. create component directory for this framework ) (like react-material-ui)

**Comment by driverpt** [comment]
@kpnigalye , i managed to get it working by installing node-sass and sass-loader
`npm install --save-dev node-sass sass-loader`

Rename Layout.css to Layout.scss

And finally add the import for the Foundation CSS

`@import '../../../node_modules/foundation-sites/dist/foundation.css';`

Don't forget when using the react-foundation-components to use the Global (CSS-less) version.

**Comment by ulani** [comment]
@kpnigalye  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
