### ISSUE TITLE
What about supporting react-css-modules?

### ISSUE THREAD

**Issue by nodkz** [kriasoft/react-starter-kit#364]
`react-css` is good, but `react-css-modules` provides isolated stylenames for each component. So I can use eg. `.text` classname in any component and it does not overlap each other.

I think, it is ugly to add component name to styleclass, after using `react-css-modules`.

Does this starter-kit support [react-css-modules](https://github.com/gajus/react-css-modules)? Or will do?

Working example: https://github.com/cdebotton/react-universal
##

**Comment by nodkz** [comment]
Oh I see required feature in https://github.com/kriasoft/react-starter-kit/blob/master/CHANGELOG.md
but it not released yet. 

I use 0.4.1.

**Comment by ulani** [comment]
@nodkz   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
