### ISSUE TITLE
Address client-side development in the docs

### ISSUE THREAD

**Issue by andrewkolesnikov** [kriasoft/react-starter-kit#368]
A lot of folks seem to think of react-starter-kit as a tool to build and deliver front-end components for a classic web app. E.g. #294 #260

To avoid confusion, maybe we should address this scenario in the docs?
With clarification, people should be able to decide better whether RSK is a good fit for what they're doing.
##

**Comment by ulani** [comment]
@andrewkolesnikov  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
