### ISSUE TITLE
@withViewport() produce problem TypeError: Cannot call a class as a function 

### ISSUE THREAD

**Issue by nodkz** [kriasoft/react-starter-kit#372]
Be aware with decorator `@withViewport`: it must be used without parentheses ()

Otherwise on child components it produce unclear error:

```
export default Header;
                     ^
TypeError: Cannot call a class as a function
```

On this kind of code:

``` javascript
@withViewport   <--- MUST BE without ()
@withStyles(s)
class Page extends React.Component {
  render() {
     return (
       <div>
          <Header ... />
       </div>
     );
  }
}
```
##

**Comment by Bogdaan** [comment]
this issue is overdue,
current branch does not use decorators

**Comment by ulani** [comment]
@nodkz  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
