### ISSUE TITLE
how to extends "withStyle"

### ISSUE THREAD

**Issue by nodegin** [kriasoft/react-starter-kit#379]
I try to customize the CSS class names,

change from something like: `App_container_2q4` to `A_a_2q4`

but I have no idea how the CSS works, can you explain a little about that?
##

**Comment by Kepro** [comment]
go to webpack.config.js

there are lines

````
        test: /\.scss$/,
        loaders: [
          'isomorphic-style-loader',
          'css-loader?' + (DEBUG ? 'sourceMap&' : 'minimize&') +
          'modules&localIdentName=[name]_[local]_[hash:base64:3]',
          'postcss-loader',
        ],
````

change line with modules localIdentName

**Comment by ulani** [comment]
@nodegin   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
