### ISSUE TITLE
not working on windows

### ISSUE THREAD

**Issue by zjufish** [kriasoft/react-starter-kit#383]
when i run "npm run install", i see below errors. can someone help?

$root\web\react-starter-kit\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\logger.js:41
    throw new Constructor(this._buildMessage(msg));
    ^

ReferenceError: [BABEL] $root\web\react-starter-kit\tools\run.js: Unknown option: base.stage
##

**Comment by ulani** [comment]
@zjufish   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
