### ISSUE TITLE
missing main.js

### ISSUE THREAD

**Issue by Kepro** [kriasoft/react-starter-kit#389]
if i want to use build version then missing main.js
also if i run in normal like npm start with devel mode then on 3000 port application work but on 5000 port not working, 

latest version from today
##

**Comment by Kepro** [comment]
okay, if i run npm run build -- --release --verbose then build is working
but also in dev mode  if we run npm start in root then on 3000 port is working but not working on 5000 port, then need we 5000 port or we can fix?

**Comment by Bogdaan** [comment]
@Kepro current build process create `server.js` and `build/public/main.js`
and works fine on 5000 port (by default) and run browsersync on 3000 (for connected via network devices)
Seems like you port busy, or you try to connect via network to dev server. Can you provide more information?

**Comment by dastiw1** [comment]
I also have a same problem! In windows 7 all works fine. But in Azure VPS main.js or app.js is not located at *build/public* folder.

**Comment by ulani** [comment]
@Kepro   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
