### ISSUE TITLE
Using with react-intl library for i18n cause history broken

### ISSUE THREAD

**Issue by nodegin** [kriasoft/react-starter-kit#390]
Using starter kit with react-intl 2.0 for i18n cause history broken,
any link clicked will send normal request instead of XHR,
please help!
##

**Comment by koistya** [comment]
You may want to debug `handleClick` handler inside `<Link to="/some/page">Click Me</Link>` (`Link`) component.

**Comment by nodegin** [comment]
@koistya  I checked the Link class not getting called, this might due to the react-intl use a <IntlProvider locale="en"></IntlProvider> element to wrap up the App

**Comment by nodegin** [comment]
P.S. this bug only occurs in Safari v9

**Comment by koistya** [comment]
I need to check that..

**Comment by ulani** [comment]
@nodegin   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
