### ISSUE TITLE
Which port I should use? 3000 or 5000

### ISSUE THREAD

**Issue by vishalvijay** [kriasoft/react-starter-kit#393]
When I run starter kit with `npm start`, I get below messages.

```
[11:37:56] The server is running at http://localhost:5000/
[BS] Proxying: http://localhost:5000
[BS] Access URLs:
 -----------------------------------
       Local: http://localhost:3000
    External: http://10.0.1.122:3000
 -----------------------------------
          UI: http://localhost:3001
 UI External: http://10.0.1.122:3001
 -----------------------------------
[BS] Watching files...
[11:37:56] Finished 'start' after 20047 ms
```

Now in browser, I can access my project via `http://localhost:3000` or `http://localhost:5000`.

**Which *post* I should actually use?**

Sometimes, when there is a unhanded crash, `http://localhost:3000` won't load but  `http://localhost:5000` works. (Bit confused on this)

**Comment by koistya** [comment]
At [http://localhost:5000](http://localhost:5000/) the original Node.js app (`build/server.js`) is running, and at [http://localhost:3000](http://localhost:3000/) there is just a BrowserSync proxy on top of `localhost:5000`, which injects BrowserSync and Webpack's Hot Module Replacement (HMR) scripts into the HTML. You should use the later on for testing and debugging locally.

**Comment by vishalvijay** [comment]
Ok, I got it. Thank you

**Comment by Jaikant** [comment]
I am using react-select and am observing weird behaviour which I am unable to understand. I think it is something to do with the starter kit, and not react-select component itself. Because - 

1. On an 'npm start' - It works when I connect to Access URLs (port 3001 in current build), but doesn't work when I connect to the Proxying URL (port 3000 in current build). 
2. It works fine if do a 'npm run build' followed by a 'node build/server.js'

Just confused why on an 'npm start' the select would not work when accessed through the port 3000 (the original app without browsersync)?
