### ISSUE TITLE
Problem with BEM naming convention using in component className

### ISSUE THREAD

**Issue by vishalvijay** [kriasoft/react-starter-kit#394]
Here is a sample css which is based on BEM naming convention.

```
.header {
  //some css
}
.header__ico {
    //some css
}
.header--left {
   //some css
}
```

See the portion of component render function

```
1) render = () => {
2) 	return (
3)		<div>
4)			<AComponent className={s.header}>
5)				<BComponent className={[s.header__ico, s.header--left]}>
6)					//some other code
7)				</BComponent>
8)			</AComponent>
9)		</div>
10)	);
11)}
```

In line number 5, `s.header--left` is an javascript syntax error, so I had to use it like `s["header--left"]`, **Is that how we should use it or Am I completely wrong?**

**Comment by frenzzy** [comment]
You don't need BEM specific `component__` prefix, because it is redundant with CSS Modules, please look at this:
- [CSS Modules - Welcome to the Future](http://glenmaddern.com/articles/css-modules)
- [React Starter Kit / Documentation / Use CSS Modules](https://github.com/kriasoft/react-starter-kit/blob/master/docs/react-style-guide.md#use-css-modules)

**Comment by vishalvijay** [comment]
I got it

Thanks.
