### ISSUE TITLE
How to use html instead of jade?

### ISSUE THREAD

**Issue by prakash-selvam** [kriasoft/react-starter-kit#397]
I would like to use html instead of jade and also add flux code. 
##

**Comment by xugy0926** [comment]
@prakash-selvam even if you use jade, the final jade is converted to HTML。so,  you can read html file. and send it.

```
 const source = await readFile(htmlFileName, { encoding: 'utf8' });
res.status(200).send(source);
````

**Comment by ulani** [comment]
@prakash-selvam   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
