### ISSUE TITLE
Is it react way to add background : url('image.png') into scss file ?

### ISSUE THREAD

**Issue by manodupont** [kriasoft/react-starter-kit#400]
Is it "react" best practice to add some url into scss file or we should always use some
<Image> component and deal with that instead of in Scss ?

Im having so much trouble just using this : background : url('image.png').
It never gets to load. Actually its loading for 1 second then i can see it disappearing.
Looks like the url has changed or the files is being removed while the page is loading because of webpack postcss or something ?

Thanks
##

**Comment by Bogdaan** [comment]
related with  #375

Quick fix for dev env:

     {
        test: /\.(png|jpg|jpeg|gif|svg|woff|woff2)$/,
        loader: 'url-loader?limit='+(DEBUG? 9999999: 1000),
      }

**Comment by ulani** [comment]
@manodupont   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
