### ISSUE TITLE
use react-dom-stream for server-side rendering

### ISSUE THREAD

**Issue by goldensunliu** [kriasoft/react-starter-kit#402]
`One difficulty with ReactDOM.renderToString is that it is synchronous, and it can become a performance bottleneck in server-side rendering of React sites. This is especially true of pages with larger HTML payloads, because ReactDOM.renderToString's runtime tends to scale more or less linearly with the number of virtual DOM nodes.`

react-dom-stream attempts to fix these three problems by rendering asynchronously to a stream
##

**Comment by aickin** [comment]
Hey there, I'm the author of react-dom-stream, and I think it'd be great to see react-dom-stream integrated into react-starter-kit, at least as an option.

I attempted to put together a PR, and it mostly works, but I came across an ugly problem that I think makes react-starter-kit fundamentally incompatible with streaming.

Currently in react-starter-kit, the server rendering code first renders the dynamic HTML using `renderToString`, and it passes a function on the context called `insertCss`. Any component in the render tree can use this function to add CSS to an array of CSS strings that are to be added to the page.  The output of `renderToString` is stored in a variable, and then it starts to output the page, with the CSS from the array placed in the head and the rendered HTML placed in the body.

When I converted this to streaming with react-dom-stream, the CSS disappeared, and that's because the content in the page was now being rendered in order of appearance. Unfortunately, using `insertCSS` the way that react-starter-kit does means that the entire page content has to be rendered before you know what CSS to put in the head. Or, in other words: the entire body needs to be rendered before the head can be sent out. Streaming is not possible.

It's worth noting that the page eventually looks OK, because the client-side render adds the missing CSS, but there is an ugly Flash Of Unstyled Content, which is clearly not OK.

I'll think about other ways this could be done, but it seems to me that it would require rewriting the way styles are handled.

**Comment by koistya** [comment]
@aickin yep, to make it work with `react-dom-stream` one should use the original Webpack's `style-loader` + `extract-text-webpack-plugin` that extracts all the CSS from React components into an external `.css` file. But this approach has its own cons.

**Comment by aickin** [comment]
Yeah, that's how we did it at my last job, and we found it worked really well (at least after we fixed a brutal bug in the `extract-text` plugin).

When you say "one should use...", does that mean there's a way to configure `react-starter-kit` to use `extract-text`? If so, I'd be happy to make a PR that adds `react-dom-stream` as an optional renderer for that case. If not, I'd suggest this issue should be closed as a WONTFIX; there's no way to reconcile streaming and this method of CSS generation.

**Comment by koistya** [comment]
Here is what's involved to make it work:

* replace `isomorphic-style-loader` with `extract-text-webpack-plugin` for client-side bundle (tools/webpack.config.js/clientConfig) but only for production mode, in development mode there should be `style-loader`
* remove `isomorphic-style-loader` from server-side bundle configuration (tools/webpack.config.js/serverConfig)
* remove `import withStyles from 'isomorphic-style-loader`;` line from React components
* remove `withStyles(Component, s)` HOC decorator from React components
* replace update `<style>..</style>` tag containing critical-path CSS with a reference to the output `.css` file in `src/components/Html` component

**Comment by chrisblossom** [comment]
@koistya could you please elaborate on the downsides of using the ```style-loader``` + ```extract-text-webpack-plugin``` solution?

**Comment by koistya** [comment]
@chrisblossom if you will need to extract critical path CSS to optimize server side rendering / initial load time, it will be harder to do. Also you will end up having CSS of the whole app in DOM which might degrade performance of your app (at least on slow devices).

**Comment by chrisblossom** [comment]
@koistya Thanks for the quick response. This is what react-starter-kit did prior to the isomorphic-style-loader addition, correct?

**Comment by piglovesyou** [comment]
I love to see the way react-starter-kit works with beautifully chunked CSS files instead of a single .css . Thus we may be able to achieve streaming SSR.

Let me put that my production use of react-starter-kit *did* face some performance issue because of being stuck in `renderToString`. I avoided it by increasing web server.

I've been thinking style dependencies have to be resolved statically, not in run time. I know `extract-text-webpack-plugin` is not so flexible. Maybe [extract-css-chunks-webpack-plugin](https://github.com/faceyspacey/extract-css-chunks-webpack-plugin) would be our silver bullet?

**Comment by ulani** [comment]
@goldensunliu   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
