### ISSUE TITLE
Integrate parse react errors when refreshing

### ISSUE THREAD

**Issue by hamzazar** [kriasoft/react-starter-kit#404]
What is the difference between clicking on knavigation link or refresh page? I use the starter kit example.

I integrated parse to get data in /contact page.. if I click in the link to go to page I get no problem but if I refresh I got errors . Is there difference between the two actions?
##

**Comment by Bogdaan** [comment]
Outdated.
Current branch catches and prettify errors (see https://github.com/kriasoft/react-starter-kit/blob/master/src/server.js#L114).
In old version of RSK - errors caught in `next(err)` and just send plain-text output.

**Comment by ulani** [comment]
@hamzazar   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
