### ISSUE TITLE
'Uncaught SyntaxError: Unexpected token <' when run on port 5000

### ISSUE THREAD

**Issue by vishalvijay** [kriasoft/react-starter-kit#407]
Getting `Uncaught SyntaxError: Unexpected token <` in console when run on http://localhost:5000
![screen shot 2016-01-16 at 4 49 49 pm](https://cloud.githubusercontent.com/assets/2828848/12372098/58bf0faa-bc71-11e5-9bda-ec0b3259a13d.png)
##

**Comment by dfrankland** [comment]
This issue has been brought up before: https://github.com/kriasoft/react-starter-kit/issues/370

**Comment by ulani** [comment]
@vishalvijay   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
