### ISSUE TITLE
Request: Add Authentication boilerplate as option

### ISSUE THREAD

**Issue by aleksandar-b** [kriasoft/react-starter-kit#410]
Add Authentication boilerplate as option
##

**Comment by Bogdaan** [comment]
@samosale kit perfectly works with passportjs or oauth0. Mayby withAuth decorator is usefull

**Comment by puradox** [comment]
@Bogdaan I agree, a withAuth decorator would be a nice addition :+1: 

I implemented a version of my own, but is limited by the current routing solution (react-routing) since there are no transitions (see https://github.com/kriasoft/react-routing/issues/15).

Has anyone else had any luck?

**Comment by samosale** [comment]
@Bogdaan @puradox I don't know oauth0 that is the problem! It must be beginers friendly just like angular fullstack is. Later on I will learn oauth0, ofcourse...

**Comment by mwpowellhtx** [comment]
Agree with @samosale supporting OAuth/OAuth2. A way to identify identity tokens that mean something to a back end authentication/authorization service.

**Comment by Bogdaan** [comment]
@puradox @samosale 
related with #70 
See example of authorization on this beautiful kit: https://github.com/Bogdaan/react-auth-kit

**Comment by ulani** [comment]
@aleksandar-b   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
