### ISSUE TITLE
General discussion

### ISSUE THREAD

**Issue by pickingausername** [kriasoft/react-starter-kit#430]
Is there any  post/blog out there which can help in understanding about components rendering, flow of (syntax wise) client.js file, and routing stuff and which files(parts) are flux related  and how to use it.
##

**Comment by manu3loq** [comment]
+1. Would be good if there's like a "code walk-through" of the boilerplate code. This might be good for people starting up with ReactJS/Express in general.

For e.g. Answer the question: "How do I get Login page to skip the `<App />` layout and render on it's own?"

**Comment by pickingausername** [comment]
Is there any other starter kit( a different version of this) which uses react-router?.

**Comment by jeroenransijn** [comment]
@pickingausername there are a lot of requests for this. I am thinking of implementing it myself at this point. I'll let you know if there is a working fork.

**Comment by frenzzy** [comment]
Did you see PR #422 "Use react-router"?

**Comment by pickingausername** [comment]
@frankleng  thanks

**Comment by jamesryancooper** [comment]
@pickingausername I implemented PR [#422](https://github.com/kriasoft/react-starter-kit/pull/422) and it works like a charm.

**Comment by jeroenransijn** [comment]
@frenzzy only saw the post/branch after posting here, #422 is the way to go.

**Comment by shepherdz** [comment]
@pickingausername I wrote a doc, see my PR #680

**Comment by ulani** [comment]
@pickingausername   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
