### ISSUE TITLE
Not able to overide react-bootstrap css component via {s.classname}

### ISSUE THREAD

**Issue by pickingausername** [kriasoft/react-starter-kit#431]
import { Navbar } from 'react-bootstrap'
`<Navbar fixedTop inverse className={s.navbar}>`
gives 
`<nav class="Navigation_navbar_20N navbar navbar-inverse navbar-fixed-top" data-reactid=".1ovq1r9dbeo.0.0">`
Bootstrap component is overriding .scss class.why?
##

**Comment by pickingausername** [comment]
And why my bootstrap.css file is in node_modules/cover/resources and not in node_modules/bootstrap/...  ?

**Comment by ulani** [comment]
@pickingausername   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
