### ISSUE TITLE
Out of date dependency

### ISSUE THREAD

**Issue by pranaygp** [kriasoft/react-starter-kit#441]
deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
##

**Comment by goldensunliu** [comment]
@pranaygp thanks for the report. Feel free to take a stab at this.

**Comment by dfrankland** [comment]
I believe that loadash@1.0.2 is a dependency of a dependency, there's no way to fix it in this repository, you will need to fix the dependency that requires it.

**Comment by richb-hanover** [comment]
Both lodash@1.0.2 and graceful-fs@1.2.3 seem to be outdated. Using node v5.3.0 and npm 3.7.1, npm install shows:
````
bash-3.2$ npm install
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
...
````
The culprit seems to be gaze/globule/glob (excerpt from the `npm install` output)
````
│...
├─┬ gaze@0.5.2
│ └─┬ globule@0.1.0
│   ├─┬ glob@3.1.21
│   │ ├── graceful-fs@1.2.3
│   │ └── inherits@1.0.2
│   ├── lodash@1.0.2
│   └── minimatch@0.2.14
│...
````
What's confusing is that the package.json for gaze@0.5.2 (https://github.com/shama/gaze/blob/master/package.json) requires a newer globule@0.2.0 than what was installed. 

And the newer globule@0.2.0 (https://github.com/cowboy/node-globule/blob/master/package.json) would pull in newer lodash and glob->graceful.fs

Any ideas why this isn't happening?

**Comment by korneSt** [comment]
@richb-hanover If you check out gaze@0.5.2 package.json (https://github.com/shama/gaze/blob/v0.5.2/package.json) , you can clearly see that there is "globule": "~0.1.0" in dependencies.

**Comment by richb-hanover** [comment]
Yeah... That's what confused me. (I'm new to npm, so please bear with me.)

The package.json on the top-level gaze page (https://github.com/shama/gaze/blob/master/package.json) lists `"globule": "^0.2.0"`

The package.json link you showed (https://github.com/shama/gaze/blob/v0.5.2/package.json) *does* list `"globule": "~0.1.0"`

What's a newbie to do? How can this be resolved? Thanks!

PS It seems to have been updated to globule@0.2.0 on 16 jan 2016 in https://github.com/shama/gaze/commit/dc5fbbead1b7b4c6894e8000084c96534f4b45c0

**Comment by ulani** [comment]
@pranaygp    thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
