### ISSUE TITLE
Add tree-shaking with Webpack 2 and Babel 6 [$15]

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-starter-kit#447]
For more information visit:
- http://www.2ality.com/2015/12/webpack-tree-shaking.html
- https://gist.github.com/sokra/27b24881210b56bbaff7
- https://www.npmjs.com/package/babel-preset-es2015-webpack
##

**Comment by ulani** [comment]
@koistya  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
