### ISSUE TITLE
Create login(), logout() GraphQL mutations

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-starter-kit#467]
```
src/data/mutations/user.login.js
src/data/mutations/user.logout.js
```

Login mutations validates user's email and password via `passport.validate('basic')` or `passport.validate('local')`, creates `id_token` JWT token, sends it via HttpOnly cookie and refreshes `me` query. Logout mutation removes `id_token` cookie and refreshes the `me` query.
##

**Comment by Bogdaan** [comment]
:-1: Http-api easier to use for simple apps.
Include react-relay and GraphQL server in "starter kit"?

**Comment by ivosabev** [comment]
+1 for react-relay implementation with GraphQL mutations

**Comment by koistya** [comment]
@Bogdaan if you already use GraphQL for data, why to use another technology for login/logout?

**Comment by Bogdaan** [comment]
@koistya GraphQL/react-relay is great, and you code is awesome. Perhaps graph query/mutation is the right way.
But there are cases where REST api is preferred:
* mobile-app / native-app clients 
* no-backend app ( web-client <--> RSK <--> Scala/Python/C++/hhvm backend )

**Comment by farhad-arjmand** [comment]
how we can login-local via passportjs? and check user login and logout?

**Comment by ulani** [comment]
@koistya  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
