### ISSUE TITLE
Use html as the entry point?

### ISSUE THREAD

**Issue by clearmirror** [kriasoft/react-starter-kit#468]
Say my project has a 'client' folder to serve files. In there I have a index.html as the entry point. How can I integrate this starter-kit?

**Comment by Bogdaan** [comment]
This starter kit - not a "client-side kit".
This kit includes server and client.
So your question is incorrect.

**Comment by ulani** [comment]
@clearmirror   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
