### ISSUE TITLE
on prod call for main.js is returning a broken html , not able to figure out the issue :(

### ISSUE THREAD

**Issue by shubhamgautam** [kriasoft/react-starter-kit#485]

**Comment by Bogdaan** [comment]
Seems you use `master` branch, try to checkout to `v0.4.1`
Releases list - https://github.com/kriasoft/react-starter-kit/releases

**Comment by ulani** [comment]
@shubhamgautam   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
