### ISSUE TITLE
SASS compile issues

### ISSUE THREAD

**Issue by Ehesp** [kriasoft/react-starter-kit#495]
Hello!

it seems that I cannot get default SASS functions to compile. For example, in the `variables.scss` file I do something like:

```
$theme: darken(#333635, 10%);
```
Docs: http://sass-lang.com/documentation/Sass/Script/Functions.html#darken-instance_method

There is no SASS errors in the console, but checking out the actual CSS on the browser:

```
background-color: darken(#333635, 10%);
```

This returns an invalid colour and hence doesn't render.

**Comment by Bogdaan** [comment]
This kit not use SASS. You can install `sass-loader` - see example #461

**Comment by Ehesp** [comment]
Ah yeah my bad... Sorted now, cheers.

**Comment by zwhitchcox** [comment]
Can someone tell me, if this project doesn't use sass, why we are labeling  our css files `scss` and using the postcss-scss parser?

Is this just so someone can easily transition to sass?

**Comment by koistya** [comment]
> Why we are labeling our css files `scss` and using the `postcss-scss` parser?

Because the fully featured Sass might be an overkill in many cases, I see developers are using mostly variables and includes, having all the advanced styling logic inside React components.

One solution would be move away from Scss variables to CSS3 variables, and switch back to `.css` file extension.

**Comment by zwhitchcox** [comment]
Ah, ok, cool!
