### ISSUE TITLE
Where do I load a CSS framework?

### ISSUE THREAD

**Issue by alexdrans** [kriasoft/react-starter-kit#499]
I am attempting to load Semantic UI into the starter pack, and at the moment I am including it on all pages in the old fashion way. Where should I be loading my .css and .js files?

**Comment by koistya** [comment]
@alexdrans try to configure a loader for these files, then import them from your custom CSS code, for example:

```css
@import '../../../node_modules/module-name/file.css';
```

Alternatively, you can specify the list of loaders along with their settings on the same line where you reference a CSS file, for example:

```css
@import '!!isomorphic-style-loader!css-loader!../../../node_modules/module-name/file.css';
```

**Comment by ulani** [comment]
@alexdrans   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
