### ISSUE TITLE
when npm start, the main process end with "web pack: bundle is now VALID"

### ISSUE THREAD

**Issue by matt1991** [kriasoft/react-starter-kit#514]
admindeiMac-4:job-node matt.miao$ npm start

> @ start /Users/matt.miao/Documents/demos/job-node
> babel-node tools/run start

[14:05:38] Starting 'start'...
[14:05:38] Starting 'clean'...
[14:05:38] Finished 'clean' after 28 ms
[14:05:38] Starting 'bound copy'...
build/package.json
[14:05:38] Finished 'bound copy' after 147 ms
webpack built fcb827e249a54f7e626c in 4216ms
Child
    Time: 4216ms
                           Asset    Size  Chunks             Chunk Names
    main.js?fcb827e249a54f7e626c  4.1 MB       0  [emitted]  main
Child
    Time: 3543ms
                  Asset    Size  Chunks             Chunk Names
        ../../server.js  278 kB       0  [emitted]  main
    ../../server.js.map  296 kB       0  [emitted]  main
webpack: bundle is now VALID.
^C
admindeiMac-4:job-node matt.miao$ 

it will happen sometimes. Then I need to stop it and restart it.

**Comment by ravihamsa** [comment]
Even I am facing this issue. some times it throws

UglifyJS.AST_Node.warn_function = function(txt) {
                                ^
TypeError: Cannot set property 'warn_function' of undefined

**Comment by ravihamsa** [comment]
upgrading uglify to 2.6.0 in transformers module helped me fix this

**Comment by jpfranco** [comment]
I was having the same issue. I updated Node to version 5.12.0 and the problem went away.

**Comment by ulani** [comment]
@matt1991   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
