### ISSUE TITLE
(Suggestion) Setup as subtree in getting-started

### ISSUE THREAD

**Issue by ChrisWC** [kriasoft/react-starter-kit#515]
This may not be the right place to leave a suggestion, but I think it may be a good idea to include how to add the kit as a subtree in the getting-started instructions. Subtree adds it as a subproject and allows you to see and modify the code as if it is just more code in a separate directory.

you can setup a subtree by running:
git subtree add --prefix directory https://github.com/kriasoft/react-starter-kit.git master --squash

you can read about subtrees here:
http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/

**Comment by ulani** [comment]
@ChrisWC   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
