### ISSUE TITLE
new html page which contains form fields using react

### ISSUE THREAD

**Issue by texirv0203** [kriasoft/react-starter-kit#532]
Hi
- i am trying to create a new html page which contains form fields
- i am trying to develop using react js
- so i have used the react-starter-kit
- in that src folder can you tell me where I can copy my html content in a page..
- can you tell me whats the url should i need to hit to see the webpage...since I see only this url they have given http://localhost:3000/
- providing image of my folder structure 
- i read through documentation but I am not able to find it
  https://github.com/kriasoft/react-starter-kit/tree/master/docs

[![enter image description here](http://i.stack.imgur.com/GUrFo.png)](http://i.stack.imgur.com/GUrFo.png)

**Comment by koistya** [comment]
You can copy some existing page. For example, copy `src/routes/login` folder into `src/routes/new-page`, then copy the route information for it in [src/routes.js](https://github.com/kriasoft/react-starter-kit/blob/master/src/routes.js#L21)

**Comment by ulani** [comment]
@texirv0203   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
