### ISSUE TITLE
Scroll position is not saved

### ISSUE THREAD

**Issue by everdimension** [kriasoft/react-starter-kit#540]
When the app runs, it sets scroll listeners to save the scroll positions for current `location` as a `state` property. The app listens to `Location` changes, which invokes the callback with a `location`, which is expected to keep the `state` property with the scroll information.

But the listener always gets a `location` which has `{ state: null }`.

I believe this may be a bug in the [history](https://github.com/mjackson/history) library.
Or maybe `createHistory` listeners were not intended to be saved by reference.

I will try to look more into this.

**Comment by ulani** [comment]
@everdimension   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
