### ISSUE TITLE
Split app to several filers and async loading

### ISSUE THREAD

**Issue by sashakru** [kriasoft/react-starter-kit#542]
Hey,

I would like split application to several entry points and load only specific component at each url, is there any approach to dynamic component loading in routes?

**Comment by debel88** [comment]
I agree that this would be way better than having a single bundle of several megabytes.

I don't know if this will be implemented in this starter kit in the near future, but in the meantime Pete Hunt has written [an how-to](https://github.com/petehunt/webpack-howto#7-multiple-entrypoints) that introduce the basics of splitting and async loading

**Comment by frenzzy** [comment]
The easiest way is to use webpack's [`require.ensure`](https://webpack.github.io/docs/code-splitting.html) for lazy paths of app and [LimitChunkCountPlugin](https://webpack.github.io/docs/list-of-plugins.html#limitchunkcountplugin) with `maxChunks` limit for `server.js` bundle.

See the latest revision [here](https://gist.github.com/frenzzy/7e8433821057452e77f5429e73bf78a4/revisions) for an example.

**Comment by ulani** [comment]
@sashakru   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
