### ISSUE TITLE
Remove babel-node dependency

### ISSUE THREAD

**Issue by zwhitchcox** [kriasoft/react-starter-kit#549]
It seems like we could not have to require users to use babel-node if we did something like

``` js
require('babel-core/register')
require('babel-polyfill')
require('./server')
```

That way users wouldn't have to download it. Also, then, we wouldn't have to compile the server, because `babel-core/register` is production-ready (or at least there wasn't a big ugly warning against it on the [docs page](https://babeljs.io/docs/usage/require/).

**Comment by ulani** [comment]
@zwhitchcox   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
