### ISSUE TITLE
Relay.js integration.

### ISSUE THREAD

**Issue by shortgiraffe4** [kriasoft/react-starter-kit#551]
Have you thought of setting up Relay.js for using GraphQL?

**Comment by koistya** [comment]
Yep, I'm exporing this path.. at least, would be nice to have the GraphQL ednpoint compatible with Relay.

**Comment by shortgiraffe4** [comment]
Great, I'm trying to make Relay.js working on the starter kit as well. Hope that I can make a pull request soon.

**Comment by koistya** [comment]
@shortgiraffe4 what do you think about this pattern of using Relay?

http://slides.com/koistya/universal-router#/9

**Comment by shortgiraffe4** [comment]
I am very interested in this idea. Apparently, I have observed that this implementation is kinda similar to what you are doing in react starter kit. Is that correct?

**Comment by koistya** [comment]
Yep, correct. This approach uses a very simple algorithm (see [universal-router/src/match.js](https://github.com/kriasoft/universal-router/blob/master/src/match.js)) and promotes asynchronous code with ES2015 async/await syntax which tends to be easier to write and read as opposed to callbacks as in React Router.

**Comment by rterysen-openroad** [comment]
@koistya It seems to be that once relay is implemented components are not as reusable.  They are heavily dependent on relay. Especially on the component level with `this.props.relay`.  Do you find this to be true as well? Once relay is implemented this starter kit will only be able to work with relay and nothing else correct?

**Comment by langpavel** [comment]
@rterysen-openroad Reusable components still can be created. Relay container components should provide props to View components. View components should not be aware of Relay.

**Comment by rterysen-openroad** [comment]
So this.props.relay will never be utilized in a view component?

**Comment by langpavel** [comment]
@rterysen-openroad You can always separate code of component to as many files as you wish, cannot you? If you wish some components, e.g. DateTimePicker to be reusable, you always can. You can model `props` shape for this component and pass down only required data and envent handlers. Relay drives data abstraction. If you use Redux as dependency, component will not be reusable without it as well. Doesn't matter which data backend you use.

**Comment by rterysen-openroad** [comment]
@langpavel  Thank you! I am going give this approach a try.

**Comment by dhyegofernando** [comment]
:+1:

**Comment by adampietrasiak** [comment]
Any progress?

**Comment by meodemsao** [comment]
wait....

**Comment by koistya** [comment]
I think with Relay, it makes a lot of sense to use declarative routes such as:

```
[
  {
    path: '/home',
    component: './routes/Home',
    query: {
      viewer: '{ viewer }',
      news: '{ news(top: 10) }'
    }
  },
  ...
]
```

...where each route contains GraphQL root queries. You can see this solution implemented in [react-static-boilerplate](https://github.com/kriasoft/react-static-boilerplate), though instead of Relay queries it uses custom queries compatible with REST API endpoints, but tweaking it to Relay should be very easy. Take a look:

```
/route.json - the list of routes in JSON (declarative)
/utils/routes-loader.js - Webpack loader that converts JSON routes to JavaScript code during compilation
/core/router.js - the router itself that has a single API method: `const result = await Router.resolve(routes, location)`
/main.js - application entry point, demonstrating how this router is used
```

**Comment by parthrao** [comment]
I would be great if you can add this to existing project

**Comment by ulani** [comment]
@shortgiraffe4   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
