### ISSUE TITLE
Problem trying to run on Windows 10

### ISSUE THREAD

**Issue by estyrke** [kriasoft/react-starter-kit#557]
I'm trying to get react-starter-kit to work on Windows 10. "npm install" and "npm start" seems to do what they should, but when I browse to "localhost:3001", the page is blank and won't finish loading. If I instead go to "localhost:3000" I get the headers and footers, but no content. The console shows the error "main.js:1 Uncaught SyntaxError: Unexpected token <", and main.js appears to contain the same code as the main page (the title tag contains "Error").

The last lines of the server console (the last line appears when I go to localhost:3000):

```
webpack: bundle is now VALID.
[16:13:32] The server is running at http://localhost:3000/
[BS] [info] Proxying: http://localhost:3000
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:3001
    External: http://172.16.1.121:3001
 -------------------------------------
          UI: http://localhost:3002
 UI External: http://172.16.1.121:3002
 -------------------------------------
[BS] Watching files...
[16:13:34] Finished 'start' after 6392 ms
Warning: Failed propType: Invalid prop `children` supplied to `App`, expected a single ReactElement.
```

Apart from that, there are no obvious error messages.

npm@3.8.3 C:\Program Files\nodejs\node_modules\npm
node-gyp@3.3.1  C:\Users\EmilS\AppData\Roaming\npm\node_modules\node-gyp
node@5.10.1

**Comment by oizie** [comment]
I am having the same issue in a Windows 7.

**Comment by janicak** [comment]
I'm having this issue in OSX, so probably not related to the OS

**Comment by andyhu** [comment]
Same issue here

**Comment by chentaixu** [comment]
I had the same issue, then I realized the googleapi.com is blocked in China. Check out news.js

If your server cannot access googleapi.com for whatever reason, it will stuck for 2 mins.

And you will get "Invalid prop `children` supplied to `App`, expected a single ReactElement." because there is no single news entry fetched.

Delete the news.js part and see if it works.

Hope that solves your problem.

**Comment by ulani** [comment]
@estyrke   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
