### ISSUE TITLE
Action methods in routes should be able resolve data other than the component to render

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-starter-kit#576]
Currently, route handlers (actions) return React components as follows:
##### `src/routes/news/index.js`

``` js
import React from 'react';
import fetch from '../../core/fetch';
import NewsPage from './NewsPage';

export default {
  path: '/news',
  async action() {
    const resp = await fetch('/api/news');
    const data = await resp.json();
    return <NewsPage {...data} />;
  }
}
```

It would be great to change this pattern to something like this instead:
##### `src/routes/news/index.js`

``` js
import fetch from '../../core/fetch';
import NewsPage from './NewsPage';

export default {
  path: '/news',
  async action() {
    const resp = await fetch('/api/news');
    const data = await resp.json();
    return {
      title: 'News Feed',
      meta: [
        { name: 'og:title', content: 'News Feed' }
      ]
      component: NewsPage,
      props: data
    };
  }
}
```

P.S.: For more information about the routing approach used in this starter kit, visit [universal-router](http://slides.com/koistya/universal-router)

**Comment by ulani** [comment]
@koistya  thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
