### ISSUE TITLE
graceful-fs version 3 is outdated

### ISSUE THREAD

**Issue by akaRem** [kriasoft/react-starter-kit#607]
I've tried to install packages from latest master and such warning appeared:

> npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
> not sure which components are outdated, but please take a look

**Comment by langpavel** [comment]
This is caused by third party dependencies.

**Comment by akaRem** [comment]
```
├─┬ mocha@2.4.5
│ ├── commander@2.3.0
│ ├── diff@1.4.0
│ ├── escape-string-regexp@1.0.2
│ ├─┬ glob@3.2.3
│ │ ├── graceful-fs@2.0.3
│ │ └─┬ minimatch@0.2.14
│ │   └── lru-cache@2.7.3
```

**Comment by koistya** [comment]
Ref https://github.com/mochajs/mocha/issues/2121

**Comment by ulani** [comment]
@akaRem   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
