### ISSUE TITLE
Generate `.html` pages at compile-time

### ISSUE THREAD

**Issue by koistya** [kriasoft/react-starter-kit#61]
Create a new build step (aka Gulp task) which would generate `.html` pages during a build in order to be able to deploy this web app into CDN (see [GitHub Pages](https://pages.github.com/)).

**Comment by goatslacker** [comment]
I was actually thinking of making the html pages dynamic rather than static so we can turn this into a proper isomorphic example.

Data fetching/passing data from the server to the client is what is usually complex with isomorphic apps.

If this happens then we'd be unable to publish to github pages.

**Comment by frankbolviken** [comment]
Any progress on this task?

**Comment by koistya** [comment]
@frankbolviken this was implemented in [React Static Boilerplate](https://github.com/koistya/react-static-boilerplate) project, which has a similar structure but optimized for static hostings like GitHub Pages, Amazon S3, Firebase.
