### ISSUE TITLE
Weird (possible) error

### ISSUE THREAD

**Issue by zwhitchcox** [kriasoft/react-starter-kit#621]
I haven't figured out why this happens, and I have not seen this before. But when webpack is compiling, within the `routes/[route]/[route.js]` directory, this doesn't work:

``` js
import MyComponent from 'components/MyComponent'
```

However, if you add the same code above in the `routes/index.js` directory, it works.

I'm using the absolute path relative to the source directory, because I think it's easier than managing relative paths to the directory. It is specified in the [`resolve.root` property of the webpack config](https://github.com/kriasoft/react-starter-kit/blob/master/tools/webpack.config.js#L124).

This is bizarre to me, and took me a while to figure out. It's not a huge issue, but I just wanted to point it out to people who might be interested. I will try to figure it out myself as well.

**Comment by pierrecholhot** [comment]
I stumbled on this in React Static Boilerplate when I tried to create a `resolve.alias` to the components path.. I found a workaround: https://github.com/koistya/react-static-boilerplate/issues/86

**Comment by bearcott** [comment]
@pierrecholhot why didn't you just make an src alias?

**Comment by ulani** [comment]
@zwhitchcox   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
