### ISSUE TITLE
Do not use DefinePlugin for process.env.NODE_ENV

### ISSUE THREAD

**Issue by khankuan** [kriasoft/react-starter-kit#636]
Using the define plugin causes confusion as `process.env['NODE_ENV'] === process.env.NODE_ENV` results to `false`.

**Comment by langpavel** [comment]
@khankuan good point. Any suggestions?

**Comment by ulani** [comment]
@khankuan   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
