### ISSUE TITLE
app.use(compression()) doesn't work for main.js

### ISSUE THREAD

**Issue by antongavrilenkov** [kriasoft/react-starter-kit#644]
Other static files perfectly compressed with gzip. 
Is it a bug, compromise for 
other features or is it my mistake?

![1](https://cloud.githubusercontent.com/assets/11135741/15095996/f80aa792-14b2-11e6-95b5-fc44225251ff.jpg)
![2](https://cloud.githubusercontent.com/assets/11135741/15095999/f80b2a50-14b2-11e6-84d4-178059a8e894.jpg)
![3](https://cloud.githubusercontent.com/assets/11135741/15095997/f80afb2a-14b2-11e6-914e-25f65cc60984.jpg)
![4](https://cloud.githubusercontent.com/assets/11135741/15095998/f80b134e-14b2-11e6-83e0-1fc25c2468bc.jpg)

**Comment by frenzzy** [comment]
In the watch mode (`npm start`) bundles (`main.js` and chunks) are not processed by node.js application due to the specifics of [webpack hot reload](http://webpack.github.io/docs/hot-module-replacement-with-webpack.html).

If you run the application without a hot reload, gzip should work for `main.js` too, try
```shell
$ npm run build && node build/server.js
```

**Comment by damiangreen** [comment]
I just encountered this and it only started working when i moved the `compression()` invocation immediately beneath the express instantiation, i.e.


    const app = express()
    app.use(compression())

having it beneath `app.use(bodyParser.....` caused it to silently fail
