### ISSUE TITLE
RFC: HTML5  linting

### ISSUE THREAD

**Issue by bravo-kernel** [kriasoft/react-starter-kit#645]
To start discussion; [validating the demo landing page](https://validator.w3.org/nu/?doc=https%3A%2F%2Fdemo.reactstarterkit.com%2F) produces the following html5 error.

``` text
    Error: Attribute description not allowed on element meta at this point.

    From line 1, column 160; to line 1, column 199

    it</title><meta name="description" description=""><meta 
```

Easily fixed by changing second `description` to `content` but I think a better approach would be:
- to add html linting support to RSK
- ideally integrated with `.travis.yml`
- so we can all benefit

**Comment by langpavel** [comment]
Automatically linting whole generated output is not easy to setup.
You must bring production server alive in test, make requests, send them to validation service (do you know HTML5 validating npm package?), and then kill it. It is possible and can be based on work done by @frenzzy static page generator.

**Comment by ulani** [comment]
@bravo-kernel   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
