### ISSUE TITLE
how i can use setMeta ?

### ISSUE THREAD

**Issue by farhad-arjmand** [kriasoft/react-starter-kit#647]
when i use setMeta :
`TypeError: context.setMeta is not a function`

**Comment by AlexCrookes** [comment]
you need to set the contextTypes in your component, i.e.

`
(functionName)..contextTypes = { 
  setTitle: PropTypes.func.isRequired, 
  setMeta: PropTypes.func.isRequired 
};
`

Once you do that, you can setMeta() to your hearts content

**Comment by ulani** [comment]
@farhad-arjmand   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
