### ISSUE TITLE
Any advice on how to integrate react-toolbox?

### ISSUE THREAD

**Issue by davidascher** [kriasoft/react-starter-kit#652]
I'd like to build on the components in http://react-toolbox.com/, but I'm not sure how to combine its npm installation w/ this kit's build setup.

**Comment by ChrisWC** [comment]
I just took a quick look at incorporating react-toolbox. You might want to take a look at [https://github.com/react-toolbox/react-toolbox/issues/508](this issue) if you having an issue setting it up. I

**Comment by kemcake** [comment]
Hey @davidascher Did you find a way to use react-toolbox ? Having the problem with css loaders

**Comment by kemcake** [comment]
thank you @davidascher , but it's not an isomorphic anymore :/

**Comment by tabzone** [comment]
does anyone have the setup files for  react-toolbox ver 2.0 ?

**Comment by ErichBSchulz** [comment]
+1

**Comment by ulani** [comment]
@davidascher   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
