### ISSUE TITLE
Example adding a component

### ISSUE THREAD

**Issue by DanielHabib** [kriasoft/react-starter-kit#655]
Please add an example in the documentation for how to add new components.

I have tried and I keep running into issues with the CSS not exporting correctly

**Comment by upq** [comment]
I'm pretty sure you are missing one of these

First import [isomorphic style loader](https://github.com/kriasoft/isomorphic-style-loader) for server side rendering css
```import withStyles from 'isomorphic-style-loader/lib/withStyles';```

**Import your styles**
```import s from './Style.scss';```

**Use your style** 
```<div className={s['My-style']}>```
or
```<div className={s.MyStyle}>```

And lastly don't forget to **export with styles**
```export default withStyles(s)(YourComponent);```

**Comment by ritsuyan** [comment]
@upq  it must use scss but cannot use css?

**Comment by upq** [comment]
I believe you can use css too.

**Comment by tobiasmuehl** [comment]
@ritsuyan CSS support has been added in [8fcb0fa3aac032eb9e7d85e07a50703e54e0e8af](https://github.com/kriasoft/react-starter-kit/commit/8fcb0fa3aac032eb9e7d85e07a50703e54e0e8af)

**Comment by ulani** [comment]
@DanielHabib   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
