### ISSUE TITLE
Using both babel-runtime and babel-polyfill

### ISSUE THREAD

**Issue by finkelm** [kriasoft/react-starter-kit#667]
These two do the same thing in different ways. Perhaps you should choose one or the other. Or just polyfill for the features you actually are using (to get a smaller transpiled product).

**Comment by fmal** [comment]
I guess the best solution would be to keep `babel-polyfill` in entry files and properly configure `babel-plugin-transform-runtime` so it only does helper aliasing.

Change https://github.com/kriasoft/react-starter-kit/blob/35b7c774f084a5f46fe185d93f06f3123b815d25/tools/webpack.config.js#L66 to:

```
"plugins": [
  [
    "transform-runtime",
    {
      "polyfill": false,
      "regenerator": false
    }
  ],
  ...
]
```

**Comment by ulani** [comment]
@finkelm   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
