### ISSUE TITLE
Broken Images from `npm run build`

### ISSUE THREAD

**Issue by 5punk** [kriasoft/react-starter-kit#669]
`<img src={require('../../public/logo.png')} ...`

works for dev mode
it makes a http request to
`http://localhost:3000/src/public/logo.png`
but in build folder
the same URL is requested
and it's not found
cause the image is actually in `http://localhost:3000/logo.png`

What's the generic way of requiring images so they work in dev mode as well as from the build folder?

**Comment by frenzzy** [comment]
I can not reproduce this on the master branch, maybe your version of RSK is outdated?

**Comment by ulani** [comment]
@5punk   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
