### ISSUE TITLE
test

### ISSUE THREAD

**Issue by pbazard** [kriasoft/react-starter-kit#670]

**Comment by upq** [comment]
why ?

**Comment by simeg** [comment]
@koistya this should probably be closed and/or removed.

**Comment by ulani** [comment]
@pbazard   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
