### ISSUE TITLE
 the application is styleless for seconds at the first mount

### ISSUE THREAD

**Issue by FakhruddinAbdi** [kriasoft/react-starter-kit#671]
My app on the first load is styleless for about a second then Bootstrap get loaded.
I'm using bootstrap-loader package and i have added it to the client.js entry point to load bootstrap. 

apparently it's not related to bootstrap-loader. Because the style is placed in the DOM ,  then they can be hot reloadable.

I thought it's ok since it should only applied to development environment, but when i tried running build script, i saw same problem.

Can you please help me how to fix it

**Comment by FakhruddinAbdi** [comment]
@koistya @frenzzy

**Comment by koistya** [comment]
Don't you want to reference Bootstrap's CSS directly on the HTML page? For example:

```html
<html>
  <head>
    <title>{title}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script async src="/bundle.js"></script>
  </head>
  <body>
    <div id="container">/* pre-rendered markup */</div>
  </body>
</html>
```

Alternatively you would need to load it the same way as the rest of the CSS styles via `isomorphic-style-loader`.

**Comment by langpavel** [comment]
See https://github.com/kriasoft/react-starter-kit/pull/646

**Comment by atalebagha** [comment]
I am using bootstrap loader, what is the work around for that?

**Comment by ulani** [comment]
@FakhruddinAbdi   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
