### ISSUE TITLE
Pass port via command line

### ISSUE THREAD

**Issue by frob** [kriasoft/react-starter-kit#673]
Is there any way to pass the port via the command line?

**Comment by langpavel** [comment]
Just use environment variable `PORT`

**Comment by frob** [comment]
Can an argument be passed via the command line? I would prefer not to use an environment variable. 

I have several of these sites on the same server that are being hosted via apache proxy pass.

**Comment by langpavel** [comment]
It is very easy to tweak code in `src/config.js`.
You can use [`nopt`](https://github.com/npm/nopt#readme), [`commanderjs`](https://github.com/tj/commander.js#commanderjs) or even more universal [`nconf`](https://github.com/indexzero/nconf#nconf)

I personally use [`dotenv`](https://github.com/motdotla/dotenv#dotenv) module, reading defaults from `.conf` ini-like file.

**Comment by frob** [comment]
Those all look like good options. They also look like this is becoming a feature request.

**Comment by ulani** [comment]
@frob   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
