### ISSUE TITLE
weird comportement

### ISSUE THREAD

**Issue by pascalct** [kriasoft/react-starter-kit#675]
when you click on one of the news on the first page and then back button on browser, you can't change page anymore, links seems to not work. 
Only on firefox

**Comment by ulani** [comment]
@pascalct   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
