### ISSUE TITLE
enter localhost:3000 and localhost:3001 just find internal server error

### ISSUE THREAD

**Issue by ritsuyan** [kriasoft/react-starter-kit#679]

**Comment by leonzinger** [comment]
Getting the same error after an update

**Comment by florianlebrenn** [comment]
Same error.

**Comment by tracihaire** [comment]
Not able to hook on to server

**Comment by GideonFlynn** [comment]
How to reproduce this problem? Try this:

- Clone repo
- Go to folder where RSK exists
- Open a terminal and run:
- yarn install
- Some time will pass while it downloads, now run:
- yarn start
- Go to localhost and check.

**Comment by ulani** [comment]
@ritsuyan   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
