### ISSUE TITLE
The Component ClassName Corrent but cannot generator its styles??

### ISSUE THREAD

**Issue by ritsuyan** [kriasoft/react-starter-kit#681]

**Comment by tobiasmuehl** [comment]
Please provide more details like sample code and wanted result. As this looks more like a general question than an actual issue, please refer to the [Gitter.im chat](https://gitter.im/kriasoft/react-starter-kit).

**Comment by ulani** [comment]
@ritsuyan   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
