### ISSUE TITLE
Unnecessary PostCSS plugins

### ISSUE THREAD

**Issue by maximhoffman** [kriasoft/react-starter-kit#685]
Hey guys. I found some plugins what aren't used. Maybe we don't need it and more logical will be removed it for keeping packages purity?
I found that with the RSK install postcss-custom-selectors and postcss-pseudoelements. 
The first plugin is loaded in webpack config but in css code never used. 
The second plugin is not even loaded.

I think we should install modules only if we going to using it. 
What you think about it?

**Comment by frenzzy** [comment]
Agree about [postcss-pseudoelements](https://github.com/axa-ch/postcss-pseudoelements), because this is required for IE8, but many developers no longer support it.

[Custom Selectors](https://drafts.csswg.org/css-extensions/#custom-selectors) is native "W3C CSS Next" feature as well as others postcss plugins from [this list](https://github.com/stephenway/level4). And I think the starter should include all the plugins that are necessary to [transpile](https://en.wikipedia.org/wiki/Source-to-source_compiler) css next features into cross-browser css like we do now for js (ES7/ES6 => ES5).

**Comment by maximhoffman** [comment]
@frenzzy so, maybe we should use it in CSS? At least for example. Because I couldn't find any usage.

**Comment by ulani** [comment]
@maximhoffman   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
