### ISSUE TITLE
How to add a proxy for backend

### ISSUE THREAD

**Issue by hlzhang** [kriasoft/react-starter-kit#690]
I want to use react-starter-kit generated project with spring-boot which starts a jetty server on localhost:8080.
To avoid cors problem, I need a proxy run with webpackHotMiddleware at localhost:3000.
How to impl this. Need help.

**Comment by pritamkumarshahi** [comment]
I have to ask same question of #chshawkn.

**Comment by chshawkn** [comment]
I have api service at localhost:8080/api/someService

https://www.npmjs.com/package/express-http-proxy

```
npm install express-http-proxy --save

# in server.js top
import proxy from 'express-http-proxy';
app.use('/api', proxy("localhost", {
  port: 8080,
  forwardPath: function(req, res) {
    console.log("proxy url: " + require('url').parse(req.url).path)
    return "/api" + require('url').parse(req.url).path;
  }
}));
```

**Comment by ulani** [comment]
@hlzhang   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
