### ISSUE TITLE
Are the social profile confidential keys be left mentioned open in config file?

### ISSUE THREAD

**Issue by venkatb4u** [kriasoft/react-starter-kit#714]
Pl do make sure you really need to keep the fb, google, twitter consumer key  & secret in config.js file.

**Comment by frenzzy** [comment]
By default there are used [environment variables](https://en.wikipedia.org/wiki/Environment_variable) and only if they are not set RSK uses specially predefined keys to authorization out of the box for demonstration purposes.

**Comment by ulani** [comment]
@venkatb4u   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
