### ISSUE TITLE
Can't access state of tested component wrapped in withStyle decorator

### ISSUE THREAD

**Issue by sashakru** [kriasoft/react-starter-kit#717]
Hello there,

I'm trying to test component's `state`, component wrapped in `withStyle` decorator, after render component with  `renderIntoDocument` method of `react-addons-test-utils` the `state` of the component is null, I'm assuming that happen because of decorator, is there any approaches how can access `state` of nested component?

**Comment by ulani** [comment]
@sashakru   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
