### ISSUE TITLE
one style file in production

### ISSUE THREAD

**Issue by vadimsg** [kriasoft/react-starter-kit#719]
Hi there, I'm trying to create one compiled css file for production env but currently can't get it to work. One of the problems with this is that we can't create cash buster for styles.

Is it possible, any ideas?

**Comment by srobinson** [comment]
see [772](https://github.com/kriasoft/react-starter-kit/issues/722)

**Comment by langpavel** [comment]
Sorry, what means "cash buster"?

**Comment by langpavel** [comment]
@vadimsg If you think you can continue in #772, please close this issue, otherwise I will close this issue few days later ;-) Thanks!

**Comment by ulani** [comment]
@vadimsg   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
