### ISSUE TITLE
Output to CSS file

### ISSUE THREAD

**Issue by jasonmoro1** [kriasoft/react-starter-kit#722]
Hey guys,

I'm just starting out learning React and I have a (rather simple) question in regards to this starter kit -

Currently, the build compiles the LESS/SASS/CSS as a `style` element in the HTML. I am wondering how would I be able to compile this into a separate CSS file.

Any help would be appreciated!

Thanks!

**Comment by srobinson** [comment]
You can achieve this using extract-text-webpack-plugin, though you likely only want it for the release build, since you will lose hot loading ability in dev

Try something like this:

install the following

`
npm i -D extract-text-webpack-plugin style-loader
`

Update the webpack loader:

```     
 {
        test: /\.css/,
        loaders: DEBUG ? [
          'isomorphic-style-loader',
          `css-loader?${JSON.stringify({
            sourceMap: DEBUG,
            modules: true,
            localIdentName: DEBUG ? '[name]_[local]_[hash:base64:3]' : '[hash:base64:4]',
            minimize: !DEBUG,
          })}`,
          'postcss-loader?pack=default',
        ] : [],
        loader: !DEBUG ? ExtractTextPlugin.extract('style-loader?localIdentName=localIdentName=[hash:base64:4]', 'css-loader?module', 'postcss-loader?pack=default') : ''
      },
```

configure the plugin

```
  plugins: [
    new ExtractTextPlugin('style.css'),
    ...
  ]
```

Add the script to index.jade

```
link(rel="stylesheet", type="text/css", href="/assets/style.css")
```

update server.js: [checking for style._getCss]

```
        insertCss: (...styles) => {
          styles.forEach(style => style._getCss && css.push(style._getCss())) 
        },
```

run

```
npm run -- --release
```

**Comment by jasonmoro1** [comment]
Hey @srobinson,

Thanks for the amazing help.

I have added what you have mentioned and did a release build but I am getting the following error now:

`       ERROR in ./~/css-loader?module!./src/server.js
        Module build failed: CssSyntaxError: /css-loader!/Users/Documents/react-starter-kit/src/server.js:10:1: Unknown word

        import 'babel-polyfill';
        ^
        import path from 'path'`

**Comment by srobinson** [comment]
Looks like you have an unrelated issue with babel-loader. Are you able to build a release w/o these changes?

**Comment by jasonmoro1** [comment]
Hey @srobinson,

It is working now as I didn't include the plugin in the !DEBUG area. That being said, it all builds fine but when I run `node build/server.js`, I can see `TypeError: t._insertCss is not a function(…)` in the console.

**Comment by FakhruddinAbdi** [comment]
@srobinson could you please create pull request for your changes ? It makes more sense

**Comment by FakhruddinAbdi** [comment]
@srobinson Did you solve `TypeError: t._insertCss is not a function(…)` error? 
I'm seeing same.

**Comment by sgraham785** [comment]
i am seeing that error also. i did further testing by adding link to a static css file in index.jade and it gets caught by the router and converts to html. if it load the css file in the browser it also gets caught by the browser. anyone experience this while getting the single css file for prod?

**Comment by ulani** [comment]
@jasonmoro1   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
