### ISSUE TITLE
ReactStarterKit - 0.5.0? 0.5.1? 0.6? 1.0?

### ISSUE THREAD

**Issue by richb-hanover** [kriasoft/react-starter-kit#746]
ReactStarterKit has won the prize - it's the top-ranked project on Andrew Farmer's "Find your perfect React starter project" page - http://andrewhfarmer.com/starter-project/

I wonder if it is a good time for RSK to consider its version numbering. The project itself seems to have been moving forward boldly, and to a good end. But the version numbering gets pretty murky:
- http://reactstarterkit.com boldly proclaims it's at 0.5.0
- The Webstorm folks graciously included the 0.5.1 version in March 2016
- There are a flock of interesting, but un-numbered and breaking, changes since that date in the Changelog at https://github.com/kriasoft/react-starter-kit/blob/master/CHANGELOG.md
- There are now three feature branches available, with an uncertain evolutionary path...

What's a developer to do? 

I have a personal project built on 0.5.1 that needs a bunch of refactoring after I rebased on master. That's OK - but I only want to do it once... 

I wonder if we are nearing an inflection point where we're close to splitting off a "RSK version 1" that goes into maintenance (updating npm packages, bug fixes, etc.) but no new functionality, and a new, wildly experimental RSK2...

I invite your thoughts and comments. In any event, I thank you for all your good work to get the project to this state.

**Comment by ulani** [comment]
@richb-hanover   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
