### ISSUE TITLE
Reloading Assets Problem

### ISSUE THREAD

**Issue by ChrisWC** [kriasoft/react-starter-kit#752]
I seem to be having an issue when I'm using a font that I provide as an asset. Each time I navigate to a different location on the site it reloads the fonts. To me it seems unnecessary and not at all efficient. Any ideas on how to resolve the issue?

**Comment by frenzzy** [comment]
Add your fonts to the styles of root (Layout) component that you are using on all pages or create such component.

**Comment by ChrisWC** [comment]
They were already there. The issue seems to be something with the declaration of font-families. Importing them from somewhere (such as google) seems to resolve the issue, but declaration within the root css file seems to be troublesome.

**Comment by MadeInMoon** [comment]
I'm facing the same problem. When location changes, the nav links disappear and re-appear quickly (when using a local font with font-face).

@ChrisWC, can you provide a short exemple for a local font? thanks

**Comment by MadeInMoon** [comment]
I solved it by using one of the option mentioned [here](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization): "Optimizing font rendering with inlining"

**Comment by ulani** [comment]
@ChrisWC   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
