### ISSUE TITLE
Sample using ReactFire

### ISSUE THREAD

**Issue by ruelluna** [kriasoft/react-starter-kit#760]
I'm finding trouble where to start using ReactFire with RSK.

Anyone got some guides?

**Comment by maxneh** [comment]
I use the library [https://github.com/tylermcginnis/re-base]

**Comment by ulani** [comment]
@ruelluna   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
