### ISSUE TITLE
OnClick functions won't fire

### ISSUE THREAD

**Issue by jdosullivan** [kriasoft/react-starter-kit#761]
Somehow I can't get onClick functions to fire. Even adding a basic JSX such as this anywhere on the page doesn't work:

`<a href="#" onClick={function(e) { e.preventDefault(); alert("left"); }}>Left</a>`

Is there anything special I need to do or is this just happening to me?

**Comment by langpavel** [comment]
Hi, try use instance bound function, look for handleClick on code.. But I cannot see error in your code

**Comment by jahmaiosullivan** [comment]
Seems to be centralized to the feature/react-intl branch. I'll work off the redux branch for now.

**Comment by gooddaddy** [comment]
me too

**Comment by leiming** [comment]
me too

**Comment by langpavel** [comment]
Is everything ok in browser console? All without error?

**Comment by ulani** [comment]
@jdosullivan   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
