### ISSUE TITLE
Html component has relative path for apple-touch-icon

### ISSUE THREAD

**Issue by nuclearspike** [kriasoft/react-starter-kit#768]
This just needs a '/' in the href:

```
<link rel="apple-touch-icon" href="apple-touch-icon.png" />
```

Otherwise if you render "/some/path/other/than/root" it tries to look in that non-existent directory.

**Comment by ulani** [comment]
@nuclearspike   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
