### ISSUE TITLE
modify routes/register/Register.js but UI didn't reload

### ISSUE THREAD

**Issue by fkpwolf** [kriasoft/react-starter-kit#772]
Modify src/components/Header/Header.js and UI will reload and update. But for js under routers, UI didn't get update. 

At both case, I noticed some request like http://localhost:3001/assets/0.0af3b69970588af0c696.hot-update.js but I don't know why one is working and another is not.

**Comment by fkpwolf** [comment]
check with v0.5.1, Register page now is in src/components/RegisterPage/RegisterPage.js. And auto-reload function works well. 

So this issue only happened in master version?

**Comment by andrewkolesnikov** [comment]
There seems to be problem with hot reloading these `The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.
VM961:89 [HMR]  - ./src/routes/register/Register.js`

**Comment by fkpwolf** [comment]
It works now.

**Comment by fkpwolf** [comment]
https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md this topic explained why this error happened. It is because Register.js is not imported by root component - App.js.

**Comment by ulani** [comment]
@fkpwolf   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
