### ISSUE TITLE
Electron integration

### ISSUE THREAD

**Issue by bjackson** [kriasoft/react-starter-kit#785]
Has anyone successfully integrated this with electron?

I am able to get my app to load in Electron, but I cannot seem to be able to require any of the electron modules.

**Comment by holgersindbaek** [comment]
Can you share you main.js file?

**Comment by holgersindbaek** [comment]
@bjackson Can you share your main.js file? Which file are you loading using "loadURL".

**Comment by ulani** [comment]
@bjackson   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
