### ISSUE TITLE
passport facebook strategy bug

### ISSUE THREAD

**Issue by ChrisWC** [kriasoft/react-starter-kit#786]
The facebook strategy (in src/core/passport.js) will return a lot more than id and email if executing line 85. You need to extract the id and email fields from users[0].dataValues if you would like to be getting the same result as in the other sections of the strategy. Using the code as is causes a circular reference error when using jwt.sign with it.

*The case in which this code executes occurs when req.user is null and their is a user to be found. Clearing cookies and trying to use the strategy with the same credentials is an easy way to recreate the bug.

**Comment by blackmiaool** [comment]
I encountered the same error. I solved it by changing the code to : `    const expiresIn = 60 * 60 * 24 * 180; // 180 days
    if(req.user.dataValues){
        req.user=req.user.get({plain:true})
    }
    const token = jwt.sign(req.user, auth.jwt.secret, { expiresIn });`

**Comment by Jaikant** [comment]
@blackmiaool A different solution provided in [this comment](https://github.com/kriasoft/react-starter-kit/issues/935#issuecomment-260375271), what are your views?

**Comment by jorrit** [comment]
A fix is proposed in PR #1184.

**Comment by ulani** [comment]
@ChrisWC   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
