### ISSUE TITLE
Sometimes the everything just stops working (no reload, :3001 endless loading) on Windows 10

### ISSUE THREAD

**Issue by totty90** [kriasoft/react-starter-kit#794]
I don't know why after a while the server just stops working.. If I go to the http://localhost:3001/ it hangs, tries to load the page endlessly.. If I go to http://localhost:3000 the page renders ok.

Anyway I've noticed that even if I change some code the console doesn't understand the changes so it doesn't even refresh anymore.

The solution is to stop the server and start again, which is a pain because is slow.

**Comment by dzek69** [comment]
did you fix that?

**Comment by ulani** [comment]
@totty90   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
