### ISSUE TITLE
scss not building

### ISSUE THREAD

**Issue by mde17** [kriasoft/react-starter-kit#800]
scss not building, needs to update the content of the scss file to import it to the html

**Comment by andrewkolesnikov** [comment]
`scss` is processed through webpack. What isn't working for you, exactly? Can you provide any details?

**Comment by frenzzy** [comment]
Recipe: [How to Use Sass/SCSS](https://github.com/kriasoft/react-static-boilerplate/blob/master/docs/recipes/how-to-use-sass.md)

**Comment by Jaikant** [comment]
I followed the recipe to use Sass, but I am getting the error 
"TypeError: style._getCss is not a function"
The getCss or insertCss function are not part of the css which is parsed. Any pointers on what could be going wrong?

**Comment by frenzzy** [comment]
@Jaikant was a wrong link, please replace `style-loader` with `isomorphic-style-loader`

**Comment by Jaikant** [comment]
@frenzzy thats how I have it. this is how it looks for the error condition.

      {
        test: /\.scss$/,
        loaders: [
          'isomorphic-style-loader',
          `css-loader?${JSON.stringify({ sourceMap: isDebug, minimize: !isDebug })}`,
          'postcss-loader?pack=sass',
          'sass-loader',
        ],
      },

**Comment by Jaikant** [comment]
@frenzzy apologies. I had the import statement wrong. I had done a 
require("!raw!sass!file.scss) instead of the require(file.scss).

**Comment by ulani** [comment]
@mde17   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
