### ISSUE TITLE
Routes error after deployment

### ISSUE THREAD

**Issue by upq** [kriasoft/react-starter-kit#801]
Im deploying my app to heroku
locally everything runs perfect
after deploy I get error complaining about this

```

   async action({ next, render, context }) {
    const component = await next();
    if (component === undefined) return component;
    return render(
      <App context={context}>{component}</App>
    );
  },
```

it says 
`component is not defined`
refering to the one inside the JSX HTML tag.

My order is this

```
  children: [
    home,
    admin,
    contact,
    start,
    login,
    register,
    persona,
    forgot,
    reset,
    content,
    error,
  ],

```

Any clues or possible suspects that may cause this error?

**Comment by langpavel** [comment]
Did you figure this out? Can you provide more details?

**Comment by upq** [comment]
Im still struggling here btw since then , I delayed deployment and worked on finishing my app, I didnt want to waste time on it , but now I am deploying , still same issue.

**Comment by koistya** [comment]
@upq does your app work in production mode locally? `npm start --
--release`. Do you get any other errors or warnings on a production site?
Have you checked Heroku logs?

**Comment by upq** [comment]
@koistya yea its the same in release of course .. the problem is there anyway , Im thinking about using a fresh new copy of rsk but that will be alot of work...

**Comment by ulani** [comment]
@upq   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
