### ISSUE TITLE
Proxy from :3000 to :3001 in development only to avoid issues with HTTP callbacks

### ISSUE THREAD

**Issue by langpavel** [kriasoft/react-starter-kit#815]
This should fix #773 and similar issues in development

**Comment by ulani** [comment]
@langpavel   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
