### ISSUE TITLE
When `debugger` is hit in chrome, source code is not visible and stack is `exports.default`

### ISSUE THREAD

**Issue by totty90** [kriasoft/react-starter-kit#823]
When I put a `debugger` for example in the reducer, when it hits in the browser, this is what I see:

![image](https://cloud.githubusercontent.com/assets/236974/18034797/42bed4aa-6d3e-11e6-858d-775083daa38c.png)

There is no way to see the actual line. All default settings.

If you change the devTool like this it works: `devtool: DEBUG ? '#@cheap-module-eval-source-map' : false,`

Based on commit #374b1dfc3acca38bcbe2edf0ce13aa2b38966265 and merged with redux branch (last night)

**Comment by udisun** [comment]
+1

**Comment by ulani** [comment]
@totty90   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
