### ISSUE TITLE
Is there a showcase of sites that were created using this starter kit?

### ISSUE THREAD

**Issue by lokaltrav** [kriasoft/react-starter-kit#843]
I've looked around and nothing was immediately obvious. I'd like to be able to submit the URL to our site partially to get more visibility for the site, but also to let prospective users see a production site that was built on this project.

**Comment by ulani** [comment]
@lokaltrav   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
