### ISSUE TITLE
Test folder notes in the docs

### ISSUE THREAD

**Issue by itaied246** [kriasoft/react-starter-kit#848]
In the `Getting Started` docs it is mentioned that the folder `/test` should include all the unit tests and end-to-end tests, though the `npm test` command is looking for test files in `\"src/**/*.test.js\"`.  
Am I missing something? Where should I place my unit tests then?

**Comment by ulani** [comment]
@itaied246   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
