### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by hackhat** [kriasoft/react-starter-kit#859]
For example I've implemented in my own project integration tests that runs the front-end and the app is loaded on the page. Then it tests several components at the same time. I think would be really useful

**Comment by ulani** [comment]
@hackhat   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
