### ISSUE TITLE
Add end to end tests

### ISSUE THREAD

**Issue by hackhat** [kriasoft/react-starter-kit#860]
This can be done with webdriver io + selenium + cucumber.js

**Comment by ulani** [comment]
@hackhat   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
