### ISSUE TITLE
Add tooling/installation testing

### ISSUE THREAD

**Issue by hackhat** [kriasoft/react-starter-kit#861]
For example tests that our tooling works fine. For example if you run `npm start` it actually starts a server. If you run build is actually builds the app. The same for eslint and all other tools we have...

**Comment by ulani** [comment]
@hackhat   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
