### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by Bzod** [kriasoft/react-starter-kit#87]
Hi there! i found a one thing on your app. Every time when we reload the page V8 consumes little memory . If you refresh the page several times (10-15 ), you can dial up to 70 MB of memory usage that is not released .

**Comment by NikitaKis** [comment]
+1 Every time when we reload +20MB

**Comment by Bzod** [comment]
(>O_o<) 20MB?!

**Comment by d0ntth1nc** [comment]
I made some tests with Chrome Timeline function and there is no memory leaks. Click f12, click the "Record" button, do some navigation in the website and try to hit at least 50% of the buffer. When you know that you did some work on the web app, click the "Collect Garbage" button, wait 1-2 secs and click the "Stop" button. You will see nice picture of the whole application memory. Trust me, there is no memory leaks! :)
The browser seems to garbage collect all JS objects and DOM nodes at given interval, but not listeners. This can be seen in all applications, not react based only. I don`t know why, but maybe there is good reason. This is not memory leak, because when i click the button "Collect Garbage", all listeners are freed from the memory. I can give you a nice picture to prove that
![image](http://s27.postimg.org/jyjvy5poj/snapshot10.jpg)

**Comment by koistya** [comment]
I'm going to close this issue for now. Feel free to reopen if needed.
