### ISSUE TITLE
issue with BrowserSync when editing home.js inside the /routes/home folder

### ISSUE THREAD

**Issue by bodazhao** [kriasoft/react-starter-kit#871]
hi beginner here

just followed the getting started guide and had the website running on `localhost:3001` with BrowserSync, but when i tried to edit the home.js inside the ./routes/home folder, the website won't refresh on `localhost:3001`. I had to manually refresh to see the changes. But it works fine with other routes, such as Login, Contact etc. Any idea?

**Comment by amilajack** [comment]
What is the status of this? Did anyone solve this?

**Comment by fblecha** [comment]
+1

**Comment by devk1d** [comment]
+1

**Comment by koistya** [comment]
After editing Home.js, both client-side and server-side bundles are being recompiled, the problem is that the client-side portion is reloaded faster, but there is an Ajax request hanging in pending state waiting for the server to respond which never does. Ideas how to solve this issue are welcome! :)

**Comment by brendonshih** [comment]
I'm having similar issues when I modify Header.js in the components file. HMR/BrowserSync aren't updating the pages automatically.

**Comment by amcsi** [comment]
For me, none of the components update the pages automatically

**Comment by AJIh** [comment]
@koistya Maybe we should resolve `Component` and `props` separately in the router?

```javascript
// route
async action() {
  // ... some actions
  return {
    async getComponent() {
    },
    async getData() {
    },
  },
}

// client.js
let Component, data;

function onLocationChange(location) {
  // ... some actions
  const route = await UniversalRouter.resolve(routes);
  [Component, data] = await Promise.all([route.getComponent(), route.getData()];
  appInstance = ReactDOM.render(
      <App context={context}><Component {..data.renderProps} /></App>,
      container,
      () => onRenderComplete(route, location)
    );
}

// Enable Hot Module Replacement (HMR)
if (module.hot) {
  module.hot.accept('./routes', async () => {
    routes = require('./routes').default; // eslint-disable-line global-require

    const route = await UniversalRouter.resolve(routes);
    Component = await route.getComponent();
    appInstance = ReactDOM.render(
      <App context={context}><Component {..data.renderProps} /></App>,
      container,
      () => onRenderComplete(route, location)
    );
  });
}
```

**Comment by ulani** [comment]
@bodazhao   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
