### ISSUE TITLE
Using Flow with ESLint

### ISSUE THREAD

**Issue by amilajack** [kriasoft/react-starter-kit#876]
This would be a great addition to the workflow of this project

![ESLint Flow Demo](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/flow-demo.gif?raw=true)

https://github.com/amilajack/eslint-plugin-flowtype-errors

Thoughts?

**Comment by jedwards1211** [comment]
Yeah I pity the fool who writes a large-scale app without Flowtype or Typescript these days

**Comment by langpavel** [comment]
@amilajack can you give us a hint

**Comment by amilajack** [comment]
There a getting started guide: https://github.com/amilajack/eslint-plugin-flowtype-errors#getting-started

**Comment by ulani** [comment]
@amilajack   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
