### ISSUE TITLE
in ie9 componentDidMount not work

### ISSUE THREAD

**Issue by cyenchen** [kriasoft/react-starter-kit#884]
componentDidMount not work in ie9,setState not work too,
[
![image](https://cloud.githubusercontent.com/assets/18211005/18902959/ddd29a28-8588-11e6-9beb-65d5f14cecca.png)
](url)
This is my code!
@kriasoft

**Comment by mkelley33** [comment]
@kriasoft-bot `componentDidMount` isn't working for IE9 for me either.  I'm also seeing a script error in vendor.chunks.js for the query-string dependency using the `const`keyword, which isn't supported in IE9. Do you think we should update the `browserslist` in package.json to support maybe IE11 and up?  IE9 and IE10 usage peak at .2 percent according to https://www.w3schools.com/browsers/browsers_explorer.asp.  We could show the classic get-a-modern-browser banner for <= IE10, and probably be just fine.

**Comment by ulani** [comment]
@cyenchen   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
