### ISSUE TITLE
Externals Regex in Webpack serverConfig is too broad.

### ISSUE THREAD

**Issue by Judahmeek** [kriasoft/react-starter-kit#892]
The externals regex catches 'bootstrap-loader' requests, which leads to a `Cannot find module './lib/bootstrap.loader!./no-op.js'` error if 'bootstrap-loader' is added as an entry point to serverConfig.

I'm pretty sure that 'bootstrap-loader' requests aren't the only requests being caught that shouldn't be. Full console.log results here: https://gist.github.com/Judahmeek/67a73f2b1b1cdb342a82e2e66c9d256f

Brought to my attention by @mxmtsk in shakacode/bootstrap-loader#41. Tested: https://github.com/Judahmeek/react-starter-kit-with-bootstrap-loader/tree/server-config-error

**Comment by ulani** [comment]
@Judahmeek   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
