### ISSUE TITLE
what's the philosophy with components?

### ISSUE THREAD

**Issue by mattroid** [kriasoft/react-starter-kit#896]
Do we create components with a package.js so that we can independently configure each component and make them more portable? Or is this a common practice to put package.js in sub directories of different parts of the application for commonjs to require it easily.

**Comment by koistya** [comment]
@mattroid an alternative solution would be creating `index.js` instead of `package.json` and re-exporting component. But in case with `package.json` you import corresponding React component directly without intermediaries. For example, `Layout` references `Link` component, if you open `components/Layout/Layout.js` and CTR+Click on the `import Link from '../Link'` in your editor or IDE, you will be redirected straight to the `components/Link/Link.js` file (and not `components/Link/index.js`).

**Comment by ulani** [comment]
@mattroid   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
