### ISSUE TITLE
unmounting issue?

### ISSUE THREAD

**Issue by DA717** [kriasoft/react-starter-kit#905]
we have a SPA app uses a previous version of the starter kit pre-layout.  an odd thing we are noticing is our child component never gets unmounted and the app container seems to get re-created moving between routes.  Is anyone else having a similar issue?  See screenshot.  thanks.

![image](https://cloud.githubusercontent.com/assets/18683944/19197063/d4728f70-8c6c-11e6-969e-d12bb7be301d.png)

**Comment by ulani** [comment]
@DA717   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
