### ISSUE TITLE
Test server side API with chai

### ISSUE THREAD

**Issue by r14git** [kriasoft/react-starter-kit#906]
I would like to test API using chai library. I want to test express router and check if '/api/books' can be accessible and return proper value. To do this I've tried to use chai library where I need to include server in a test file.  
When I include server from src file:
`let server =``require('../../server');`
I've got error message: 

```
module.js:341
    throw err;
    ^
Error: Cannot find module './assets'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)

Error: Cannot find module './assets'
```

So I've tried to include server from build folder:
`let server =``require('../../Build/server');`

In this case it works but when I use npm run test:watch it works only for the first time, then in every next reload (save of test file) I have error related to port binding (as probably port is already in use): 

```
Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
```

What is the proper way of testing server.js ?

**Comment by itaied246** [comment]
Did you find a proper way to test the API?
I also thought about importing the `Build/server`, but then I need to build the code every time before a test...

**Comment by ulani** [comment]
@r14git   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
