### ISSUE TITLE
How to call child component method from parent?

### ISSUE THREAD

**Issue by devk1d** [kriasoft/react-starter-kit#909]
Child.js

```
import s from './Child.css';

class Child extends Component {
 getAlert() {
    alert('clicked');
 }
 render() {
  return (
    <h1 ref="hello">Hello</h1>
  );
 }
}

export default withStyles(s)(Child);
```

Parent.js

```
class Parent extends Component {
 render() {
  onClick() {
    this.refs.child.getAlert() // undefined
  }
  return (
    <div>
      <Child ref="child" />
      <button onClick={this.onClick.bind(this)}>Click</button>
    </div>
  );
 }
}
```

**Comment by frenzzy** [comment]
For example you can use [Refs to Components](https://facebook.github.io/react/docs/more-about-refs.html) approach like so:

```js
/* Child.js */
import React from 'react'
import withStyles from 'isomorphic-style-loader/lib/withStyles'
import s from './Child.css'

class Child extends React.Component {
  componentDidMount() {
    this.props.onRef(this)
  }
  componentWillUnmount() {
    this.props.onRef(null)
  }
  method() {
    console.log('do stuff')
  }
  render() {
    return <h1>Hello World!</h1>
  }
}

export default withStyles(s)(Child);
```
```js
/* Parent.js */
import React from 'react'

class Parent extends React.Component {
  onClick = () => {
    this.child.method() // do stuff
  };
  render() {
    return (
      <div>
        <EnhancedChild onRef={ref => (this.child = ref)} />
        <button onClick={this.onClick}>Child.method()</button>
      </div>
    );
  }
}
```

Demo: https://jsfiddle.net/frenzzy/z9c46qtv/

**Comment by devk1d** [comment]
@frenzzy it works!  tks!

**Comment by martinnov92** [comment]
Hello @frenzzy , first I want to thank you for amazing solution. It worked like charm, but could you please explain me what this:

```
  componentDidMount() {
    this.props.onRef(this)
  }
```

is exactly doing? I am new in this so I would like to know why it works? :D 

Thank you very much

**Comment by Sartonon** [comment]
When you call the onRef function inside Child-component, you are calling the function passed from the parent component. 
`
this.props.onRef(this)
`
Here parameter this points to the child component itself and parent component receives that reference as the first parameter:
`
 onRef={ref => (this.child = ref)} 
`
and then it saves the reference with key "child". After that you have to whole child component reference accessible inside the parent component and you can call the child components functions.

for example:

`
this.child.method()
`

**Comment by martinnov92** [comment]
@Sartonon Thank you very much for nice explanation!

**Comment by Vamshikrishna209** [comment]
I am using a child component which is repeated many times dynamically , How can i give refs for that dynamic Components and Call them respectively on click ? Can you please help me with this.

**Comment by frenzzy** [comment]
@Vamshikrishna209 you can save references like so:
```js
<div>
  {this.props.array.map((item, index) =>
    <ChildComponent onRef={ref => (this[`example${index}`] = ref)} />
  )]
</div>
```
and then get access to it
```js
this.example0.childComponentMethod();
// or
this[`example${index}`].childComponentMethod();
```

**Comment by Vamshikrishna209** [comment]
@Sartonon  
Can you please explain it ?
I am using a widgets which are placed differently and having a unique names of values

<UploadWidget uploadValues={currentValue} uploadSuccess={self.uploadSuccess} onRef={ref => (  self[`currentValue`]= ref)}}

Am not able to give values there ,

**Comment by Vamshikrishna209** [comment]
@frenzzy 

Can you please explain it ?
I am using a widgets which are placed differently and having a unique names of values

<UploadWidget uploadValues={currentValue} uploadSuccess={self.uploadSuccess} onRef={ref => ( self[currentValue]= ref)}}

Am not able to give values there , in a loop , the ref is only taking the last value in the loop ,

**Comment by langpavel** [comment]
This is antipattern!

**Comment by ThaJay** [comment]
I just randomly found this because I want to write unit tests for component functions but to anyone coming here in the future: @langpavel is right, do not do this!

You should define the method on the parent, pass it to the child as prop and call it in the child;

```
class Thing extends Component {
  render () {
    return (
      <View>
        {getThings()}
      </View>
    )
  }

  getThings () {
    const thingNodes = []
    for (let thing of this.props.things) {
      thingNodes.push(<Child key={thing.id} thing={thing} doStuff={this.doStuff} />)
    }
    return thingNodes
  }

  doStuff () {
    // doTheStuff
  }
}

class Child extends Component {
  render () {
    return <View onClick={this.props.doStuff} />
  }
}
```

**Comment by dmr07** [comment]
@langpavel How should the app be structured so as to avoid this design pattern?

**Comment by langpavel** [comment]
@dmr07 If you need call child function, it indicates lack of data model in your app.
If you use redux, you just call an action creator. This can be complex, you can use redux-thunk or sagas or what you want, and as action creator creates actions, state will update and connected components will rerender.
You can of course use different approaches, like RxJS, but I highly recommend redux – it's simple and it will direct you to the right reactive way.. :wink:

**Comment by sahanDissanayake** [comment]
@langpavel why is this an anitpattern ?

**Comment by eromoe** [comment]
But how to set ref to `this.props.children`  ???
```
<Parent>
   <Child/ >
</Parent>
```

I want to call `Child` method in `Parent` .  That's mean `Child` is dynamic,

import React from 'react'
// can not import Child here
// import Child from './Child'  

class Parent extends React.Component {
  onClick = () => {
    this.child.method() // do stuff
  }
  render() {

    const {children} = this.props;
    return (
      <div>
        <button onClick={this.onClick}>Child.method()</button>
      </div>
    );
  }
}

**Comment by ThaJay** [comment]
It does not work like that. Restructure your data model as said before like so:
```
constructor (props) {
  super(props)
  this.state = {
    item: {}
  }
}

render () {
  <div>
    <Child method={(item) => this.setState({item})} item={this.state.item} />
  </div>
}
```

**Comment by eromoe** [comment]
I have worked it around by using `React.cloneElement` to pass `ref ` to children. Detail see:
https://stackoverflow.com/a/46187469/1637673

**Comment by ThaJay** [comment]
Perhaps something like this?

index.js
```js
import React from 'react'

class Parent extends React.Component {
  handleSubmit1 () {}

  handleSubmit2 () {}

  render () {
    return (
      <div>
        <Dialog visible={this.state.dialog1Visible}>
          <DialogChild1 / >
         <button onClick={this.handleSubmit1} />
        </Dialog>
        <Dialog visible={this.state.dialog2Visible}>
          <DialogChild2 / >
         <button onClick={this.handleSubmit2} />
        </Dialog>
      </div>
    )
  }
}
```

Get creative with your architecture, there shurely is a way to structure the code better. Or you haven't explained in enough detail why it it needed. But as react-starter-kit is a beginner package I assume the first.

**Comment by ThaJay** [comment]
I did not read your point properly. You want to pass child from higher up. See the following example. Of course you can use `this.props.children` but the child has to be selected somewhere.
```js
import React from 'react'
import getOnSubmit from './submitters.js'
import children from './children.js'

class Parent extends React.Component {

  componentWillMount () {
    const child = children.get(this.props.childName)
    const onSubmit = getOnSubmit(this.props.childName)

    this.setState({onSubmit, child})
  }

  render () {
    return (
      <div>
        <Dialog onSubmit={this.state.onSubmit}>
          {this.state.child}
        </Dialog>
      </div>
    )
  }
}

```

**Comment by andrewnaeve** [comment]
I have a parent that needs to call its child component every time a scroll event triggers for custom lazy loading. I have it set up so that when the parent is scrolled, setState toggles a boolean. The child receives this with componentWillReceiveProps, and triggers the child to check its position in the viewport.  Problem is that of course, each received prop triggers a re-render. I've debounced it, but am looking for a more elegant solution. 

I came here looking to circumvent updating state, hoping that the parent could simply tell the child to check its position on scroll, thereby avoiding re-render if not necessary. Is using refs still a bad idea in this case?

**Comment by ThaJay** [comment]
I would not bother thinking about the logic and just use a module. A quick google gave me the following:
https://www.npmjs.com/package/react-list-lazy-load
You could also just use it for inspiration.

**Comment by jose920405** [comment]
@frenzzy 

Thanks, your method is very similar to the delegates in the native ios

**Comment by henrikra** [comment]
@frenzzy How can you make HOC out of that logic?

So always when I want to get ref I don't have to add those `componentDidMount` etc. I would like to wrap a component to a HOC like this `withRef(MyChild)`

**Comment by frenzzy** [comment]
@henrikra you don't need HOC for this, example:
```js
import React from 'react'

class Child extends React.Component {
  render() {
    return <label>Input: <input ref={this.props.inputRef} /></label>
  }
}

class Parent extends React.Component {
  componentDidMount() {
    this.input.focus() // <= access to child ref
  }

  render() {
    return <Child inputRef={ref => this.input = ref} />
  }
}
```

**Comment by grneggandsam** [comment]
Ok, I don't understand all the people who think this is a structural problem and not needed.

Situation: You have a FEW DIFFERENT parent components which both contain the same child component. The child component is an alert.

The same actions will need to be made within the child components. The child component will always need to have an addAlert and removeAlert function.

Wouldn't it be nice if you could not have to re-write the methods passed down to the child components? Doesn't seem very DRY if you can't.

**Comment by ianakiara** [comment]
I think you guys are looking for something like this: https://stackoverflow.com/questions/37949981/call-child-method-from-parent

No needs to implement anything on the child
`   return (
      <div>
        <Child ref={instance => { this.child = instance; }} />
        <button onClick={() => { this.child.getAlert(); }}>Click</button>
      </div>
    );`

**Comment by koistya** [comment]
You can create an external object implementing "event emitter" pattern, for example:

```js
// auth.js
const callbacks = new Set();

export default {
  showLogin() {
    callbacks.forEach(fn => fn());
  },
  onShowLogin(callback) {
    callbacks.add(callback);
    return () => callback.delete(callback);
  },
}
```

```js
// Child.js
class Child extends React.Component {
  componentDidMount() {
    this.unlisten = auth.onShowLogin(() => { ... });
  }

  componentWillUnmount() {
    this.unlisten();
  }

  render() { ... }
}
```

```js
// Parent.js
class Parent extends React.Component {
  render() {
    return <div><Child /><button onClick={auth.showLogin} /></div>;
  }
}
```

Or, you can implement the same functionality with Flux, Redux or Relay Modern (it provides API for working with the client-side state).

**Comment by vitto-moz** [comment]
Today I find next solution
 I need to get my component wrapped with a function (because it receives url from routing functionality)
Child component looks like this
```
const externalVideo = ({uri}) => {
  return <VideoBlock
            >
              {(parent) => <ExternalVideo parent={parent} ref={ref => parent.webViewComponent = ref }/>}
        </VideoBlock>
}
```

VideoBlock component has next render method 
```
render() {
    return (
      <View style={styles.videoBlockWrap}>
          {this.props.children(this)}
      </View>
    );
  }
```

After this preparations, I can simply invoke child's method with next syntax:
method in parent topic 
 ```
onCreateTopicPress = () => {
    this.webViewComponent.getCurrentSelection()
  }
```

**Comment by goredefex** [comment]
I don't fully agree with things in this conversation and I have no idea how to get it to change in the React world of design patters. Calling methods on a child component should not be an anti-pattern or considered a bad pattern. It should be encouraged given certain use cases. 

For example: I have a silly game app and all you have to do is drag little circles from one side of the screen to the other. Sometimes there can be over 200 of them at once on screen. Many MANY times I need to know the positions and a number of state values in my child components of these circles. Also, many other times, I need the parent (which is the game itself) to not only house all of the logic of the game, which the circles should NOT know, but also update things based on it's rules. Often this involves changing the state of one of the components...

To say that I should be putting over 200 items and their states into Redux or application state is total poppycock! Application state is supposed to be simple, clean, derivable objects and not to go crazy with because of badly things can get slowed down if you keep choosing to just casually throw everything into app state. Now imagine as I drag them, that I need to update their state through redux every pixel! Not only am I updating a massive state object consistently but I am also causing render logic to have to ripple down through the components using this state...

Why not have the ability for the parent to call a clean, concise method to access it's own component state safely? It would be clean because the component owns it's own state changing functions and can allow/disallow clean/dirty choices of access.

**Comment by pstanton** [comment]
the desire to use an antipatern usually identifies a shortcoming in the framework

**Comment by jamessawyer** [comment]
how can I pass a 'ref' to Child Component from Parent Component?
```
// Child Component
import React, { PureComponent } from 'react';
import PropTypes from 'prop-types';
import { TextInput } from 'react-native';

export default class MyTextInput extends PureComponent {
  // child method
  // to get focus the input
  getFocus = () => {
    this.refs[this.props.next].focus()
  }
  render() {
    return (
      <TextInput
        ref = {this.props.next}
        autoCapitalize='none'
        autoCorrect={false}
        underlineColorAndroid='transparent'
        allowFontScaling={false}
        {...this.props}
      />
    );
  }
}

// parent Component
class Parent extends PureComponent {
  return (
    <View>
      <MyTextInput
        onSubmitEditing={() => {}} // I wanna use child component's getFocus() method here
      />
      <MyTextInput
        next='childRef'
      />
    </View>
  )
}
```

**Comment by francisngo** [comment]
With a little tweak of @frenzzy's solution, I was able to get it to work with "withStyles" higher order  component from isomorphic-style-loader

**Comment by crrobinson14** [comment]
I realize this issue is closed. The ONLY reason I'm replying to it is because it's now the #1 Google search result for `react native call component method`, which is how I ended up here myself. Some of the details here may be confusing for the casual passer-by, and I'd like to add two quick clarifications:

1. ReactJS is actually agnostic about this technique. I just went back through the docs on refs and ref usage and other than one caution against overuse, at no time is this specifically forbidden or referred to there as an anti-pattern. In fact, the more complex use case, where refs are dealt with through multiple layers of parent->child calls, has an entire documentation page (Forwarding Refs) describing how to do it properly and why you might want it.

2. The closely related React Native library EXTENSIVELY uses this method to provide Component-level APIs (https://facebook.github.io/react-native/docs/webview#goback, among many dozens of examples). If you are using React as part of React Native, this is absolutely not an antipattern there - the core devs use it and document it as a standard technique.

Many of the suggestions above for working around this method are useful to know. I don't personally agree that a much longer solution or library dependency to avoid a 2-line option is objectively "better", or that this option (direct ref-taking) is indeed even a true "antipattern," but that's my personal opinion. I respect the authors of this starter kit, their work, and their goals for how it's meant to be used. My comments here apply only to those looking for this solution generally (particularly in React Native, as I was before I went on this fact-checking goose chase), NOT in the context of React Starter Kit.

**Comment by theCuriousOne** [comment]
Let me add some more advice to the pour soul that might be having some issue with the referencing of child component.

> THE **REF** DOES NOT WORK IF THE CHILD COMPONENT IS BEING LAZY LOADED!

I lost almost 2 days before realizing that. After i removed the **react-loadable** (the npm package that makes any react component lazy loadable), the referencing worked nicely like mentioned by several people above

**Comment by muwae** [comment]
Based on @joeytwiddle solution, i've implemented this another solution, who have worked very fine. 

class Parent extends Component {
    render() {
      return (
        <div>
          {/* Give the child a callback, so it can share its methods with us. */}
          {React.cloneElement(this.props.children, {onChildDoAlert: _handleChildDoAlert => {this.childDoAlert = _handleChildDoAlert}})}
          {/* We can now call the child's method directly! */}
          <button onClick={this.childDoAlert}>Click</button>
        </div>
      );
    }
  }
  
  class Child extends Component {
    componentDidMount() {
        // Child passes its method to the parent
        this.props.onChildDoAlert(this.handleDoAlert.bind(this))
        // or you can pass the implementation directly
        // this.props.onChildDoAlert(() => {
        //     alert('clicked')
        // })
    }
    handleDoAlert() {
      alert('clicked');
    }
    render() {
      return (
        <h1>Hello</h1>
      );
    }
  }

**Comment by YisraelV** [comment]
Here is an example why I think this is not an antipattern:

You have a panel component that can be in an "folded" or "unfolded" state.  The component includes a button to fold\unfold.

Now you have a parent component with several of such panels. You have a buttons in parent "fold all" and "unfold all" which cause all the accordions to fold\unfold.

You could pass a "open=false" as a prop. The problem is now you have two sources of truth: the parent's (which is passed as a prop) and the child's (which is changed with setState on every click)

What you might do is make the parent the single source of truth, and on every click of the child call "onClick" callback and have the parent modify the state.

That might work but is not intuitive. Why should the child tell the parent it was clicked just so the parent can tell it again "yes you were clicked" using a prop? Intuitively the child owns the state here. And intuitive app is more readable and understandable.

On the other hand changing the child's state using a method conveys the message: the child owns the state here, and it allows others to ask him to change.

**Comment by mfaheemakhtar** [comment]
I have not read everything but I was facing the same issue. Instead of using refs. I used callback.

I had to reset the form fields once the container has submitted the form.

Child:


```js
validateFields((err, values) => {
    // handleSubmit is from the parent (props)
    handleSubmit(err, values, () => {
        form.resetFields();
    });
});
```

Parent:

```js
handleSubmit = (err, values, resetFields) => {
    // my code
    resetFields();
}
```
Anti-Pattern?

**Comment by yairEO** [comment]
@langpavel - You explanation of why this is an anti-pattern, and suggesting to use Redux is not satisfactory.

React should handle such basic needs without the needs of an external independent tool such as Redux.

Components are instances of javascript classes (or functions) and there should be a "reactive" way to simply access the instances' methods from the parent, in React.

## For example: 
I have `N` times on the screen and one button to reset them all.
Each timer has its own state, and methods (`start`, `stop`, `restart`), each timer works independently. I cannot pass props to the timers to restart because that makes no sense. A "restart" is a once-time thing and not a prop is permanent until changes. having a timeout set it back to `false` is wrong.

Back in the good days, in vanilla JS, i could easily create an instance of a timer from a parent, and render it using my vanilla framework, and from the parent component loop on all the child instances which are timers and call each of those `restart` methods.

----

Why, for such a *simple* app, would I need Redux or RXJX for? it's insane.

**Comment by vpillinger** [comment]
@yairEO The issue is less that using refs is an anti-pattern and more that refs are just unnecessarily difficult to work with.

You can write 2-3 lines of code and pass a silly callback or you can write 15-20 lines of code to track the refs and call the child function. This gets super annoying when your adding/removing elements. Imagine you were writing a dashboard with custom blocks that could be customized, but had to refresh every 30 seconds to update their data. However, you also needed a manual refresh button. What if that refresh button could also be moved around the page?

This is very similar to your use case with the timers and it really shows where React falls short.

Trying to track all the refs down into the dashboard would be a nightmare. It may be simple enough, but if you allow components to be nested then... 💥.

I would actually argue that the callback method is the anti-pattern since its a convoluted replacement of observer pattern. Ultimately, the issue is that React doesn't provide a way to fire/listen-to custom events.

What your really looking for is something like this: https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events or something like what Vue does https://vuejs.org/v2/guide/components-custom-events.html. How this works is to fire a "refresh" event and observe it with the individual timers who are responsible for handling the event appropriately.

**Comment by strommj** [comment]
Another solution:
Ditch react and use Angular, haha.  You'll have all the state control you'll ever need brought to you by mutable classes!

**Comment by lukewlms** [comment]
We use a custom hook called useCounterKey to send events to children.  Although it's not as straightforward as e.g. a simple HTML event handler, it's less messy than using refs (the data flow is only one-way) and is pretty React-idiomatic (since incrementing keys can already be used to reset components).

Details here on how we're using it: https://stackoverflow.com/a/60568459/152711

**Comment by sli782** [comment]
> I found a reasonably sensible solution to this problem by ['brickingup' on StackOverflow](https://stackoverflow.com/a/45582558/99777).
> 
> The idea is that the parent passes a callback function to the child, and the child calls that function, to pass its method(s) to the parent. The parent can then store the methods locally.
> 
> The important code is commented below.
> 
> ```js
> class Parent extends Component {
>   acceptMethods(childDoAlert) {
>     // Parent stores the method that the child passed
>     this.childDoAlert = childDoAlert;
>   }
>   render() {
>     return (
>       <div>
>         {/* Give the child a callback, so it can share its methods with us. */}
>         <Child shareMethods={this.acceptMethods.bind(this)}/>
>         {/* Later we can call the child's method directly! */}
>         <button onClick={() => this.childDoAlert()}>Click</button>
>       </div>
>     );
>   }
> }
> 
> class Child extends Component {
>   componentDidMount() {
>     // Child passes its method to the parent
>     this.props.shareMethods(this.doAlert.bind(this));
>   }
>   doAlert() {
>     alert('clicked');
>   }
>   render() {
>     return (
>       <h1>Hello</h1>
>     );
>   }
> }
> ```
> 
> If you want to receive more than one method from the child, then change `shareMethods` and `acceptMethods` to pass an object instead of just one function.
> 
> For clarity, I think the `acceptMethods` function should be placed as close to the constructor as possible.

Thanks!!!

**Comment by dfyz011** [comment]
Example with functional components and useRef hook:

/* Child.js */
```
import React, { useEffect } from "react";
import withStyles from "isomorphic-style-loader/lib/withStyles";
import s from "./Child.css";

const Child = () => {
	useEffect(() => {
		onRef(() => {
			console.log("lol");
		});
	}, []);
	return <h1 className={s.root}>Hello World!</h1>;
};

export default withStyles(s)(Child);
```

/* Parent.js */
```
import React, { useRef } from "react";
import Child from "./Child";

const callbackRef = useRef();

const Parent = () => {
	onClick = () => {
		this.child.method(); // do stuff
	};

	return (
		<div>
			<Child
				onRef={(callback) => {
					callbackRef.current = callback;
				}}
			/>
			<button
				onClick={() => {
					callbackRef && callbackRef.current();
				}}
			>
				Child.method()
			</button>
		</div>
	);
};
```

**Comment by mattgle** [comment]
The answer from @dfyz011 works but not in TypeScript, here's the TS option, hope it helps 😄 

/* Child.tsx */

```ts
import React, { useEffect } from "react";

type Props {
   onRef: (callback: Function) => void;
 }

export const Child: React.FC<Props> (onRef) => {
  useEffect(() => {
    onRef(() => {
      console.log("Dude, see? It's working!");
    });
  }, [onRef]);
  
  return <h1 className={s.root}>Hello World!</h1>;
};
```

/* Parent.tsx */

```ts
import React, { useRef } from "react";
import Child from "./Child";

const callbackRef = useRef();

export const Parent = () => {
  const callbackRef = useRef<Function>();
  const handleOnRef = (callback: Function) => {
    callbackRef.current = callback;
  };
  
  return (
    <div>
      <Child onRef={handleOnRef} />
      <button
        onClick={() => {
          callbackRef?.current?.();
        }}
      >
        Child.method()
      </button>
    </div>
  );
};
```
