### ISSUE TITLE
How to auto restart when code changed? 

### ISSUE THREAD

**Issue by bexoss** [kriasoft/react-starter-kit#910]
How to restart when codes are changed? 

I don't know well, so I just break tasking with Ctrl+C on Windows, 

and "npm start" again. 

It is little bit inconvenient. 

any better way?

**Comment by frenzzy** [comment]
The app automatically rebuilds after file changes and restarts the server after that, you do not need to stop and re-run `npm start`. Try to refresh the page in your browser, you should see latest changes.

If the changes are still not visible, please let us know which file you are trying to change.

**Comment by ulani** [comment]
@bexoss   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
