### ISSUE TITLE
configure webpack for less

### ISSUE THREAD

**Issue by gauravprwl14** [kriasoft/react-starter-kit#914]
hi, i want to use less for styling the component. i am facing problem in configuring the less in the webpack. i am working in feature/bootstrap3  branch. i would be great if you can give one example how to use less styling in the header component.

i tired adding less configuration in the modules loader inside webpack configuration file but it didn't work out. below is the code which i added in the webapck configuration file 
`{
        test: /\.less$/,
        loaders: [
          'isomorphic-style-loader',
`css-loader?${JSON.stringify({ sourceMap: DEBUG, minimize: !DEBUG })}`,
          'postcss-loader?pack=less',
          'less-loader',
        ],
      }`

**Comment by nisargrthakkar** [comment]
@gauravprwl14  any update on this? I tried to configuring less css with this starter kit but its not working yet. If you have any working example please share with us. Thank you in advance

**Comment by TristanDongMaster** [comment]
how to resolve it ?

**Comment by ulani** [comment]
@gauravprwl14   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
