### ISSUE TITLE
bootstrap3 branch : can't build -- --release

### ISSUE THREAD

**Issue by kenny1har** [kriasoft/react-starter-kit#919]
npm run build -- --release

```
[00:05:14] Finished 'copy' after 28 ms
[00:05:14] Starting 'bundle'...
Child
    Time: 11904ms
                           Asset    Size  Chunks             Chunk Names
    main.32a383820683636ac44c.js  311 kB       0  [emitted]  main

    ERROR in ./src/components/Header/Header.js
    Module build failed: TypeError: /media/aabb/Drive1/rsk/src/components/Header/Header.js: Property object of JSXMemberExpression expected node to be of a type ["JSXMemberExpression","JSXIdentifier"] but instead got "MemberExpression"

```

**Comment by ulani** [comment]
@kenny1har   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
