### ISSUE TITLE
Adding bootstrap javascript

### ISSUE THREAD

**Issue by l4u** [kriasoft/react-starter-kit#93]
What's the recommended way to load jQuery and Bootstrap JavaScript?

**Comment by koistya** [comment]
Bootstrap related files are going to be removed from this starter kit soon. You can use [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap) as a replacement. Though keep in mind, while Bootstrap is an excellent solution for prototyping your initial project, it's generally not a good idea to use it in real web application projects.

**Comment by l4u** [comment]
Thanks!

**Comment by rstormsf** [comment]
@koistya Why bootstrap is not a good idea to use in real web apps?

**Comment by korczis** [comment]
Maybe you should think of this @koistya. This is not first request - https://github.com/kriasoft/react-starter-kit/issues/138

**Comment by 9gix** [comment]
After looking at one of the grid css class that seems to have a similar class naming as bootstrap `col-sm-4` at https://github.com/kriasoft/react-starter-kit/blob/master/src/content/index.jade#L6, then I wonder why the index page doesn't show 3 columns instead. And realize that bootstrap wasn't included in the starter kit.

I use bootstrap as prototyping functionality. When it comes to building real application, I prefer not to use bootstrap because it is bloated and customization is not easy in my opinion.

I also think it is good to keep bootstrap as a separate part, because we may have a different css framework choice, such as Zurb Foundation.

@koistya what about the `col-sm-4`? do we need a grid system in the starter kit? or perhaps we can remove the `col-sm-4` class, because it doesn't affect anything.?

**Comment by koistya** [comment]
@9gix good point, need to remove these `col-sm-4` classes to avoid confusion. Another idea is to convert static pages from Jade to Markdown.

**Comment by nickeblewis** [comment]
That explains that then! I was asking about this on Gitter
