### ISSUE TITLE
Why don't you export process.env.NODE_ENV in the config? What about local config?

### ISSUE THREAD

**Issue by Vadorequest** [kriasoft/react-starter-kit#931]
I wonder why don't you export `process.env.NODE_ENV` from the `src/config.js` file. Is it something you've missed or is it by design?

I'd add the following at the very beginning of the config.
`export const env = process.env.NODE_ENV || 'development';`

And load it when needed.

Also, I'd add a `config-default.yml` and `config-local.yml` to store the default configuration and the local configuration, and merge both of them (config-local taking priority) in the `config.js`. Easier for the dev environment and allow to keep sensitive stuff, like passwords or tokens out of github.

**Comment by ulani** [comment]
@Vadorequest   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
