### ISSUE TITLE
Does not support  js nested require css

### ISSUE THREAD

**Issue by IDrinkMoreWater** [kriasoft/react-starter-kit#947]
**Register router **

```
import React, { PropTypes } from 'react';
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import Layout from '../../components/Layout';
import '../../../node_modules/antd-mobile/lib/style';
import Button from '../../../node_modules/antd-mobile/lib/button';
import s from './Register.css';

function Register({ title }) {
  return (
    <Layout>

      <div className={s.root}>

        <div className={s.container}>
            <Button>Start</Button>
          <h1>{title}</h1>
          <p>...</p>
        </div>
      </div>
    </Layout>
  );
}

Register.propTypes = { title: PropTypes.string.isRequired };

export default withStyles(s)(Register);

```

**in style folder,  index.js  code:  **

```
'use strict';

require('../../style/');

require('../../icon/style/');

require('./index.css');
```

 **Problem**

`console no error log. The  Register page,but I can't get CSS to load.`

**Comment by zhw2590582** [comment]
I have same issues when I use antd too, Did you solve this problem?

**Comment by ulani** [comment]
@IDrinkMoreWater   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
