### ISSUE TITLE
copyDir cannot process dirs with '.'

### ISSUE THREAD

**Issue by DzenisevichK** [kriasoft/react-starter-kit#972]
I extened `/tools/copy.js` with copy `/node_modules/amcharts3` to `/public/lib` but got error:

```text
[14:53:40] Starting 'start'...
[14:53:40] Starting 'clean'...
[14:53:40] Finished 'clean' after 462 ms
[14:53:40] Starting 'copy'...
Error: EISDIR: illegal operation on a directory, open 'D:\Projs\nav-tu\charts\build\public\lib\amcharts3\amcharts\plugins\export\libs\blob.js'
    at Error (native)
```

Here `blob.js` is directory...

Fast solution for me was adding `nodir: true` option for `readDir` call in `fs.js:copyDir` function...

**Comment by mantap123** [comment]
Any  update?

I am integrating a paid ReactJS theme, you can see the detail here:

- [https://wrapbootstrap.com/theme/rubix-reactjs-powered-admin-template-WB09498FH](url)
- [http://rubix410.sketchpixy.com/](url)

when start the project by npm start command, it was stopped:
`Error: EISDIR: illegal operation on a directory, open '/Users/user123/veedy/admin/build/public/js/vendor/ion.rangeSlider'`

**Comment by ulani** [comment]
@DzenisevichK   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
