### ISSUE TITLE
Embed to Facebook Tab

### ISSUE THREAD

**Issue by mxmtsk** [kriasoft/react-starter-kit#973]
I wanna embed my app to a Facebook's Fan Page Tab but Facebook does send a Post Request. I tried changing the route to use app.use instead of app.get but when I do that SSR does not work anymore, but I don't really understand why? Can you maybe explain to me why SSR breaks when requested via post?

**Comment by ulani** [comment]
@mxmtsk   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
