### ISSUE TITLE
Cannot set port on c9

### ISSUE THREAD

**Issue by x5engine** [kriasoft/react-starter-kit#974]
Hello guys,
this is a very good project and great work you did here!

I am not able to set the port and even if I get the app running with the port 8080 and localhost or 0.0.0.0 the graphql crashes and doesn't let the app to run!

thank you so much

**Comment by ulani** [comment]
@x5engine   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
