### ISSUE TITLE
How you to use MongoDB with this react starter kit

### ISSUE THREAD

**Issue by x5engine** [kriasoft/react-starter-kit#975]
Hello Guys,

I am confused on how to use MongoDb with this great app!
isn't there a config file where you can add your mongodb string and it will work?
I saw one in the the config file.... but not sure

thanks :)

**Comment by Jaikant** [comment]
I integrated mongoose, included the mongoose schema in /src/data/models/filename.js

**Comment by koistya** [comment]
@meteorplus here is a small example with MongoDB native driver:

https://medium.com/@tarkus/how-to-open-database-connections-in-a-node-js-express-app-e14b2de5d1f8#.n5g11yjqt

**Comment by sudhiryadav** [comment]
It uses sequelize for orm. Couldn't find the solution for using mongo db using mongoose. Is there any possibility?

**Comment by ulani** [comment]
@x5engine   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
