### ISSUE TITLE
RSK breaks if started while offline (server side error)

### ISSUE THREAD

**Issue by buildbreakdo** [kriasoft/react-starter-kit#978]
Reproduction steps:

git clone git@github.com:kriasoft/react-starter-kit.git
cd react-starter-kit
npm install
disconnect from internet (go get on your bus, plane, train)
npm start

Fetch example breaks server side on first load, but not on second, don't understand why. 

 ```
Error: Failed to load the news feed.
  
  - index.js:32 Object._callee$
    /Users/foo/react-starter-kit/build/webpack:/routes/home/index.js:32:36
  
  - runtime.js:63 tryCatch
    [react-starter-kit]/[regenerator-runtime]/runtime.js:63:40
  
  - runtime.js:337 Generator.invoke [as _invoke]
    [react-starter-kit]/[regenerator-runtime]/runtime.js:337:22
  
  - runtime.js:96 Generator.prototype.(anonymous function) [as next]
    [react-starter-kit]/[regenerator-runtime]/runtime.js:96:21
  
  - asyncToGenerator.js:17 step
    [react-starter-kit]/[babel-runtime]/helpers/asyncToGenerator.js:17:30
  
  - asyncToGenerator.js:28 
    [react-starter-kit]/[babel-runtime]/helpers/asyncToGenerator.js:28:13

```

Refresh the page and it works. Bad first impression for people that use their disconnected downtime to explore projects like this.

**Comment by koistya** [comment]
A while ago there was a pull request tweaking tools/runServer.js or tools/start.js so that the server shuts down in case of an error. I think we need to rollback this commit.

**Comment by ulani** [comment]
@buildbreakdo   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
