### ISSUE TITLE
Webpack watch not work in vagrant

### ISSUE THREAD

**Issue by amorev** [kriasoft/react-starter-kit#993]
Hello! 

I try to turn on webpack watch by using poll and it doesn't work. I need it because i am using vagrant to develop

I added here tools/webpack.config.js:130
`watchOptions: {
    poll: 100,
    aggregateTimeout: 100
  },` 

and it didn't help. What should I do? Thank you very much!

**Comment by andrewhickey** [comment]
You need to add it to tools/start.js line 53 :)

**Comment by zvinger** [comment]
@andrewhickey Thanks!

**Comment by ulani** [comment]
@amorev   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
