### ISSUE TITLE
Is the user login system supposed to work?

### ISSUE THREAD

**Issue by PrincipalsOffice** [kriasoft/react-starter-kit#994]
When I run the project, there is nothing on the register page, and the social login are not working either even after I replace the oauth keys.

**Comment by HildoBijl** [comment]
Wondering the same thing. Have spent a few hours on this, but not sure what's supposed to happen. I also cannot find any documentation on this.

**Comment by maksimkurb** [comment]
Facebook OAuth is implemented, but it does not work properly.
This is my working example (I switched to Bookshelf.JS due to some bugs in Sequelize): [gist@17c7dddab564a9e76263fd24c27f5e87](https://gist.github.com/maksimkurb/17c7dddab564a9e76263fd24c27f5e87)

**Comment by ulani** [comment]
@PrincipalsOffice    thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
