### ISSUE TITLE
Pass propTypes definition between classes

### ISSUE THREAD

**Issue by archansel** [kriasoft/react-starter-kit#996]
I've been working on my project for quite some time, always in development mode (never use `npm start -- --release`). When I tried using `npm start -- --release` it crashes and says **TypeError: Cannot read property 'path' of undefined**. 

I encountered this problem before when trying to move propTypes definition inside a class. When I move propTypes definition inside the class, I cannot use `const { path, ...innerPropTypes } = Image.propTypes;`. It seems in release mode I cannot get propTypes directly from a class (in this case an Image class) but work fine in development.

I'm quite new with this react things and stuck with this problems, if it can't be solved it seems I need another way to pass propTypes between classes

**Comment by frenzzy** [comment]
https://fb.me/react-warning-dont-call-proptypes

**Comment by archansel** [comment]
do you have suggestion how to pass proptypes between classses @frenzzy ?

**Comment by ulani** [comment]
@archansel   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
